// prettier-ignore

export const WORDS = [
 
  
  // === OBJETOS (Concretos / Simples / Compostos) ===
  {word: "Óculos",category: "Objetos",related: ["Lente de Contato"],hint: "Melhora a percepção visual de quem usa.",},
  {word: "Lente de Contato",category: "Objetos",related: ["Óculos"],hint: "Fica em contato direto com o globo ocular.",},
  {word: "Guarda-chuva",category: "Objetos",related: ["Capa de Chuva"],hint: "Um escudo portátil contra a água que cai do céu.",},
  {word: "Capa de Chuva",category: "Objetos",related: ["Guarda-chuva"],hint: "Uma vestimenta impermeável para dias úmidos.",},
  {word: "Teclado",category: "Objetos",related: ["Máquina de Escrever"],hint: "Possui muitas teclas para registrar caracteres.",},
  {word: "Máquina de Escrever",category: "Objetos",related: ["Teclado"],hint: "Um dispositivo mecânico clássico para redigir textos.",},
  {word: "Espelho",category: "Objetos",related: ["Reflexo"],hint: "Sua superfície devolve a imagem fiel do que está à frente.",},
  {word: "Reflexo",category: "Objetos",related: ["Espelho"],hint: "Uma duplicata visual gerada por luz ou água.",},
  {word: "Cadeira",category: "Objetos",related: ["Poltrona"],hint: "Móvel básico feito para suportar uma pessoa sentada.",},
  {word: "Poltrona",category: "Objetos",related: ["Cadeira"],hint: "Geralmente mais macia e com braços para maior conforto.",},
  {word: "Bicicleta",category: "Objetos",related: ["Patinete"],hint: "Veículo de duas rodas movido pelo esforço das pernas.",},
  {word: "Patinete",category: "Objetos",related: ["Bicicleta"],hint: "Possui uma prancha estreita e um guidão para equilíbrio.",},
  {word: "Fone de Ouvido",category: "Objetos",related: ["Caixa de Som"],hint: "Privatiza a experiência sonora para apenas um indivíduo.",},
  {word: "Caixa de Som",category: "Objetos",related: ["Fone de Ouvido"],hint: "Amplifica vibrações sonoras para todo um ambiente.",},
  {word: "Relógio de Pulso",category: "Objetos",related: ["Despertador"],hint: "Acessório que nos mantém situados no fluxo do dia.",},
  {word: "Despertador",category: "Objetos",related: ["Relógio de Pulso"],hint: "Sua principal função é interromper o repouso de alguém.",},
  {word: "Lanterna",category: "Objetos",related: ["Lâmpada"],hint: "Uma fonte de luz portátil usada em lugares escuros.",},
  {word: "Lâmpada",category: "Objetos",related: ["Lanterna"],hint: "Converte energia elétrica em radiação luminosa fixa.",},
  {word: "Martelo",category: "Objetos",related: ["Marreta"],hint: "Ferramenta de impacto usada para fixar pregos.",},
  {word: "Marreta",category: "Objetos",related: ["Martelo"],hint: "Versão pesada e bruta de uma ferramenta de percussão.",},
  // === FAMOSOS (Brasil - TV, Música, Internet) ===
  {word: "Silvio Santos",category: "Famosos",related: ["Faustão"],hint: "Um dos maiores ícones da comunicação.",},
  {word: "Faustão",category: "Famosos",related: ["Silvio Santos"],hint: "Conhecido por seu bordão 'Oloco bicho' e longos domingos na TV.",},
  {word: "Anitta",category: "Famosos",related: ["Ludmilla"],hint: "Cantora carioca que alcançou grande sucesso internacional.",},
  {word: "Ludmilla",category: "Famosos",related: ["Anitta"],hint: "Grande voz do pagode e funk atual, iniciou como MC Beyoncé.",},
  {word: "Neymar",category: "Famosos",related: ["Pelé"],hint: "O principal craque da seleção brasileira na última década.",},
  {word: "Pelé",category: "Famosos",related: ["Neymar"],hint: "O eterno Rei do Futebol e atleta do século.",},
  {word: "Casimiro",category: "Famosos",related: ["Felca"],hint: "Fenômeno das lives, conhecido por reagir a tudo no YouTube.",},
  {word: "Felca",category: "Famosos",related: ["Casimiro"],hint: "Criador de conteúdo, faz vídeos sarcástico, reflexivos e com o humor ácido.",},
  {word: "Whindersson Nunes",category: "Famosos",related: ["Felipe Neto"],hint: "Começou com vídeos simples no Piauí e virou gigante no humor.",},
  {word: "Felipe Neto",category: "Famosos",related: ["Whindersson Nunes"],hint: "Um dos primeiros grandes YouTubers do Brasil, muito influente na política.",},
  {word: "Ivete Sangalo",category: "Famosos",related: ["Claudia Leitte"],hint: "A rainha do axé baiano, amada por quase todo o Brasil.",},
  {word: "Claudia Leitte",category: "Famosos",related: ["Ivete Sangalo"],hint: "Cantora loira de axé que também brilhou no Babado Novo.",},
  {word: "Luciano Huck",category: "Famosos",related: ["Marcos Mion"],hint: "Apresentador que comanda as tardes de domingo atualmente.",},
  {word: "Marcos Mion",category: "Famosos",related: ["Luciano Huck"],hint: "Conhecido pelo estilo enérgico e por apresentar o 'Caldeirão'.",},
  // === COMIDA E BEBIDA (Brasil) ===
  {word: "Coxinha",category: "Comida",related: ["Empada"],hint: "Salgado clássico que tem formato de gota e recheio de frango.",},
  {word: "Empada",category: "Comida",related: ["Coxinha"],hint: "Salgado de massa podre que derrete na boca.",},
  {word: "Feijoada",category: "Comida",related: ["Dobradinha"],hint: "Prato nacional feito à base de feijão preto e carnes suínas.",},
  {word: "Dobradinha",category: "Comida",related: ["Feijoada"],hint: "Prato polêmico feito com o bucho do animal.",},
  {word: "Pão de Queijo",category: "Comida",related: ["Chipas"],hint: "A maior iguaria mineira, essencial no café da manhã.",},
  {word: "Chipas",category: "Comida",related: ["Pão de Queijo"],hint: "Parecido com o pão de queijo, mas com formato de ferradura.",},
  {word: "Brigadeiro",category: "Comida",related: ["Beijinho"],hint: "O doce indispensável em qualquer festa de aniversário brasileira.",},
  {word: "Beijinho",category: "Comida",related: ["Brigadeiro"],hint: "Doce feito de leite condensado e coco ralado.",},
  {word: "Cerveja",category: "Comida",related: ["Chopp"],hint: "Bebida fermentada de malte, muito consumida em churrascos.",},
  {word: "Chopp",category: "Comida",related: ["Cerveja"],hint: "Bebida servida fresca e sob pressão, com colarinho de espuma.",},
  {word: "Guaraná",category: "Comida",related: ["Coca-Cola"],hint: "Refrigerante tipicamente brasileiro feito de uma fruta da Amazônia.",},
  {word: "Coca-Cola",category: "Comida",related: ["Guaraná"],hint: "O refrigerante de cola mais famoso e consumido do mundo.",},
  // === SUBSTANTIVOS ABSTRATOS / EMOÇÕES ===
  {word: "Amor",category: "Emoções",related: ["Paixão"],hint: "Sentimento profundo e duradouro de afeição por alguém.",},
  {word: "Paixão",category: "Emoções",related: ["Amor"],hint: "Sentimento intenso, avassalador e muitas vezes passageiro.",},
  {word: "Felicidade",category: "Emoções",related: ["Alegria"],hint: "Estado de espírito pleno e satisfação com a vida.",},
  {word: "Alegria",category: "Emoções",related: ["Felicidade"],hint: "Manifestação momentânea de contentamento e vivacidade.",},
  {word: "Saudade",category: "Emoções",related: ["Nostalgia"],hint: "Palavra única da nossa língua para a falta de algo ou alguém.",},
  {word: "Nostalgia",category: "Emoções",related: ["Saudade"],hint: "Desejo sentimental de retornar a um momento do passado.",},
  {word: "Medo",category: "Emoções",related: ["Fobia"],hint: "Reação natural de proteção diante de um perigo real ou imaginário.",},
  {word: "Fobia",category: "Emoções",related: ["Medo"],hint: "Um temor exagerado e irracional diante de algo específico.",},
  {word: "Coragem",category: "Emoções",related: ["Audácia"],hint: "A capacidade de agir mesmo diante do temor.",},
  {word: "Audácia",category: "Emoções",related: ["Coragem"],hint: "Um ímpeto de arriscar-se de forma ousada ou atrevida.",},
  // === COLETIVOS / SUBSTANTIVOS COLETIVOS ===
  {word: "Alcateia",category: "Substantivos variados",related: ["Matilha"],hint: "Grupo organizado de predadores que uivam para a lua.",},
  {word: "Matilha",category: "Substantivos variados",related: ["Alcateia"],hint: "Designação para um grupo numeroso de cães de caça.",},
  {word: "Cardume",category: "Substantivos variados",related: ["Enxame"],hint: "Um grande grupo de seres que respiram debaixo d'água.",},
  {word: "Enxame",category: "Substantivos variados",related: ["Cardume"],hint: "Multidão de insetos voadores que trabalham juntos.",},
  {word: "Constelação",category: "Substantivos variados",related: ["Galáxia"],hint: "Agrupamento de pontos luminosos que formam figuras no céu.",},
  {word: "Galáxia",category: "Substantivos variados",related: ["Constelação"],hint: "Sistema gigantesco que contém bilhões de estrelas e planetas.",},
  {word: "Arquipélago",category: "Substantivos variados",related: ["Ilha"],hint: "Um conjunto ou cadeia de porções de terra cercadas por água.",},
  {word: "Ilha",category: "Lugares",related: ["Arquipélago"],hint: "Uma porção solitária de terra firme rodeada pelo oceano.",},
  // === PERSONAGENS E CULTURA POP (Brasil e Global) ===
  {word: "Mônica",category: "Personagens",related: ["Magali"],hint: "Dona da rua e inseparável do seu coelho de pelúcia.",},
  {word: "Magali",category: "Personagens",related: ["Mônica"],hint: "Melhor amiga da protagonista, conhecida por seu apetite sem fim.",},
  {word: "Cebolinha",category: "Personagens",related: ["Cascão"],hint: "Menino que troca o R pelo L e cria planos infalíveis.",},
  {word: "Cascão",category: "Personagens",related: ["Cebolinha"],hint: "Personagem que tem um medo terrível de água e higiene.",},
  {word: "Harry Potter",category: "Personagens",related: ["Luke Skywalker"],hint: "O órfão que descobriu ser um bruxo famoso.",},
  {word: "Luke Skywalker",category: "Personagens",related: ["Harry Potter"],hint: "O jovem fazendeiro que se tornou um mestre na Força espacial.",},
  {word: "Homem-Aranha",category: "Personagens",related: ["Batman"],hint: "Herói que ganha poderes após a picada de um animal.",},
  {word: "Batman",category: "Personagens",related: ["Homem-Aranha"],hint: "Herói sombrio que utiliza a inteligência e o dinheiro como armas.",},
  {word: "Pica-Pau",category: "Personagens",related: ["Pernalonga"],hint: "Pássaro azul e doido, muito amado nas manhãs da TV brasileira.",},
  {word: "Pernalonga",category: "Personagens",related: ["Pica-Pau"],hint: "Coelho astuto que sempre pergunta 'O que que há, velhinho?'.",},
  // === JOGOS E VIDEO GAMES ===
  {word: "Super Mario",category: "Video Games",related: ["Sonic"],hint: "Encanador italiano que resgata uma princesa em um reino de cogumelos.",},
  {word: "Sonic",category: "Video Games",related: ["Super Mario"],hint: "O ouriço azul mais rápido do mundo que coleta argolas.",},
  {word: "Minecraft",category: "Video Games",related: ["Roblox"],hint: "Jogo de construção onde tudo é feito de blocos cúbicos.",},
  {word: "Roblox",category: "Video Games",related: ["Minecraft"],hint: "Plataforma onde os usuários criam seus próprios mundos e minijogos.",},
  {word: "Free Fire",category: "Video Games",related: ["Fortnite"],hint: "O 'Battle Royale' mais popular nos celulares do Brasil.",},
  {word: "Fortnite",category: "Video Games",related: ["Free Fire"],hint: "Conhecido pelas construções rápidas e danças famosas.",},
  {word: "League of Legends",category: "Video Games",related: ["Dota 2"],hint: "Famoso MOBA da Riot Games com competições mundiais gigantes.",},
  {word: "Dota 2",category: "Video Games",related: ["League of Legends"],hint: "Jogo estratégico complexo que deu origem ao gênero MOBA.",},
  {word: "FIFA",category: "Video Games",related: ["PES"],hint: "A série de futebol virtual mais vendida do planeta.",},
  {word: "PES",category: "Video Games",related: ["FIFA"],hint: "Grande rival do FIFA, agora conhecido como eFootball.",},
  {word: "GTA",category: "Video Games",related: ["Red Dead Redemption"],hint: "Série polêmica e aclamada sobre o mundo do crime urbano.",},
  {word: "Red Dead Redemption",category: "Video Games",related: ["GTA"],hint: "Ambientado no Velho Oeste, com foco em cowboys e cavalos.",},
  // === FILMES E SÉRIES ===
  {word: "Vingadores",category: "Filmes e Séries",related: ["Liga da Justiça"],hint: "O maior grupo de heróis da Marvel nos cinemas.",},
  {word: "Liga da Justiça",category: "Filmes e Séries",related: ["Vingadores"],hint: "O grupo que reúne os ícones da DC como Superman e Mulher-Maravilha.",},
  {word: "La Casa de Papel",category: "Filmes e Séries",related: ["Round 6"],hint: "Série espanhola sobre um grupo de assaltantes com máscaras de Dalí.",},
  {word: "Round 6",category: "Filmes e Séries",related: ["La Casa de Papel"],hint: "Série coreana sobre jogos infantis mortais por dinheiro.",},
  {word: "Titanic",category: "Filmes e Séries",related: ["Avatar"],hint: "Um épico sobre o naufrágio mais famoso da história.",},
  {word: "Avatar",category: "Filmes e Séries",related: ["Titanic"],hint: "Filme sobre seres azuis em um planeta chamado Pandora.",},
  {word: "Star Wars",category: "Filmes e Séries",related: ["Star Trek"],hint: "A saga espacial definitiva sobre a luta entre Jedi e Sith.",},
  {word: "Star Trek",category: "Filmes e Séries",related: ["Star Wars"],hint: "Exploração científica do espaço a bordo da Enterprise.",},
    // --- DRAMA NACIONAL ---
  { word: "Cidade de Deus", category: "Filmes e Séries", related: ["Cidade dos Homens"], hint: "Um retrato visceral do crime organizado em comunidades cariocas." },
  { word: "Cidade dos Homens", category: "Filmes e Séries", related: ["Cidade de Deus"], hint: "Foca na amizade de dois jovens crescendo em meio aos desafios da favela." },
  { word: "Tropa de Elite", category: "Filmes e Séries", related: ["Carandiru"], hint: "Aborda o sistema de segurança e o combate direto ao tráfico sob um olhar rígido." },
  { word: "Carandiru", category: "Filmes e Séries", related: ["Tropa de Elite"], hint: "Baseado em fatos reais, narra o cotidiano e a tragédia dentro do sistema prisional." },
  { word: "O Auto da Compadecida", category: "Filmes e Séries", related: ["Central do Brasil"], hint: "Um clássico que mistura fé, esperteza e a cultura do sertão nordestino." },
  { word: "Central do Brasil", category: "Filmes e Séries", related: ["O Auto da Compadecida"], hint: "Uma jornada emocionante de busca e redenção cruzando o interior do país." },

  // --- COMÉDIAS NOSTÁLGICAS (SBT / RECORD / GLOBO) ---
  { word: "Todo Mundo Odeia o Chris", category: "Filmes e Séries", related: ["Eu, a Patroa e as Crianças"], hint: "Série baseada na adolescência real de um comediante famoso." },
  { word: "Eu, a Patroa e as Crianças", category: "Filmes e Séries", related: ["Todo Mundo Odeia o Chris"], hint: "Sitcom familiar focada na dinâmica engraçada entre pais e três filhos." },
  { word: "Um Maluco no Pedaço", category: "Filmes e Séries", related: ["Três é Demais"], hint: "Um jovem de origem humilde vai morar com parentes ricos em uma mansão." },
  { word: "Três é Demais", category: "Filmes e Séries", related: ["Um Maluco no Pedaço"], hint: "Mostra a rotina de uma casa cheia de crianças criada por três figuras paternas." },
  { word: "As Branquelas", category: "Filmes e Séries", related: ["Vovó...Zona"], hint: "Dois agentes precisam usar disfarces femininos para resolver uma missão." },
  { word: "Vovó...Zona", category: "Filmes e Séries", related: ["As Branquelas"], hint: "Um policial se disfarça de uma senhora idosa e gordinha para uma investigação." },

  // --- SÉRIES TEEN (NICKELODEON / DISNEY) ---
  { word: "iCarly", category: "Filmes e Séries", related: ["Victorious"], hint: "Um grupo de amigos cria um programa de variedades de sucesso na internet." },
  { word: "Victorious", category: "Filmes e Séries", related: ["iCarly"], hint: "A rotina de jovens talentosos em uma escola de artes performáticas." },
  { word: "Kenan & Kel", category: "Filmes e Séries", related: ["Drake & Josh"], hint: "Uma dupla de amigos se mete em confusões, um é esperto e o outro adora refrigerante." },
  { word: "Drake & Josh", category: "Filmes e Séries", related: ["Kenan & Kel"], hint: "Dois irmãos postiços com personalidades opostas precisam aprender a conviver." },

  // --- SÉRIES DE SUCESSO MUNDIAL NO BRASIL ---
  
  { word: "Grey's Anatomy", category: "Filmes e Séries", related: ["Dr. House"], hint: "Dramatiza a vida pessoal e profissional de internos e cirurgiões em um hospital." },
  { word: "Dr. House", category: "Filmes e Séries", related: ["Grey's Anatomy"], hint: "Um médico genial e ranzinza resolve mistérios médicos quase impossíveis." },
  { word: "Friends", category: "Filmes e Séries", related: ["How I Met Your Mother"], hint: "Seis amigos vivendo em Nova York, frequentando sempre o mesmo café." },
  { word: "How I Met Your Mother", category: "Filmes e Séries", related: ["Friends"], hint: "A jornada de um pai contando aos filhos como conheceu a mãe deles através de flashbacks." },

  // --- FENÔMENOS DE BILHETERIA ---
  { word: "Titanic", category: "Filmes e Séries", related: ["Avatar"], hint: "Um épico de romance e tragédia dirigido por James Cameron no oceano." },
  { word: "Avatar", category: "Filmes e Séries", related: ["Titanic"], hint: "Exploração de um mundo alienígena exuberante e conflito com colonizadores humanos." },
  { word: "Harry Potter", category: "Filmes e Séries", related: ["O Senhor dos Anéis"], hint: "Um jovem órfão descobre um mundo de magia escondido da sociedade comum." },
  { word: "O Senhor dos Anéis", category: "Filmes e Séries", related: ["Harry Potter"], hint: "Uma jornada épica para destruir um artefato poderoso e salvar um mundo de fantasia." },

  // --- COMÉDIA NACIONAL MODERNA ---
  { word: "Minha Mãe é uma Peça", category: "Filmes e Séries", related: ["Até que a Sorte nos Separe"], hint: "Inspirado em uma peça teatral, foca no cotidiano hilário de uma dona de casa protetora." },
  { word: "Até que a Sorte nos Separe", category: "Filmes e Séries", related: ["Minha Mãe é uma Peça"], hint: "Um pai de família ganha na loteria e gasta tudo escondido da esposa." },

  // --- HERÓIS E AÇÃO ---
  { word: "Missão Impossível", category: "Filmes e Séries", related: ["007"], hint: "Famoso por cenas de ação reais e arriscadas protagonizadas por Tom Cruise." },
  { word: "007", category: "Filmes e Séries", related: ["Missão Impossível"], hint: "Agente britânico clássico conhecido por seu estilo refinado e carros equipados." },

  // --- ANIMAÇÕES ---
  { word: "Shrek", category: "Filmes e Séries", related: ["Toy Story"], hint: "Uma paródia de contos de fadas estrelada por um ogro verde e um burro falante." },
  { word: "Toy Story", category: "Filmes e Séries", related: ["Shrek"], hint: "Mostra o mundo secreto dos brinquedos quando os humanos não estão por perto." },
  { word: "Frozen", category: "Filmes e Séries", related: ["Moana"], hint: "Animação da Disney sobre o amor fraternal entre duas irmãs em um reino gelado." },
  { word: "Moana", category: "Filmes e Séries", related: ["Frozen"], hint: "Uma jovem navegadora atravessa o oceano para salvar seu povo e sua ilha." },

  // --- REALTIES E NOVELAS (MUITO FAMOSOS) ---
  { word: "Big Brother Brasil", category: "Filmes e Séries", related: ["A Fazenda"], hint: "Reality show de confinamento onde o público vota para eliminar os participantes." },
  { word: "A Fazenda", category: "Filmes e Séries", related: ["Big Brother Brasil"], hint: "Famosos ficam confinados em um ambiente rural cuidando de animais." },
  { word: "Avenida Brasil", category: "Filmes e Séries", related: ["O Clone"], hint: "Novela que parou o país com a vingança de Nina contra Carminha." },
  { word: "O Clone", category: "Filmes e Séries", related: ["Avenida Brasil"], hint: "Trama que mistura genética, religião mulçumana e dependência química." },


  // === MARCAS FAMOSAS ===
  {word: "Apple",category: "Marcas",related: ["Samsung"],hint: "Empresa da maçã, famosa pelos iPhones e MacBooks.",},
  {word: "Samsung",category: "Marcas",related: ["Apple"],hint: "Gigante coreana que domina o mercado de telas e Androids.",},
  {word: "Nike",category: "Marcas",related: ["Adidas"],hint: "Marca esportiva do 'Swoosh' e do slogan 'Just Do It'.",},
  {word: "Adidas",category: "Marcas",related: ["Nike"],hint: "Marca alemã famosa pelas três listras paralelas.",},
  {word: "Netflix",category: "Marcas",related: ["Disney+"],hint: "A plataforma que popularizou o streaming de filmes e séries.",},
  {word: "Disney+",category: "Marcas",related: ["Netflix"],hint: "Casa do Mickey, Star Wars e Marvel no mundo digital.",},
  {word: "McDonald's",category: "Marcas",related: ["Burger King"],hint: "A maior rede de fast-food do mundo, famosa pelos arcos dourados.",},
  {word: "Burger King",category: "Marcas",related: ["McDonald's"],hint: "Conhecido pelo Whopper e pela rivalidade ácida com o palhaço.",},
  // === LUGARES E PAÍSES ===
  {word: "Brasil",category: "Países e Cidades",related: ["Portugal"],hint: "O maior país da América Latina, famoso pelo Carnaval.",},
  {word: "Portugal",category: "Países e Cidades",related: ["Brasil"],hint: "País europeu onde se originou a nossa língua oficial.",},
  {word: "Estados Unidos",category: "Países e Cidades",related: ["Canadá"],hint: "A maior potência econômica do ocidente.",},
  {word: "Canadá",category: "Países e Cidades",related: ["Estados Unidos"],hint: "País da América do Norte conhecido pelo frio e a folha de bordo.",},
  {word: "Rio de Janeiro",category: "Países e Cidades",related: ["São Paulo"],hint: "A Cidade Maravilhosa, casa do Cristo Redentor.",},
  {word: "São Paulo",category: "Países e Cidades",related: ["Rio de Janeiro"],hint: "A maior metrópole do Brasil, conhecida como a cidade que não dorme.",},
  {word: "Paris",category: "Países e Cidades",related: ["Roma"],hint: "A cidade luz, famosa pela Torre Eiffel e o amor.",},
  {word: "Roma",category: "Países e Cidades",related: ["Paris"],hint: "A cidade eterna, berço do antigo império e do Coliseu.",},
  // === ANIMAIS (Concretos) ===
  {word: "Elefante",category: "Animais",related: ["Mamute"],hint: "O maior mamífero terrestre atual, possui uma tromba versátil.",},
  {word: "Mamute",category: "Animais",related: ["Elefante"],hint: "Gigante pré-histórico peludo com grandes presas curvadas.",},
  {word: "Leão",category: "Animais",related: ["Tigre"],hint: "O rei da selva, conhecido pela sua juba imponente.",},
  {word: "Tigre",category: "Animais",related: ["Leão"],hint: "O maior dos felinos, reconhecido por suas listras negras.",},
  {word: "Girafa",category: "Animais",related: ["Zebra"],hint: "Animal de pescoço longuíssimo para alcançar copas de árvores.",},
  {word: "Zebra",category: "Animais",related: ["Girafa"],hint: "Mamífero africano com um padrão único de listras brancas e pretas.",},
  {word: "Tubarão",category: "Animais",related: ["Baleia"],hint: "Predador dos oceanos com várias fileiras de dentes afiados.",},
  {word: "Baleia",category: "Animais",related: ["Tubarão"],hint: "O maior ser vivo do planeta, respira por um orifício no topo.",},
  // --- ANIMAIS (Aquáticos e Anfíbios) ---
  {word: "Jacaré",category: "Animais",related: ["Crocodilo"],hint: "Muito comum no Pantanal, possui o focinho mais largo e arredondado.",},
  {word: "Crocodilo",category: "Animais",related: ["Jacaré"],hint: "Pode viver em água salgada e seu focinho é afilado em forma de V.",},
  {word: "Sapo",category: "Animais",related: ["Rã"],hint: "Possui a pele rugosa, seca e prefere se deslocar em terra firme.",},
  {word: "Rã",category: "Animais",related: ["Sapo"],hint: "Tem a pele lisa, úmida e é uma excelente saltadora e nadadora.",},
  {word: "Polvo",category: "Animais",related: ["Lula"],hint: "Possui oito tentáculos com ventosas e é mestre em camuflagem e fuga.",},
  {word: "Lula",category: "Animais",related: ["Polvo"],hint: "Tem um corpo alongado em forma de torpedo e possui duas nadadeiras na cabeça.",},
  {word: "Golfinho",category: "Animais",related: ["Boto"],hint: "Mamífero marinho extremamente inteligente e sociável com humanos.",},
  {word: "Boto",category: "Animais",related: ["Golfinho"],hint: "Lenda viva das águas doces da Amazônia, dizem que se transforma em homem.",},
  {word: "Tartaruga",category: "Animais",related: ["Jabuti"],hint: "Passa a maior parte da vida na água e possui nadadeiras em vez de patas.",},
  {word: "Jabuti",category: "Animais",related: ["Tartaruga"],hint: "Animal exclusivamente terrestre com patas pesadas que lembram as de um elefante.",},
  // --- ANIMAIS (Aves) ---
  {word: "Avestruz",category: "Animais",related: ["Ema"],hint: "A maior ave do mundo, nativa da África, corre em velocidades incríveis.",},
  {word: "Ema",category: "Animais",related: ["Avestruz"],hint: "A maior ave das Américas, muito comum nos campos brasileiros.",},
  {word: "Águia",category: "Animais",related: ["Gavião"],hint: "Símbolo de soberania, possui uma visão aguçada para caçar grandes presas.",},
  {word: "Gavião",category: "Animais",related: ["Águia"],hint: "Rapina de médio porte, muito ágil em voos rasantes entre árvores.",},
  {word: "Arara",category: "Animais",related: ["Papagaio"],hint: "Ave de cauda longa e cores vibrantes, símbolo das florestas tropicais.",},
  {word: "Papagaio",category: "Animais",related: ["Arara"],hint: "Famoso por sua habilidade de imitar sons e a voz humana.",},
  {word: "Urubu",category: "Animais",related: ["Condor"],hint: "Ave carniceira essencial para a limpeza do ecossistema urbano e rural.",},
  {word: "Condor",category: "Animais",related: ["Urubu"],hint: "Uma das maiores aves voadoras do mundo, habita as altas cordilheiras.",},
  {word: "Pinguim",category: "Animais",related: ["Pelicano"],hint: "Ave que não voa, mas é uma exímia nadadora em águas geladas.",},
  {word: "Pelicano",category: "Animais",related: ["Pinguim"],hint: "Conhecido pela grande bolsa sob o bico usada para pescar.",},
  // --- ANIMAIS (Mamíferos) ---
  {word: "Camelo",category: "Animais",related: ["Dromedário"],hint: "O 'navio do deserto' que possui duas corcovas de gordura.",},
  {word: "Dromedário",category: "Animais",related: ["Camelo"],hint: "Habitante das dunas que possui apenas uma corcova nas costas.",},
  {word: "Gorila",category: "Animais",related: ["Chimpanzé"],hint: "O maior e mais forte dos primatas, vive em grupos familiares nas florestas.",},
  {word: "Chimpanzé",category: "Animais",related: ["Gorila"],hint: "Nosso parente genético mais próximo, famoso pelo uso de ferramentas.",},
  {word: "Leopardo",category: "Animais",related: ["Guepardo"],hint: "Excelente escalador que costuma levar suas presas para o topo das árvores.",},
  {word: "Guepardo",category: "Animais",related: ["Leopardo"],hint: "O animal terrestre mais rápido do mundo, possui linhas negras no rosto.",},
  {word: "Lhama",category: "Animais",related: ["Alpaca"],hint: "Animal andino de carga, conhecido por cuspir quando se sente ameaçado.",},
  {word: "Alpaca",category: "Animais",related: ["Lhama"],hint: "Criada principalmente por sua lã macia e valiosa nas montanhas frias.",},
  {word: "Rinoceronte",category: "Animais",related: ["Hipopótamo"],hint: "Blindado natural com um ou dois chifres feitos de queratina no focinho.",},
  {word: "Hipopótamo",category: "Animais",related: ["Rinoceronte"],hint: "Passa o dia na água para proteger a pele e é extremamente territorialista.",},
  // --- ANIMAIS (Insetos e Pequenos) ---
  {word: "Abelha",category: "Animais",related: ["Vespa"],hint: "Produz alimento doce e é fundamental para a polinização das flores.",},
  {word: "Vespa",category: "Animais",related: ["Abelha"],hint: "Predadora agressiva de cintura fina, muitas vezes constrói ninhos de 'papel'.",},
  {word: "Aranha",category: "Animais",related: ["Escorpião"],hint: "Possui oito patas e muitas vezes fia teias para capturar o almoço.",},
  {word: "Escorpião",category: "Animais",related: ["Aranha"],hint: "Animal articulado que carrega uma arma perigosa na ponta da cauda.",},
  {word: "Grilo",category: "Animais",related: ["Gafanhoto"],hint: "Conhecido pelo som rítmico que faz à noite esfregando as asas.",},
  {word: "Gafanhoto",category: "Animais",related: ["Grilo"],hint: "Grande saltador que pode formar nuvens destruidoras em plantações.",},
  {word: "Carrapato",category: "Animais",related: ["Pulga"],hint: "Parasita que se fixa na pele para sugar sangue, comum em matagais.",},
  {word: "Pulga",category: "Animais",related: ["Carrapato"],hint: "Pequeno saltador que infesta pelos de animais domésticos.",},
  // --- ANIMAIS (Brasileiros Específicos) ---
  {word: "Capivara",category: "Animais",related: ["Paca"],hint: "O maior roedor do mundo, adora viver perto de rios e lagos.",},
  {word: "Paca",category: "Animais",related: ["Capivara"],hint: "Roedor noturno de carne apreciada, com manchas brancas laterais.",},
  {word: "Tamanduá-bandeira",category: "Animais",related: ["Tatu"],hint: "Possui uma cauda imensa e peluda e uma língua longa para comer cupins.",},
  {word: "Tatu",category: "Animais",related: ["Tamanduá-bandeira"],hint: "Protegido por uma carapaça óssea, cava buracos para se esconder.",},
  {word: "Onça-pintada",category: "Animais",related: ["Jaguatirica"],hint: "O maior felino das Américas, possui a mordida mais forte entre os gatos.",},
  {word: "Jaguatirica",category: "Animais",related: ["Onça-pintada"],hint: "Felino de porte médio com pelagem lindamente manchada, muito ágil.",},
  {word: "Mico-leão-dourado",category: "Animais",related: ["Sagui"],hint: "Primata de cor vibrante, símbolo da conservação da Mata Atlântica.",},
  {word: "Sagui",category: "Animais",related: ["Mico-leão-dourado"],hint: "Pequeno macaco muito comum em áreas urbanas, possui tufos de pelos nas orelhas.",},
  // --- ANIMAIS (Cães e Parentes) ---
  {word: "Lobo",category: "Animais",related: ["Urso"],hint: "Ancestral selvagem que vive e caça em alcateias organizadas.",},
  {word: "Urso",category: "Animais",related: ["Lobo"],hint: "Mamífero carnívoro de grande porte.",},
  {word: "Cachorro",category: "Animais",related: ["Gato"],hint: "O primeiro animal domesticado, fiel companheiro de diversas raças.",},
  {word: "Gato",category: "Animais",related: ["Cachorro"],hint: 'Bixo de estimação que possui "7 vidas".',},
  {word: "Raposa",category: "Animais",related: ["Coiote"],hint: "Conhecida pela astúcia e por sua cauda felpuda, habita diversos climas.",},
  {word: "Coiote",category: "Animais",related: ["Raposa"],hint: "Canídeo resistente dos desertos e pradarias, famoso por seu uivo agudo.",},
  {word: "Hiena",category: "Animais",related: ["Abutre"],hint: "Predador africano com mandíbulas poderosas e uma 'risada' característica.",},
  {word: "Abutre",category: "Animais",related: ["Hiena"],hint: "Ave que observa do alto à espera de restos deixados por outros.",},
  // === TECNOLOGIA E APPLICATIVOS ===
  {word: "WhatsApp",category: "Tecnologia",related: ["Telegram"],hint: "O aplicativo de mensagens verde mais usado no Brasil.",},
  {word: "Telegram",category: "Tecnologia",related: ["WhatsApp"],hint: "App de mensagens azul com foco em privacidade e grandes grupos.",},
  {word: "Instagram",category: "Tecnologia",related: ["TikTok"],hint: "Rede social de fotos e vídeos comprada pelo Facebook.",},
  {word: "TikTok",category: "Tecnologia",related: ["Instagram"],hint: "Plataforma de vídeos curtos e virais que conquistou os jovens.",},
  {word: "YouTube",category: "Tecnologia",related: ["Twitch"],hint: "O maior site de compartilhamento de vídeos do mundo.",},
  {word: "Twitch",category: "Tecnologia",related: ["YouTube"],hint: "Plataforma líder em transmissões ao vivo de jogos.",},
  {word: "Uber",category: "Tecnologia",related: ["99 Pop"],hint: "O app que revolucionou o transporte urbano particular.",},
  {word: "99 Pop",category: "Tecnologia",related: ["Uber"],hint: "Principal concorrente do Uber no mercado brasileiro.",},
  // ALEATÓRIOS 1
  {word: "Oásis",category: "Lugares",related: ["Miragem"],hint: "Um refúgio real com recursos vitais em meio ao nada.",},
  {word: "Miragem",category: "Natureza",related: ["Oásis"],hint: "Uma ilusão ótica causada pelo calor que engana os olhos.",},
  {word: "Visão",category: "Emoções",related: ["Ótica"],hint: "A capacidade sensorial de interpretar a luz e as formas.",},
  {word: "Ótica",category: "Ciência",related: ["Visão"],hint: "O estudo físico da luz ou o estabelecimento que vende lentes.",},
  {word: "Horizontal",category: "Substantivos variados",related: ["Vertical"],hint: "Uma direção paralela à linha do horizonte, em repouso.",},
  {word: "Vertical",category: "Substantivos variados",related: ["Horizontal"],hint: "Uma direção em ângulo reto com o chão, que sobe ou desce.",},
  {word: "Ilusão",category: "Emoções",related: ["Alucinação"],hint: "Uma interpretação errada de algo que realmente existe.",},
  {word: "Alucinação",category: "Emoções",related: ["Ilusão"],hint: "Perceber algo que não existe fora da mente de quem vê.",},
  {word: "Abismo",category: "Natureza",related: ["Precipício"],hint: "Uma profundeza imensa onde o fundo raramente é visível.",},
  {word: "Precipício",category: "Natureza",related: ["Abismo"],hint: "Uma queda brusca e perigosa em um terreno elevado.",},
  {word: "Destino",category: "Emoções",related: ["Acaso"],hint: "A ideia de que os eventos são inevitáveis e pré-escritos.",},
  {word: "Acaso",category: "Emoções",related: ["Destino"],hint: "A ocorrência de eventos sem um plano ou causa aparente.",},
  {word: "Caos",category: "Emoções",related: ["Desordem"],hint: "Um estado de confusão total que precede a criação ou o fim.",},
  {word: "Desordem",category: "Emoções",related: ["Caos"],hint: "A falta de organização em um sistema que deveria ser arrumado.",},
  {word: "Essência",category: "Substantivos variados",related: ["Aparência"],hint: "O que algo realmente é em sua natureza mais profunda.",},
  {word: "Aparência",category: "Substantivos variados",related: ["Essência"],hint: "A forma como algo se apresenta superficialmente aos outros.",},
  {word: "Utopia",category: "Emoções",related: ["Sonho"],hint: "A ideia de uma sociedade perfeita que é quase impossível de alcançar.",},
  {word: "Sonho",category: "Emoções",related: ["Utopia"],hint: "Imagens e pensamentos que ocorrem durante o repouso da mente.",},
  {word: "Vácuo",category: "Natureza",related: ["Vazio"],hint: "A ausência total de matéria em um determinado espaço.",},
  {word: "Vazio",category: "Emoções",related: ["Vácuo"],hint: "Um espaço que não contém nada ou um sentimento de falta.",},
  {word: "Inércia",category: "Ciência",related: ["Estagnação"],hint: "A resistência de um corpo a mudar seu estado de movimento.",},
  {word: "Estagnação",category: "Emoções",related: ["Inércia"],hint: "Um estado onde não há progresso, crescimento ou movimento.",},
  {word: "Labirinto",category: "Lugares",related: ["Enigma"],hint: "Um lugar com caminhos complexos feitos para confundir quem entra.",},
  {word: "Enigma",category: "Emoções",related: ["Labirinto"],hint: "Um problema ou situação que desafia a compreensão lógica.",},
  {word: "Eco",category: "Natureza",related: ["Reflexo"],hint: "A repetição de um som causada pelo rebatimento em uma superfície.",},
  {word: "Reflexo",category: "Natureza",related: ["Eco"],hint: "A imagem ou luz que volta após atingir uma superfície polida.",},
  // --- FAMOSOS MUNDIAIS (Conhecidos no Brasil) ---
  {word: "Donald Trump",category: "Famosos",related: ["Elon Musk"],hint: "Magnata americano que se tornou o 45º presidente dos EUA.",},
  {word: "Elon Musk",category: "Famosos",related: ["Donald Trump"],hint: "Dono da Tesla e do X, com planos de colonizar Marte.",},
  {word: "Lionel Messi",category: "Esporte",related: ["Cristiano Ronaldo"],hint: "Craque argentino canhoto, multicampeão pelo Barcelona.",},
  {word: "Cristiano Ronaldo",category: "Esporte",related: ["Lionel Messi"],hint: "Atleta português conhecido por sua disciplina física extrema e gols.",},
  {word: "Justin Bieber",category: "Famosos",related: ["Shawn Mendes"],hint: "Cantor canadense que surgiu como um fenômeno adolescente no YouTube.",},
  {word: "Shawn Mendes",category: "Famosos",related: ["Justin Bieber"],hint: "Cantor canadense da nova geração, conhecido por tocar violão e hits pop.",},
  {word: "Adele",category: "Famosos",related: ["Beyoncé"],hint: "Voz britânica potente conhecida por baladas sentimentais e recordes de vendas.",},
  {word: "Beyoncé",category: "Famosos",related: ["Adele"],hint: "A 'Queen B', um dos maiores nomes da performance e cultura pop atual.",},
  {word: "Bill Gates",category: "Famosos",related: ["Mark Zuckerberg"],hint: "Fundador da Microsoft e um dos maiores filantropos do mundo.",},
  {word: "Mark Zuckerberg",category: "Famosos",related: ["Bill Gates"],hint: "Criador do Facebook e figura central na era das redes sociais.",},
  {word: "Lady Gaga",category: "Famosos",related: ["Madonna"],hint: "Conhecida por figurinos extravagantes e versatilidade no pop e jazz.",},
  {word: "Madonna",category: "Famosos",related: ["Lady Gaga"],hint: "A eterna Rainha do Pop que revolucionou a música nos anos 80.",},
  {word: "Michael Jackson",category: "Famosos",related: ["Prince"],hint: "O Rei do Pop, criador do 'Moonwalk'.",},
  {word: "Prince",category: "Famosos",related: ["Michael Jackson"],hint: "Gênio multi-instrumentista conhecido pela cor roxa e estilo único.",},
  {word: "Albert Einstein",category: "Famosos",related: ["Isaac Newton"],hint: "Físico famoso pela teoria da relatividade e a fórmula E=mc².",},
  {word: "Isaac Newton",category: "Famosos",related: ["Albert Einstein"],hint: "Cientista que formulou as leis do movimento e da gravitação universal.",},
  {word: "Pablo Picasso",category: "Famosos",related: ["Salvador Dalí"],hint: "Artista espanhol e um dos fundadores do cubismo.",},
  {word: "Salvador Dalí",category: "Famosos",related: ["Pablo Picasso"],hint: "Mestre do surrealismo, famoso por seus relógios derretidos.",},
  {word: "Angelina Jolie",category: "Famosos",related: ["Jennifer Aniston"],hint: "Atriz conhecida por papéis de ação e seu trabalho humanitário.",},
  {word: "Jennifer Aniston",category: "Famosos",related: ["Angelina Jolie"],hint: "Eterna Rachel da série 'Friends' e ícone das comédias românticas.",},
  {word: "Usain Bolt",category: "Esporte",related: ["Michael Phelps"],hint: "O homem mais rápido da história, recordista nos 100 metros rasos.",},
  {word: "Michael Phelps",category: "Esporte",related: ["Usain Bolt"],hint: "O maior medalhista olímpico de todos os tempos, dono das piscinas.",},
  {word: "Ayrton Senna",category: "Esporte",related: ["Michael Schumacher"],hint: "Ídolo brasileiro da F1, tricampeão mundial e rei da chuva.",},
  {word: "Michael Schumacher",category: "Esporte",related: ["Ayrton Senna"],hint: "Piloto alemão recordista de títulos na F1, ícone da Ferrari.",},
  {word: "Leonardo da Vinci",category: "Famosos",related: ["Michelangelo"],hint: "Pintor da Mona Lisa e um inventor visionário à frente de seu tempo.",},
  {word: "Michelangelo",category: "Famosos",related: ["Leonardo da Vinci"],hint: "Escultor de 'Davi' e pintor do teto da Capela Sistina.",},
  // --- SUBSTANTIVOS COLETIVOS E GRAMÁTICA ---
  {word: "Frota",category: "Substantivos variados",related: ["Comboio"],hint: "Designação para um conjunto de veículos, especialmente navios ou aviões.",},
  {word: "Comboio",category: "Substantivos variados",related: ["Frota"],hint: "Grupo de veículos que viajam juntos para proteção ou organização.",},
  {word: "Vara",category: "Substantivos variados",related: ["Fato"],hint: "O termo coletivo usado para um grupo de porcos.",},
  {word: "Fato",category: "Substantivos variados",related: ["Vara"],hint: "Nome dado ao conjunto de cabras.",},
  {word: "Rebanho",category: "Substantivos variados",related: ["Manada"],hint: "Coletivo comum para ovelhas ou gado doméstico.",},
  {word: "Manada",category: "Substantivos variados",related: ["Rebanho"],hint: "Coletivo usado para animais de grande porte, como elefantes ou búfalos.",},
  {word: "Alcateia",category: "Substantivos variados",related: ["Matilha"],hint: "Grupo de lobos que caçam e vivem sob uma hierarquia rígida.",},
  {word: "Matilha",category: "Substantivos variados",related: ["Alcateia"],hint: "Conjunto de cães de caça.",},
  {word: "Resma",category: "Substantivos variados",related: ["Bloco"],hint: "Uma quantidade específica de quinhentas folhas de papel.",},
  {word: "Bloco",category: "Objetos",related: ["Resma"],hint: "Conjunto de folhas de papel unidas por um dos lados.",},
  {word: "Atlas",category: "Substantivos variados",related: ["Dicionário"],hint: "Coleção de mapas geográficos ou ilustrações de um tema.",},
  {word: "Dicionário",category: "Substantivos variados",related: ["Atlas"],hint: "Livro que reúne e explica o significado das palavras de uma língua.",},
  // --- SUBSTANTIVOS DERIVADOS E PRIMITIVOS ---
  {word: "Flor",category: "Natureza",related: ["Floricultura"],hint: "A parte colorida e reprodutiva das plantas angiospermas.",},
  {word: "Floricultura",category: "Lugares",related: ["Flor"],hint: "Local comercial especializado na venda de plantas e arranjos.",},
  {word: "Pedra",category: "Natureza",related: ["Pedregulho"],hint: "Matéria mineral sólida e dura, fragmento de rocha.",},
  {word: "Pedregulho",category: "Natureza",related: ["Pedra"],hint: "Fragmento de rocha desgastado pelo tempo ou pela água.",},
  {word: "Fogo",category: "Natureza",related: ["Incêndio"],hint: "Produção de luz e calor resultante da combustão.",},
  {word: "Incêndio",category: "Natureza",related: ["Fogo"],hint: "Um fogo de grandes proporções que foge ao controle humano.",},
  {word: "Papel",category: "Objetos",related: ["Papelaria"],hint: "Material fino feito de fibras vegetais usado para escrita.",},
  {word: "Papelaria",category: "Lugares",related: ["Papel"],hint: "Loja que vende materiais de escritório e escrita.",},
  // --- MAIS CONCEITOS E OBJETOS ---
  {word: "Sombra",category: "Natureza",related: ["Penumbra"],hint: "Região escura formada pela interrupção da luz por um objeto.",},
  {word: "Penumbra",category: "Natureza",related: ["Sombra"],hint: "Estado de luz suave entre a iluminação total e a escuridão.",},
  {word: "Labirinto",category: "Objetos",related: ["Quebra-cabeça"],hint: "Estrutura complexa de caminhos que desafia a orientação.",},
  {word: "Quebra-cabeça",category: "Jogos",related: ["Labirinto"],hint: "Jogo que consiste em montar peças para formar uma figura completa.",},
  {word: "Bússola",category: "Objetos",related: ["Radar"],hint: "Instrumento antigo que usa o magnetismo para indicar direções.",},
  {word: "Radar",category: "Tecnologia",related: ["Bússola"],hint: "Sistema que utiliza ondas de rádio para detectar objetos e distâncias.",},
  {word: "Telescópio",category: "Tecnologia",related: ["Microscópio"],hint: "Instrumento que permite observar objetos situados a grandes distâncias.",},
  {word: "Microscópio",category: "Tecnologia",related: ["Telescópio"],hint: "Instrumento que amplia imagens de objetos minúsculos.",},
  {word: "Ampulheta",category: "Objetos",related: ["Cronômetro"],hint: "Dispositivo antigo que mede o tempo através do escoamento de areia.",},
  {word: "Cronômetro",category: "Objetos",related: ["Ampulheta"],hint: "Relógio de precisão usado para medir intervalos exatos de tempo.",},
  {word: "Sinfonia",category: "Músicas",related: ["Orquestra"],hint: "Composição musical complexa escrita para ser tocada por muitos músicos.",},
  {word: "Orquestra",category: "Músicas",related: ["Sinfonia"],hint: "Grande conjunto de músicos que tocam diversos instrumentos juntos.",},
  {word: "Lenda",category: "Substantivos variados",related: ["Mito"],hint: "Narrativa transmitida oralmente que mistura fatos reais e ficção.",},
  {word: "Mito",category: "Substantivos variados",related: ["Lenda"],hint: "História simbólica que tenta explicar a origem do mundo ou fenômenos.",},
  {word: "Horizonte",category: "Lugares",related: ["Infinito"],hint: "A linha onde o céu e a terra parecem se encontrar.",},
  {word: "Infinito",category: "Substantivos variados",related: ["Horizonte"],hint: "Aquilo que não tem fim, limite ou término.",},
  {word: "Vento",category: "Natureza",related: ["Brisa"],hint: "O ar em movimento na atmosfera terrestre.",},
  {word: "Brisa",category: "Natureza",related: ["Vento"],hint: "Um vento suave, leve e geralmente refrescante.",},
  {word: "Relâmpago",category: "Natureza",related: ["Trovão"],hint: "A claridade intensa e súbita causada por uma descarga elétrica no céu.",},
  {word: "Trovão",category: "Natureza",related: ["Relâmpago"],hint: "O estrondo sonoro que se segue a uma descarga elétrica atmosférica.",},
  {word: "Deserto",category: "Lugares",related: ["Duna"],hint: "Vasta região árida com pouca chuva e vegetação escassa.",},
  {word: "Duna",category: "Natureza",related: ["Deserto"],hint: "Montanha de areia formada pela ação constante do vento.",},
  // ALEATÓRIOS 2
  // --- PERSONAGENS (Ficção e Animação) ---
  {word: "Darth Vader",category: "Personagens",related: ["Voldemort"],hint: "Um vilão icônico que serve a um mestre sombrio e usa uma máscara.",},
  {word: "Voldemort",category: "Personagens",related: ["Darth Vader"],hint: "Aquele que não deve ser nomeado, um mestre das artes das trevas.",},
  {word: "Shrek",category: "Personagens",related: ["Hulk"],hint: "Um ser grande e verde que prefere a solidão do seu pântano.",},
  {word: "Hulk",category: "Personagens",related: ["Shrek"],hint: "Um cientista que se transforma em um gigante verde por causa da raiva.",},
  {word: "Woody",category: "Personagens",related: ["Buzz Lightyear"],hint: "Um boneco de caubói que é o líder dos brinquedos de um quarto.",},
  {word: "Buzz Lightyear",category: "Personagens",related: ["Woody"],hint: "Um patrulheiro espacial que acredita que pode voar para o infinito e além.",},
  {word: "Pikachu",category: "Personagens",related: ["Charizard"],hint: "Uma criatura amarela pequena que gera eletricidade nas bochechas.",},
  {word: "Charizard",category: "Personagens",related: ["Pikachu"],hint: "Uma criatura voadora que cospe fogo e é a evolução final de um inicial.",},
  {word: "Goku",category: "Personagens",related: ["Naruto"],hint: "Um guerreiro de outro planeta que busca as esferas que realizam desejos.",},
  {word: "Naruto",category: "Personagens",related: ["Goku"],hint: "Um jovem que carrega uma raposa dentro de si e sonha em ser o líder da vila.",},
  {word: "Batman",category: "Personagens",related: ["Homem de Ferro"],hint: "Um bilionário órfão que usa a tecnologia e o medo para combater o crime.",},
  {word: "Homem de Ferro",category: "Personagens",related: ["Batman"],hint: "Um gênio da tecnologia que criou uma armadura para salvar a própria vida.",},
  {word: "Coringa",category: "Personagens",related: ["Charada"],hint: "O maior agente do caos, conhecido por seu sorriso pintado e piadas mortais.",},
  {word: "Charada",category: "Personagens",related: ["Coringa"],hint: "Um criminoso obcecado por testar a inteligência dos outros com quebra-cabeças.",},
  // --- MARCAS GLOBAIS ---
  {word: "Ferrari",category: "Marcas",related: ["Lamborghini"],hint: "Símbolo italiano de velocidade, famosa pelo escudo do cavalo empinado.",},
  {word: "Lamborghini",category: "Marcas",related: ["Ferrari"],hint: "Marca de superesportivos italiana que utiliza um touro como emblema.",},
  {word: "Rolex",category: "Marcas",related: ["Casio"],hint: "A marca de relógios que é o símbolo máximo de status e luxo.",},
  {word: "Casio",category: "Marcas",related: ["Rolex"],hint: "Famosa por relógios digitais resistentes e calculadoras eletrônicas.",},
  {word: "Google",category: "Marcas",related: ["Microsoft"],hint: "A porta de entrada para quase todo o conhecimento disponível na internet.",},
  {word: "Microsoft",category: "Marcas",related: ["Google"],hint: "Gigante da tecnologia que domina o mercado de sistemas operacionais para PC.",},
  {word: "Amazon",category: "Marcas",related: ["Mercado Livre"],hint: "A maior loja de tudo do mundo, batizada com o nome de um rio brasileiro.",},
  {word: "Mercado Livre",category: "Marcas",related: ["Amazon"],hint: "O gigante do e-commerce na América Latina, famoso pela entrega rápida.",},
  {word: "Coca-Cola",category: "Marcas",related: ["Pepsi"],hint: "A bebida gaseificada mais vendida do mundo, de cor escura.",},
  {word: "Pepsi",category: "Marcas",related: ["Coca-Cola"],hint: "A principal rival da líder, famosa pelo logo circular azul e vermelho.",},
  // --- FAST FOOD ---
  {word: "McDonald's",category: "Marcas",related: ["Burger King"],hint: "Famosa pelos arcos dourados e pelo sanduíche Big Mac.",},
  {word: "Burger King",category: "Marcas",related: ["McDonald's"],hint: "Conhecida pela carne grelhada no fogo e pelo sanduíche Whopper.",},
  // --- VAREJO BRASILEIRO ---
  {word: "Magalu",category: "Marcas",related: ["Casas Bahia"],hint: "Empresa brasileira que possui uma assistente virtual muito famosa.",},
  {word: "Casas Bahia",category: "Marcas",related: ["Magalu"],hint: "Ícone do varejo popular, conhecida pelo bordão 'Dedicação total a você'.",},
  // --- ESPORTES ---
  {word: "Nike",category: "Marcas",related: ["Adidas"],hint: "Marca americana do símbolo 'swoosh' e do slogan 'Just Do It'.",},
  {word: "Adidas",category: "Marcas",related: ["Nike"],hint: "Marca alemã famosa mundialmente pelas três listras paralelas.",},
  // --- BANCOS ---
  {word: "Nubank",category: "Marcas",related: ["Itaú"],hint: "O banco digital roxo que revolucionou o setor financeiro no Brasil.",},
  {word: "Itaú",category: "Marcas",related: ["Nubank"],hint: "Um dos maiores bancos tradicionais do país, famoso pelo logo laranja.",},
  // --- COSMÉTICOS BRASILEIROS ---
  {word: "Natura",category: "Marcas",related: ["O Boticário"],hint: "Marca brasileira com forte foco em sustentabilidade e produtos da Amazônia.",},
  {word: "O Boticário",category: "Marcas",related: ["Natura"],hint: "Gigante brasileira de perfumaria, muito comum em shoppings e presenteáveis.",},
  // --- ENTREGA E MOBILIDADE ---
  {word: "iFood",category: "Marcas",related: ["Rappi"],hint: "O aplicativo líder absoluto em delivery de comida no Brasil.",},
  {word: "Rappi",category: "Marcas",related: ["iFood"],hint: "App de entrega que se posiciona como um 'super aplicativo' de tudo.",},
  // --- HIGIENE ---
  {word: "Colgate",category: "Marcas",related: ["Oral-B"],hint: "A marca de creme dental mais lembrada e utilizada pelos brasileiros.",},
  {word: "Oral-B",category: "Marcas",related: ["Colgate"],hint: "Famosa mundialmente pelas suas escovas de dentes e fios dentais.",},
  // --- LIMPEZA ---
  {word: "Omo",category: "Marcas",related: ["Ariel"],hint: "A marca líder de sabão em pó, famosa pelo slogan 'Lava mais branco'.",},
  {word: "Ariel",category: "Marcas",related: ["Omo"],hint: "Principal concorrente do setor de lavanderia, conhecida pelas versões líquidas e pods.",},
  // --- E-COMMERCE ASIÁTICO ---
  {word: "Shopee",category: "Marcas",related: ["AliExpress"],hint: "Plataforma famosa pelos cupons de frete grátis e comerciais que grudam na cabeça.",},
  {word: "AliExpress",category: "Marcas",related: ["Shopee"],hint: "A pioneira em trazer produtos da China diretamente para o consumidor brasileiro.",},
  // --- CALÇADOS ---
  {word: "Havaianas",category: "Marcas",related: ["Ipanema"],hint: "O chinelo de borracha brasileiro que se tornou um ícone de exportação.",},
  {word: "Ipanema",category: "Marcas",related: ["Havaianas"],hint: "Marca de sandálias concorrente direta, com foco em design e moda praia.",},
  // --- CHOCOLATES ---
  {word: "Nestlé",category: "Marcas",related: ["Garoto"],hint: "Multinacional suíça dona de marcas como KitKat e Leite Moça.",},
  {word: "Garoto",category: "Marcas",related: ["Nestlé"],hint: "Tradicional marca brasileira sediada no Espírito Santo, famosa pela caixa amarela.",},
  // --- TECNOLOGIA/SMARTPHONES ---
  {word: "Apple",category: "Marcas",related: ["Samsung"],hint: "Empresa americana que criou o iPhone e preza pelo ecossistema fechado.",},
  {word: "Samsung",category: "Marcas",related: ["Apple"],hint: "Gigante coreana que oferece uma enorme variedade de telas e aparelhos Android.",},
  // --- STREAMING DE VÍDEO ---
  {word: "Netflix",category: "Marcas",related: ["Disney+"],hint: "A plataforma que popularizou o hábito de 'maratonar' séries no Brasil.",},
  {word: "Disney+",category: "Marcas",related: ["Netflix"],hint: "Serviço que reúne todo o universo Marvel, Star Wars e animações clássicas.",},
  // --- CERVEJAS ---
  {word: "Skol",category: "Marcas",related: ["Brahma"],hint: "Famosa pelo slogan 'A cerveja que desce redondo'.",},
  {word: "Brahma",category: "Marcas",related: ["Skol"],hint: "Conhecida pelo logo vermelho e pelo forte patrocínio ao futebol e festas sertanejas.",},
  // --- MONTADORAS ---
  {word: "Fiat",category: "Marcas",related: ["Volkswagen"],hint: "Marca italiana que produziu ícones populares como o Uno e o Palio.",},
  {word: "Volkswagen",category: "Marcas",related: ["Fiat"],hint: "Marca alemã responsável pelo Fusca e pelo Gol, clássicos das ruas brasileiras.",},
  // --- REDES SOCIAIS ---
  {word: "Instagram",category: "Marcas",related: ["TikTok"],hint: "Rede focada visualmente em fotos e 'Stories', parte do grupo Meta.",},
  {word: "TikTok",category: "Marcas",related: ["Instagram"],hint: "Plataforma de vídeos curtos verticais que viralizou com danças e desafios.",},
  // --- PAGAMENTOS ---
  {word: "Visa",category: "Marcas",related: ["Mastercard"],hint: "Uma das maiores bandeiras de cartões de crédito aceitas no mundo todo.",},
  {word: "Mastercard",category: "Marcas",related: ["Visa"],hint: "Famosa pelo slogan 'Não tem preço' e pelo logo de dois círculos sobrepostos.",},
  // --- POSTOS DE COMBUSTÍVEL ---
  {word: "Ipiranga",category: "Marcas",related: ["Petrobras"],hint: "Famosa pelo bordão comercial 'Pergunta lá no...'.",},
  {word: "Petrobras",category: "Marcas",related: ["Ipiranga"],hint: "A estatal brasileira de energia, com postos espalhados por todo o país.",},
  // --- BRINQUEDOS ---
  {word: "Lego",category: "Marcas",related: ["Playmobil"],hint: "Marca dinamarquesa famosa pelos blocos de montar de plástico.",},
  {word: "Playmobil",category: "Marcas",related: ["Lego"],hint: "Bonecos articulados com mãos em forma de U, clássicos dos anos 80 e 90.",},
  // --- SUBSTANTIVOS ABSTRATOS (Ética e Sentimentos) ---
  {word: "Justiça",category: "Emoções",related: ["Vingança"],hint: "O princípio moral de dar a cada um o que lhe é de direito.",},
  {word: "Vingança",category: "Emoções",related: ["Justiça"],hint: "O ato de retribuir um dano recebido com outro dano, movido por rancor.",},
  {word: "Orgulho",category: "Emoções",related: ["Vaidade"],hint: "Sentimento de satisfação e respeito pelo próprio valor ou conquistas.",},
  {word: "Vaidade",category: "Emoções",related: ["Orgulho"],hint: "Preocupação excessiva com a aparência e com a opinião alheia sobre si.",},
  {word: "Poder",category: "Substantivos variados",related: ["Autoridade"],hint: "A capacidade ou possibilidade de impor a vontade sobre os outros.",},
  {word: "Autoridade",category: "Substantivos variados",related: ["Poder"],hint: "O direito legítimo de comandar ou ser obedecido em uma estrutura.",},
  {word: "Empatia",category: "Emoções",related: ["Simpatia"],hint: "A habilidade de sentir o que o outro sente, colocando-se no lugar dele.",},
  {word: "Simpatia",category: "Emoções",related: ["Empatia"],hint: "Sentimento de afinidade ou inclinação agradável por alguém.",},
  {word: "Liberdade",category: "Emoções",related: ["Independência"],hint: "O direito de agir segundo a própria vontade, sem restrições externas.",},
  {word: "Independência",category: "Emoções",related: ["Liberdade"],hint: "O estado de quem não está sob o domínio de outrem ou de um país.",},
  // --- SUBSTANTIVOS COMPOSTOS E COLETIVOS ---
  {word: "Guarda-roupa",category: "Objetos",related: ["Cômoda"],hint: "Móvel alto e vertical usado para organizar vestimentas penduradas.",},
  {word: "Cômoda",category: "Objetos",related: ["Guarda-roupa"],hint: "Móvel baixo com várias gavetas horizontais para roupas dobradas.",},
  {word: "Beija-flor",category: "Animais",related: ["Borboleta"],hint: "Pequeno ser alado que consegue pairar no ar enquanto se alimenta.",},
  {word: "Borboleta",category: "Animais",related: ["Beija-flor"],hint: "Ser que passa por uma transformação radical antes de ganhar asas coloridas.",},
  {word: "Girassol",category: "Natureza",related: ["Margarida"],hint: "Uma planta que busca constantemente a orientação da luz solar.",},
  {word: "Margarida",category: "Natureza",related: ["Girassol"],hint: "Flor delicada com pétalas brancas, muito usada para o 'bem-me-quer'.",},
  {word: "Elenco",category: "Substantivos variados",related: ["Orquestra"],hint: "O grupo de pessoas que interpreta os papéis em um filme ou peça.",},
  {word: "Orquestra",category: "Substantivos variados",related: ["Elenco"],hint: "Um coletivo de músicos que tocam instrumentos variados sob regência.",},
  {word: "Conclave",category: "Substantivos variados",related: ["Concílio"],hint: "Reunião fechada de cardeais para a escolha de um novo líder religioso.",},
  {word: "Concílio",category: "Substantivos variados",related: ["Conclave"],hint: "Assembleia de autoridades religiosas para decidir sobre dogmas e doutrinas.",},
  {word: "Código",category: "Substantivos variados",related: ["Constituição"],hint: "Um conjunto de leis ou regras organizadas sobre um tema específico.",},
  {word: "Constituição",category: "Substantivos variados",related: ["Código"],hint: "A lei suprema que rege e organiza o funcionamento de um Estado.",},
  // --- NATUREZA E GEOGRAFIA ---
  {word: "Cachoeira",category: "Natureza",related: ["Cascata"],hint: "Uma queda d'água súbita e volumosa de uma grande altura.",},
  {word: "Cascata",category: "Natureza",related: ["Cachoeira"],hint: "Queda d'água que desce em degraus ou de forma mais suave.",},
  {word: "Oceano",category: "Natureza",related: ["Mar"],hint: "A vasta massa de água salgada que separa os continentes da Terra.",},
  {word: "Mar",category: "Natureza",related: ["Oceano"],hint: "Uma extensão de água salgada menor, geralmente próxima à costa.",},
  {word: "Montanha",category: "Natureza",related: ["Colina"],hint: "Grande elevação natural do terreno, com altitude considerável.",},
  {word: "Colina",category: "Natureza",related: ["Montanha"],hint: "Uma elevação de terra suave, arredondada e de baixa altitude.",},
  {word: "Arquipélago",category: "Natureza",related: ["Atol"],hint: "Um conjunto de várias porções de terra cercadas por água.",},
  {word: "Atol",category: "Natureza",related: ["Arquipélago"],hint: "Uma ilha oceânica em formato de anel, formada por corais.",},
  {word: "Caverna",category: "Natureza",related: ["Gruta"],hint: "Cavidade natural profunda na rocha, muitas vezes inexplorada.",},
  {word: "Gruta",category: "Natureza",related: ["Caverna"],hint: "Abertura rochosa menor, muitas vezes usada como abrigo ou santuário.",},
  // --- COMIDA E BEBIDA (Tradições) ---
  {word: "Chimarrão",category: "Comida",related: ["Tereré"],hint: "Bebida quente feita com erva-mate, servida em uma cuia com bomba.",},
  {word: "Tereré",category: "Comida",related: ["Chimarrão"],hint: "Versão gelada do preparo da erva-mate, muito popular no calor.",},
  {word: "Rapadura",category: "Comida",related: ["Pé-de-moleque"],hint: "Doce rígido feito de caldo de cana, símbolo da resistência nordestina.",},
  {word: "Pé-de-moleque",category: "Comida",related: ["Rapadura"],hint: "Doce feito de amendoim misturado com açúcar caramelizado.",},
  {word: "Pamonha",category: "Comida",related: ["Curau"],hint: "Massa de milho verde cozida dentro da própria palha do cereal.",},
  {word: "Curau",category: "Comida",related: ["Pamonha"],hint: "Doce cremoso de milho, servido em tigelas e geralmente polvilhado com canela.",},
  // --- OBJETOS E FERRAMENTAS ---
  {word: "Alicate",category: "Objetos",related: ["Pinça"],hint: "Ferramenta de metal usada para apertar, dobrar ou cortar arames.",},
  {word: "Pinça",category: "Objetos",related: ["Alicate"],hint: "Instrumento usado para segurar ou extrair objetos muito pequenos com precisão.",},
  {word: "Parafuso",category: "Objetos",related: ["Prego"],hint: "Peça metálica com rosca usada para unir partes através de rotação.",},
  {word: "Prego",category: "Objetos",related: ["Parafuso"],hint: "Haste metálica pontiaguda que é fixada através de impacto.",},
  {word: "Paraquedas",category: "Objetos",related: ["Asa-delta"],hint: "Equipamento usado para retardar a queda de um corpo na atmosfera.",},
  {word: "Asa-delta",category: "Objetos",related: ["Paraquedas"],hint: "Aeronave sem motor usada para voo livre e planeio.",},
  // --- SUBSTANTIVOS DERIVADOS E GRAMÁTICA ---
  {word: "Livro",category: "Substantivos variados",related: ["Livraria"],hint: "Conjunto de folhas impressas que formam uma obra literária.",},
  {word: "Livraria",category: "Lugares",related: ["Livro"],hint: "Estabelecimento comercial onde se compram obras de leitura.",},
  {word: "Ferro",category: "Natureza",related: ["Ferrugem"],hint: "Elemento metálico fundamental para a indústria e o sangue humano.",},
  {word: "Ferrugem",category: "Natureza",related: ["Ferro"],hint: "O resultado da oxidação do metal quando exposto à umidade.",},
  {word: "Ouro",category: "Natureza",related: ["Diamante"],hint: "Metal precioso amarelo, maleável e inoxidável.",},
  {word: "Diamante",category: "Natureza",related: ["Ouro"],hint: "Cristal resistente.",},
  {word: "Escritura",category: "Substantivos variados",related: ["Escritório"],hint: "O ato de registrar um texto ou um documento legal de posse.",},
  {word: "Escritório",category: "Lugares",related: ["Escritura"],hint: "Local de trabalho onde se realizam tarefas administrativas e intelectuais.",},
  // --- CONCEITOS FÍSICOS ---
  {word: "Eclipse",category: "Natureza",related: ["Aurora"],hint: "O obscurecimento total ou parcial de um astro por outro.",},
  {word: "Aurora",category: "Natureza",related: ["Eclipse"],hint: "Fenômeno luminoso que ocorre nas regiões polares do planeta.",},
  {word: "Gravidade",category: "Ciência",related: ["Magnetismo"],hint: "A força invisível que atrai todos os corpos para o centro da Terra.",},
  {word: "Magnetismo",category: "Ciência",related: ["Gravidade"],hint: "A força de atração ou repulsão entre objetos com propriedades específicas.",},
  {word: "Átomo",category: "Ciência",related: ["Molécula"],hint: "A menor unidade fundamental da matéria comum.",},
  {word: "Molécula",category: "Ciência",related: ["Átomo"],hint: "Um grupo de dois ou mais componentes básicos unidos por ligações químicas.",},
  //ALEATÓRIOS 3
  // --- SUBSTANTIVOS COLETIVOS E GRAMÁTICA ---
  {word: "Pinacoteca",category: "Substantivos variados",related: ["Museu"],hint: "Um espaço dedicado exclusivamente ao acervo de pinturas.",},
  {word: "Museu",category: "Lugares",related: ["Pinacoteca"],hint: "Instituição que preserva e expõe objetos de valor histórico ou artístico.",},
  {word: "Revoada",category: "Substantivos variados",related: ["Bando"],hint: "O coletivo que descreve o movimento de muitos pássaros no céu.",},
  {word: "Bando",category: "Substantivos variados",related: ["Revoada"],hint: "Coletivo genérico para aves ou grupos de pessoas nômades.",},
  {word: "Enxame",category: "Substantivos variados",related: ["Nuvem"],hint: "Um grupo denso de insetos que trabalham para uma rainha.",},
  {word: "Nuvem",category: "Natureza",related: ["Enxame"],hint: "Conjunto de partículas de água no céu ou um grande grupo de gafanhotos.",},
  {word: "Pomar",category: "Substantivos variados",related: ["Horta"],hint: "Local destinado ao cultivo específico de árvores frutíferas.",},
  {word: "Horta",category: "Substantivos variados",related: ["Pomar"],hint: "Espaço para o cultivo de legumes, verduras e ervas comestíveis.",},
  {word: "Fauna",category: "Substantivos variados",related: ["Flora"],hint: "O conjunto de todas as espécies animais de uma região.",},
  {word: "Flora",category: "Substantivos variados",related: ["Fauna"],hint: "A descrição botânica de todas as plantas de um ecossistema.",},
  // --- PRIMITIVOS E DERIVADOS (Gramática) ---
  {word: "Sapato",category: "Substantivos variados",related: ["Sapataria"],hint: "O objeto de couro ou tecido usado para proteger os pés.",},
  {word: "Sapataria",category: "Substantivos variados",related: ["Sapato"],hint: "O local de comércio ou conserto de calçados.",},
  {word: "Pão",category: "Substantivos variados",related: ["Padaria"],hint: "Alimento básico feito de farinha e fermento.",},
  {word: "Padaria",category: "Substantivos variados",related: ["Pão"],hint: "O estabelecimento onde o pão é produzido e vendido.",},
  {word: "Jardim",category: "Substantivos variados",related: ["Jardineiro"],hint: "Um terreno onde se cultivam flores e plantas ornamentais.",},
  {word: "Jardineiro",category: "Substantivos variados",related: ["Jardim"],hint: "A pessoa que se dedica ao cuidado e manutenção das plantas.",},
  {word: "Cozinha",category: "Substantivos variados",related: ["Cozinheiro"],hint: "O cômodo da casa destinado ao preparo de refeições.",},
  {word: "Cozinheiro",category: "Substantivos variados",related: ["Cozinha"],hint: "Aquele que domina as técnicas de transformar alimentos em pratos.",},
  // --- FAMOSOS (MPB, Sertanejo e Ícones do Brasil) ---
  {word: "Roberto Carlos",category: "Famosos",related: ["Erasmo Carlos"],hint: "O 'Rei' da música brasileira, famoso pelos especiais de fim de ano.",},
  {word: "Erasmo Carlos",category: "Famosos",related: ["Roberto Carlos"],hint: "O 'Tremendão', grande parceiro de composição do Rei e ícone da Jovem Guarda.",},
  {word: "Zeca Pagodinho",category: "Famosos",related: ["Arlindo Cruz"],hint: "Ícone do samba que mora em Xerém e prefere a vida simples.",},
  {word: "Arlindo Cruz",category: "Famosos",related: ["Zeca Pagodinho"],hint: "Mestre do banjo e um dos maiores compositores de samba do país.",},
  {word: "Ana Maria Braga",category: "Famosos",related: ["Palmirinha"],hint: "Apresentadora que divide as manhãs com um papagaio falante.",},
  {word: "Palmirinha",category: "Famosos",related: ["Ana Maria Braga"],hint: "A eterna vovó da culinária brasileira na TV.",},
  {word: "Chitãozinho",category: "Famosos",related: ["Xororó"],hint: "A primeira voz de uma das duplas sertanejas mais antigas em atividade.",},
  {word: "Xororó",category: "Famosos",related: ["Chitãozinho"],hint: "A segunda voz potente, pai de uma famosa dupla de irmãos cantores.",},
  {word: "Adele",category: "Famosos",related: ["Amy Winehouse"],hint: "Cantora britânica de voz poderosa e álbuns nomeados por sua idade.",},
  {word: "Amy Winehouse",category: "Famosos",related: ["Adele"],hint: "Estrela do jazz e soul com estilo marcante e voz inconfundível, falecida cedo.",},
  // --- PERSONAGENS (Folclore e Cultura Popular) ---
  {word: "Saci-Pererê",category: "Personagens",related: ["Curupira"],hint: "Menino de uma perna só que adora fazer travessuras e usa um gorro vermelho.",},
  {word: "Curupira",category: "Personagens",related: ["Saci-Pererê"],hint: "Protetor das matas com pés voltados para trás para enganar caçadores.",},
  {word: "Cinderela",category: "Personagens",related: ["Branca de Neve"],hint: "Uma jovem que perde um sapatinho de cristal ao fugir de um baile.",},
  {word: "Branca de Neve",category: "Personagens",related: ["Cinderela"],hint: "A princesa que viveu com sete mineradores após fugir de uma rainha má.",},
  {word: "Luffy",category: "Personagens",related: ["Zoro"],hint: "O pirata que estica e deseja ser o rei de todos os mares.",},
  {word: "Zoro",category: "Personagens",related: ["Luffy"],hint: "O espadachim que utiliza três lâminas ao mesmo tempo e vive se perdendo.",},
  {word: "Pica-Pau",category: "Personagens",related: ["Pato Donald"],hint: "Um pássaro antropomórfico conhecido por sua risada única e persistência.",},
  {word: "Pato Donald",category: "Personagens",related: ["Pica-Pau"],hint: "Personagem ranzinza que usa uma roupa de marinheiro e quase não se entende o que fala.",},
  // --- OBJETOS E SINÔNIMOS ---
  {word: "Sofá",category: "Objetos",related: ["Divã"],hint: "Móvel estofado presente em quase todas as salas de estar.",},
  {word: "Divã",category: "Objetos",related: ["Sofá"],hint: "Tipo de poltrona sem encosto para os braços, associada à psicanálise.",},
  {word: "Caneta",category: "Objetos",related: ["Lapiseira"],hint: "Utiliza tinta líquida ou em gel para registrar grafias permanentes.",},
  {word: "Lapiseira",category: "Objetos",related: ["Caneta"],hint: "Utiliza grafite fino e um mecanismo para avançar a ponta.",},
  {word: "Tapete",category: "Objetos",related: ["Carpete"],hint: "Peça de tecido móvel usada para forrar o chão de forma decorativa.",},
  {word: "Carpete",category: "Objetos",related: ["Tapete"],hint: "Revestimento têxtil fixo que cobre toda a extensão de um piso.",},
  {word: "Xícara",category: "Objetos",related: ["Caneca"],hint: "Recipiente com asa, geralmente usado para chá ou café em jogos formais.",},
  {word: "Caneca",category: "Objetos",related: ["Xícara"],hint: "Recipiente cilíndrico e maior, usado para bebidas quentes ou frias de forma casual.",},
  {word: "Vidro",category: "Objetos",related: ["Cristal"],hint: "Material transparente e frágil obtido pela fusão de areia.",},
  {word: "Cristal",category: "Objetos",related: ["Vidro"],hint: "Material de alta transparência e brilho, com adição de chumbo na composição.",},
  // --- SUBSTANTIVOS ABSTRATOS (Conceitos Metafísicos) ---
  {word: "Paz",category: "Emoções",related: ["Silêncio"],hint: "Estado de harmonia e ausência de conflitos ou guerras.",},
  {word: "Silêncio",category: "Natureza",related: ["Paz"],hint: "A ausência total de som ou ruído em um ambiente.",},
  {word: "Sorte",category: "Emoções",related: ["Destino"],hint: "A crença em eventos favoráveis que ocorrem por acaso.",},
  {word: "Destino",category: "Emoções",related: ["Sorte"],hint: "A sucessão inevitável de acontecimentos que ninguém pode mudar.",},
  {word: "Ódio",category: "Emoções",related: ["Rancor"],hint: "Sentimento intenso de repulsa ou aversão profunda por algo ou alguém.",},
  {word: "Rancor",category: "Emoções",related: ["Ódio"],hint: "Mágoa profunda que se guarda de uma ofensa recebida por muito tempo.",},
  {word: "Melancolia",category: "Emoções",related: ["Tristeza"],hint: "Um estado de tristeza vaga, profunda e muitas vezes sem causa definida.",},
  {word: "Tristeza",category: "Emoções",related: ["Melancolia"],hint: "Sentimento de dor emocional associado a perdas ou decepções.",},
  {word: "Foco",category: "Emoções",related: ["Atenção"],hint: "A nitidez de uma imagem ou a concentração total em um objetivo.",},
  {word: "Atenção",category: "Emoções",related: ["Foco"],hint: "A aplicação cuidadosa da mente em um objeto ou tarefa.",},
  // --- SUBSTANTIVOS COMPOSTOS ---
  {word: "Arco-íris",category: "Natureza",related: ["Prisma"],hint: "Fenômeno ótico que separa a luz solar em sete cores após a chuva.",},
  {word: "Prisma",category: "Objetos",related: ["Arco-íris"],hint: "Sólido geométrico de vidro que decompõe a luz branca em cores.",},
  {word: "Para-choque",category: "Objetos",related: ["Para-lama"],hint: "Peça do veículo destinada a amortecer impactos leves frontais ou traseiros.",},
  {word: "Para-lama",category: "Objetos",related: ["Para-choque"],hint: "Peça que envolve as rodas para evitar que detritos sejam lançados para cima.",},
  {word: "Couve-flor",category: "Comida",related: ["Brócolis"],hint: "Hortaliça de cor clara e formato de buquê muito compactado.",},
  {word: "Brócolis",category: "Comida",related: ["Couve-flor"],hint: "Hortaliça verde escura rica em ferro com flores comestíveis.",},
  {word: "Passatempo",category: "Jogos",related: ["Entretenimento"],hint: "Atividade feita apenas para o tempo passar de forma prazerosa.",},
  {word: "Entretenimento",category: "Jogos",related: ["Passatempo"],hint: "Indústria ou espetáculo destinado a divertir o público.",},
  // --- CIÊNCIA E TECNOLOGIA ---
  {word: "Satélite",category: "Tecnologia",related: ["Foguete"],hint: "Objeto que orbita um corpo celeste para fins de comunicação ou pesquisa.",},
  {word: "Foguete",category: "Tecnologia",related: ["Satélite"],hint: "Veículo propulsor usado para colocar objetos no espaço sideral.",},
  {word: "Senha",category: "Tecnologia",related: ["Assinatura"],hint: "Código secreto usado para autenticar a identidade de um usuário.",},
  {word: "Assinatura",category: "Substantivos variados",related: ["Senha"],hint: "A marca manuscrita e pessoal que valida um documento.",},
  {word: "Software",category: "Tecnologia",related: ["Hardware"],hint: "A parte lógica e intangível de um sistema computacional.",},
  {word: "Hardware",category: "Tecnologia",related: ["Software"],hint: "Os componentes físicos e táteis que compõem um computador.",},
  {word: "Bateria",category: "Tecnologia",related: ["Pilha"],hint: "Acumulador recarregável de energia para dispositivos móveis.",},
  {word: "Pilha",category: "Tecnologia",related: ["Bateria"],hint: "Gerador galvânico de energia, geralmente de uso único e descartável.",},
  //ALEATÓRIOS 4
  // --- FAMOSOS (Hollywood e Ícones Internacionais) ---
  {word: "Brad Pitt",category: "Famosos",related: ["Leonardo DiCaprio"],hint: "Atleta das telas que venceu o Oscar após décadas e é ícone de beleza.",},
  {word: "Leonardo DiCaprio",category: "Famosos",related: ["Brad Pitt"],hint: "Famoso por um naufrágio épico e pela luta constante pelo meio ambiente.",},
  {word: "Meryl Streep",category: "Famosos",related: ["Fernanda Montenegro"],hint: "Recordista absoluta de indicações ao Oscar, mestre dos sotaques.",},
  {word: "Fernanda Montenegro",category: "Famosos",related: ["Meryl Streep"],hint: "A única brasileira indicada ao Oscar de Melhor Atriz, dama do teatro nacional.",},
  {word: "Tom Cruise",category: "Famosos",related: ["Will Smith"],hint: "Conhecido por dispensar dublês em cenas de ação impossíveis e perigosas.",},
  {word: "Will Smith",category: "Famosos",related: ["Tom Cruise"],hint: "O 'Um Maluco no Pedaço' que se tornou uma das maiores estrelas de ação do mundo.",},
  {word: "Oprah Winfrey",category: "Famosos",related: ["Ellen DeGeneres"],hint: "A rainha do talk show americano, bilionária e influenciadora global.",},
  {word: "Ellen DeGeneres",category: "Famosos",related: ["Oprah Winfrey"],hint: "Apresentadora conhecida por seu humor leve, dancinhas e o bordão 'sejam gentis'.",},
  {word: "Angelina Jolie",category: "Famosos",related: ["Scarlett Johansson"],hint: "Atriz famosa por 'Lara Croft' e por seu intenso trabalho na ONU.",},
  {word: "Scarlett Johansson",category: "Famosos",related: ["Angelina Jolie"],hint: "A 'Viúva Negra' dos cinemas e uma das atrizes mais bem pagas de Hollywood.",},
  // --- JOGOS (Tabuleiro e Cartas) ---
  {word: "Xadrez",category: "Jogos",related: ["Damas"],hint: "Batalha estratégica onde o objetivo final é cercar a peça real do oponente.",},
  {word: "Damas",category: "Jogos",related: ["Xadrez"],hint: "Jogo em tabuleiro quadriculado onde as peças saltam umas sobre as outras.",},
  {word: "Poker",category: "Jogos",related: ["Truco"],hint: "Jogo de cartas internacional onde saber blefar é tão importante quanto as cartas.",},
  {word: "Truco",category: "Jogos",related: ["Poker"],hint: "Jogo de cartas muito barulhento e popular no Brasil, jogado em duplas.",},
  {word: "Monopoly",category: "Jogos",related: ["Banco Imobiliário"],hint: "O jogo original de compra de propriedades que destrói amizades há décadas.",},
  {word: "Banco Imobiliário",category: "Jogos",related: ["Monopoly"],hint: "A versão brasileira clássica do jogo de negociação de ruas e empresas.",},
  {word: "Dominó",category: "Jogos",related: ["Mahjong"],hint: "Pequenas peças retangulares com pontos que devem ser conectadas por números iguais.",},
  {word: "Mahjong",category: "Jogos",related: ["Dominó"],hint: "Jogo de origem chinesa que utiliza peças com ideogramas e símbolos complexos.",},
  // --- GEOGRAFIA (Países vs. Capitais) ---
  {word: "Tóquio",category: "Países e Cidades",related: ["Japão"],hint: "A metrópole mais populosa do mundo, mistura de neon e tradição.",},
  {word: "Japão",category: "Países e Cidades",related: ["Tóquio"],hint: "Arquipélago conhecido como a 'Terra do Sol Nascente'.",},
  {word: "Paris",category: "Países e Cidades",related: ["França"],hint: "Destino turístico número um do mundo, cortada pelo Rio Sena.",},
  {word: "França",category: "Países e Cidades",related: ["Paris"],hint: "Nação europeia famosa pela gastronomia, vinhos e a revolução dos direitos.",},
  {word: "Roma",category: "Países e Cidades",related: ["Itália"],hint: "Cidade que abriga um país inteiro dentro de seus limites geográficos.",},
  {word: "Itália",category: "Países e Cidades",related: ["Roma"],hint: "País com formato de bota, berço do Império Romano e da massa.",},
  {word: "Cairo",category: "Países e Cidades",related: ["Egito"],hint: "Cidade caótica e histórica situada às margens do Rio Nilo.",},
  {word: "Egito",category: "Países e Cidades",related: ["Cairo"],hint: "Nação africana famosa por suas pirâmides e escrita hieroglífica.",},
  // --- SUBSTANTIVOS ABSTRATOS (Filosofia e Ética) ---
  {word: "Ética",category: "Substantivos variados",related: ["Moral"],hint: "O estudo teórico sobre o que é bom ou mau para a sociedade.",},
  {word: "Moral",category: "Substantivos variados",related: ["Ética"],hint: "O conjunto de regras práticas de conduta adotadas por um grupo.",},
  {word: "Ego",category: "Emoções",related: ["Orgulho"],hint: "A parte da mente que busca a autoafirmação e o reconhecimento do eu.",},
  {word: "Orgulho",category: "Emoções",related: ["Ego"],hint: "Sentimento de prazer elevado pelas próprias conquistas ou dignidade.",},
  {word: "Destino",category: "Substantivos variados",related: ["Coincidência"],hint: "A crença de que os eventos da vida seguem um roteiro predeterminado.",},
  {word: "Coincidência",category: "Substantivos variados",related: ["Destino"],hint: "A ocorrência simultânea de eventos que não possuem conexão causal.",},
  {word: "Solidão",category: "Emoções",related: ["Solitude"],hint: "O sentimento doloroso de estar ou sentir-se isolado do mundo.",},
  {word: "Solitude",category: "Emoções",related: ["Solidão"],hint: "A escolha voluntária e prazerosa de estar em sua própria companhia.",},
  // --- TECNOLOGIA MODERNA ---
  {word: "Algoritmo",category: "Tecnologia",related: ["Inteligência Artificial"],hint: "Uma sequência de instruções lógicas para resolver um problema.",},
  {word: "Inteligência Artificial",category: "Tecnologia",related: ["Algoritmo"],hint: "Sistemas que tentam simular a capacidade humana de aprender e decidir.",},
  {word: "Blockchain",category: "Tecnologia",related: ["Criptomoeda"],hint: "Um livro de registros digital e imutável que garante segurança de dados.",},
  {word: "Criptomoeda",category: "Tecnologia",related: ["Blockchain"],hint: "Dinheiro puramente digital que não depende de bancos centrais.",},
  {word: "Metaverso",category: "Tecnologia",related: ["Realidade Virtual"],hint: "Um conceito de mundo virtual persistente onde as pessoas interagem socialmente.",},
  {word: "Realidade Virtual",category: "Tecnologia",related: ["Metaverso"],hint: "Tecnologia de imersão que utiliza óculos para simular um ambiente novo.",},
  // --- SUBSTANTIVOS COLETIVOS E GRAMÁTICA ---
  {word: "Vocabulário",category: "Substantivos variados",related: ["Glossário"],hint: "O conjunto total de palavras que um indivíduo domina ou conhece.",},
  {word: "Glossário",category: "Substantivos variados",related: ["Vocabulário"],hint: "Uma lista alfabética de termos técnicos com suas definições ao fim de um livro.",},
  {word: "Enxoval",category: "Substantivos variados",related: ["Mobília"],hint: "Conjunto de roupas e adornos preparados para um bebê ou casamento.",},
  {word: "Mobília",category: "Substantivos variados",related: ["Enxoval"],hint: "O conjunto de móveis necessários para guarnecer uma residência.",},
  {word: "Elenco",category: "Substantivos variados",related: ["Figuração"],hint: "O grupo principal de atores que dá vida aos personagens de uma obra.",},
  {word: "Figuração",category: "Substantivos variados",related: ["Elenco"],hint: "Pessoas contratadas para preencher o fundo de cenas, sem falas.",},
  // --- OBJETOS E FERRAMENTAS ---
  {word: "Caderno",category: "Objetos",related: ["Agenda"],hint: "Objeto de papel usado para anotações livres ou estudos escolares.",},
  {word: "Agenda",category: "Objetos",related: ["Caderno"],hint: "Caderno datado usado especificamente para organizar compromissos.",},
  {word: "Bota",category: "Objetos",related: ["Coturno"],hint: "Calçado que cobre o pé e parte da perna, usado para proteção ou moda.",},
  {word: "Coturno",category: "Objetos",related: ["Bota"],hint: "Calçado robusto de cano alto, tradicionalmente usado por militares.",},
  {word: "Óleo",category: "Comida",related: ["Azeite"],hint: "Lípido de origem vegetal ou animal usado para frituras em altas temperaturas.",},
  {word: "Azeite",category: "Comida",related: ["Óleo"],hint: "Extraído especificamente de um fruto mediterrâneo, muito usado em saladas.",},
  {word: "Espátula",category: "Objetos",related: ["Colher de Pau"],hint: "Utensílio plano usado para raspar recipientes ou virar alimentos.",},
  {word: "Colher de Pau",category: "Objetos",related: ["Espátula"],hint: "Ferramenta rústica de cozinha, favorita para mexer molhos sem riscar panelas.",},
  // --- NATUREZA (Geomorfologia) ---
  {word: "Planície",category: "Natureza",related: ["Planalto"],hint: "Grande extensão de terreno plano com poucas variações de altitude.",},
  {word: "Planalto",category: "Natureza",related: ["Planície"],hint: "Terreno elevado e plano, cercado por regiões mais baixas.",},
  {word: "Geada",category: "Natureza",related: ["Neve"],hint: "Congelamento do orvalho sobre superfícies durante noites muito frias.",},
  {word: "Neve",category: "Natureza",related: ["Geada"],hint: "Precipitação de cristais de gelo que caem das nuvens em baixas temperaturas.",},
  // ALEATÓRIOS 4
  // --- MARVEL vs. DC (Heróis e Ícones) ---
  {word: "Capitão América",category: "Personagens",related: ["Super-Homem"],hint: "Líder nato que utiliza as cores azul, vermelho e branco como símbolo.",},
  {word: "Super-Homem",category: "Personagens",related: ["Capitão América"],hint: "O herói supremo que representa a esperança e as cores da bandeira americana.",},
  {word: "Viúva Negra",category: "Personagens",related: ["Mulher-Gato"],hint: "Espiã russa altamente treinada em combate e infiltração.",},
  {word: "Mulher-Gato",category: "Personagens",related: ["Viúva Negra"],hint: "Ladra habilidosa conhecida por sua agilidade e furtividade noturna.",},
  {word: "Thor",category: "Personagens",related: ["Mulher-Maravilha"],hint: "Um deus guerreiro que utiliza uma arma mítica para controlar os raios.",},
  {word: "Mulher-Maravilha",category: "Personagens",related: ["Thor"],hint: "Guerreira de origem divina que utiliza laços e braceletes em combate.",},
  {word: "Aquaman",category: "Personagens",related: ["Namor"],hint: "O herdeiro legítimo do trono da cidade submersa de Atlântida (DC).",},
  {word: "Namor",category: "Personagens",related: ["Aquaman"],hint: "O príncipe submarino de um reino oculto nas profundezas (Marvel).",},
  {word: "Flash",category: "Personagens",related: ["Mercúrio"],hint: "O homem mais rápido do mundo, capaz de atravessar dimensões (DC).",},
  {word: "Mercúrio",category: "Personagens",related: ["Flash"],hint: "Mutante conhecido por sua velocidade sobre-humana e impaciência (Marvel).",},
  // --- MARCAS DE VEÍCULOS (Carros e Motos) ---
  {word: "Toyota",category: "Marcas",related: ["Honda"],hint: "Gigante japonesa líder em vendas, famosa pela durabilidade de seus sedãs.",},
  {word: "Honda",category: "Marcas",related: ["Toyota"],hint: "Marca japonesa que domina o mercado mundial de motocicletas e motores.",},
  {word: "Volkswagen",category: "Marcas",related: ["Fiat"],hint: "Montadora alemã cujo nome significa 'carro do povo'.",},
  {word: "Fiat",category: "Marcas",related: ["Volkswagen"],hint: "Marca italiana com forte presença histórica no mercado popular brasileiro.",},
  {word: "Harley-Davidson",category: "Marcas",related: ["Yamaha"],hint: "Ícone americano de motocicletas pesadas e ronco de motor característico.",},
  {word: "Yamaha",category: "Marcas",related: ["Harley-Davidson"],hint: "Fabricante japonesa conhecida por motos esportivas e instrumentos musicais.",},
  {word: "Tesla",category: "Marcas",related: ["BYD"],hint: "Pioneira americana no mercado de veículos totalmente elétricos e autônomos.",},
  {word: "BYD",category: "Marcas",related: ["Tesla"],hint: "Gigante chinesa que se tornou a maior fabricante de carros elétricos do mundo.",},
  // --- ESPORTES (Olímpicos e Radicais) ---
  {word: "Natação",category: "Esporte",related: ["Mergulho"],hint: "Prática de deslocamento na água através de movimentos rítmicos de braços e pernas.",},
  {word: "Mergulho",category: "Esporte",related: ["Natação"],hint: "Atividade de submergir na água, seja por lazer ou salto ornamental.",},
  {word: "Skate",category: "Esporte",related: ["Patins"],hint: "Prancha sobre rodas usada para manobras em pistas ou no asfalto.",},
  {word: "Patins",category: "Esporte",related: ["Skate"],hint: "Calçados com rodas alinhadas que permitem deslizar sobre superfícies lisas.",},
  {word: "Surfe",category: "Esporte",related: ["Windsurfe"],hint: "Esporte de deslizar nas ondas do mar utilizando apenas uma prancha.",},
  {word: "Windsurfe",category: "Esporte",related: ["Surfe"],hint: "Combinação de vela e prancha, movida pela força do vento sobre a água.",},
  {word: "Boxe",category: "Esporte",related: ["Judô"],hint: "Arte marcial focada exclusivamente no uso dos punhos.",},
  {word: "Judô",category: "Esporte",related: ["Boxe"],hint: "Arte marcial japonesa focada em quedas e imobilização do adversário.",},
  // --- GRAMÁTICA (Coletivos Raros e Substantivos Compostos) ---
  {word: "Panapaná",category: "Substantivos variados",related: ["Nuvem"],hint: "O belo coletivo usado para designar um grupo de borboletas em voo.",},
  {word: "Nuvem",category: "Natureza",related: ["Panapaná"],hint: "Coletivo usado para grandes grupos de gafanhotos ou partículas de água no céu.",},
  {word: "Cáfila",category: "Substantivos variados",related: ["Manada"],hint: "Termo coletivo específico para um grupo de camelos ou dromedários.",},
  {word: "Manada",category: "Substantivos variados",related: ["Cáfila"],hint: "Coletivo para animais de grande porte como elefantes ou búfalos.",},
  {word: "Passatempo",category: "Substantivos variados",related: ["Entretenimento"],hint: "Substantivo composto que define algo feito apenas para divertir.",},
  {word: "Entretenimento",category: "Emoções",related: ["Passatempo"],hint: "Ação de distrair ou divertir um público através de uma atividade.",},
  {word: "Girassol",category: "Natureza",related: ["Para-raios"],hint: "Substantivo composto que nomeia uma flor que busca a luz solar.",},
  {word: "Para-raios",category: "Objetos",related: ["Girassol"],hint: "Substantivo composto para um dispositivo que atrai descargas elétricas.",},
  // --- SUBSTANTIVOS ABSTRATOS (Filosofia e Vida) ---
  {word: "Paciência",category: "Emoções",related: ["Tolerância"],hint: "A virtude de manter a calma e esperar o tempo necessário das coisas.",},
  {word: "Tolerância",category: "Emoções",related: ["Paciência"],hint: "A capacidade de aceitar opiniões ou comportamentos diferentes dos seus.",},
  {word: "Resiliência",category: "Emoções",related: ["Resistência"],hint: "A habilidade de se recuperar ou se adaptar após uma crise ou trauma.",},
  {word: "Resistência",category: "Emoções",related: ["Resiliência"],hint: "A força de se opor a uma pressão ou agressor externo sem ceder.",},
  {word: "Realidade",category: "Substantivos variados",related: ["Verdade"],hint: "O mundo como ele realmente é, independente da percepção humana.",},
  {word: "Verdade",category: "Emoções",related: ["Realidade"],hint: "A propriedade de estar em conformidade com os fatos ou a realidade.",},
  {word: "Alma",category: "Substantivos variados",related: ["Espírito"],hint: "A essência imaterial e vital que anima os seres vivos.",},
  {word: "Espírito",category: "Substantivos variados",related: ["Alma"],hint: "A parte imaterial do ser humano, frequentemente associada ao intelecto e fé.",},
  // --- TV E FAMOSOS (Ícones do Brasil) ---
  {word: "Xuxa",category: "Famosos",related: ["Angélica"],hint: "A eterna Rainha dos Baixinhos que marcou gerações na TV.",},
  {word: "Angélica",category: "Famosos",related: ["Xuxa"],hint: "Apresentadora famosa por sua pinta na perna e sucessos infantis nos anos 90.",},
  {word: "Gugu Liberato",category: "Famosos",related: ["Faustão"],hint: "Famoso pelo 'Domingo Legal' e pela 'Banheira do Gugu'.",},
  {word: "Faustão",category: "Famosos",related: ["Gugu Liberato"],hint: "Dono do bordão 'Oloco meu' e dos domingos da TV por décadas.",},
  {word: "Hebe Camargo",category: "Famosos",related: ["Dercy Gonçalves"],hint: "A rainha da TV brasileira, conhecida pelo seu sofá e 'Gracinha'.",},
  {word: "Dercy Gonçalves",category: "Famosos",related: ["Hebe Camargo"],hint: "Ícone da irreverência e comédia, conhecida por sua longevidade e palavrões.",},
  // --- NATUREZA (Biomas do Brasil) ---
  {word: "Pantanal",category: "Natureza",related: ["Amazônia"],hint: "A maior planície de inundação contínua do planeta, rica em jacarés.",},
  {word: "Amazônia",category: "Natureza",related: ["Pantanal"],hint: "A maior floresta tropical do mundo, considerada o pulmão da Terra.",},
  {word: "Cerrado",category: "Natureza",related: ["Caatinga"],hint: "A savana brasileira, com árvores de troncos retorcidos e solo ácido.",},
  {word: "Caatinga",category: "Natureza",related: ["Cerrado"],hint: "Bioma exclusivamente brasileiro, conhecido por sua vegetação adaptada à seca.",},
  // --- TECNOLOGIA E APPS ---
  {word: "Spotify",category: "Tecnologia",related: ["YouTube Music"],hint: "Líder mundial em streaming focado exclusivamente em música e podcasts.",},
  {word: "YouTube Music",category: "Tecnologia",related: ["Spotify"],hint: "Serviço de streaming que utiliza o vasto catálogo de vídeos da Google.",},
  {word: "Airbnb",category: "Tecnologia",related: ["Booking.com"],hint: "Plataforma focada no aluguel de casas e quartos por temporada.",},
  {word: "Booking.com",category: "Tecnologia",related: ["Airbnb"],hint: "Site líder mundial em reservas de hotéis e hospedagens tradicionais.",},
  // --- OBJETOS DE SEGURANÇA ---
  {word: "Cerca",category: "Objetos",related: ["Muro"],hint: "Barreira feita de madeira, arame ou metal para delimitar um espaço.",},
  {word: "Muro",category: "Objetos",related: ["Cerca"],hint: "Estrutura sólida de tijolos ou concreto usada para proteção e divisa.",},
  {word: "Cadeado",category: "Objetos",related: ["Fechadura"],hint: "Dispositivo de metal portátil usado para travar correntes ou portões.",},
  {word: "Fechadura",category: "Objetos",related: ["Cadeado"],hint: "Mecanismo fixo em portas que permite a abertura apenas com chave.",},
  // ALEATÓRIOS 5
  // --- INSTRUMENTOS MUSICAIS (Similares) ---
  {word: "Violão",category: "Músicas",related: ["Guitarra"],hint: "Instrumento de cordas acústico, essencial em rodas de amigos.",},
  {word: "Guitarra",category: "Músicas",related: ["Violão"],hint: "Necessita de amplificação elétrica para mostrar seu verdadeiro poder sonoro.",},
  {word: "Piano",category: "Músicas",related: ["Teclado"],hint: "Grande instrumento de cordas percutidas por martelos internos.",},
  {word: "Teclado",category: "Músicas",related: ["Piano"],hint: "Versão eletrônica e portátil que simula diversos timbres musicais.",},
  {word: "Bateria",category: "Músicas",related: ["Percussão"],hint: "Conjunto de tambores e pratos que marca o ritmo de uma banda.",},
  {word: "Percussão",category: "Músicas",related: ["Bateria"],hint: "Categoria de instrumentos tocados por impacto, mãos ou baquetas.",},
  {word: "Flauta",category: "Músicas",related: ["Saxofone"],hint: "Instrumento de sopro pequeno e agudo, feito de madeira ou metal.",},
  {word: "Saxofone",category: "Músicas",related: ["Flauta"],hint: "Instrumento de metal com palheta, muito associado ao Jazz.",},
  // --- DESENHOS ANIMADOS CLÁSSICOS ---
  {word: "Mickey Mouse",category: "Personagens",related: ["Pernalonga"],hint: "O camundongo que se tornou o maior símbolo de um império do entretenimento.",},
  {word: "Pernalonga",category: "Personagens",related: ["Mickey Mouse"],hint: "O coelho astuto que sempre escapa dos seus caçadores com humor.",},
  {word: "Tom",category: "Personagens",related: ["Jerry"],hint: "O gato cinza que vive uma eterna perseguição doméstica sem sucesso.",},
  {word: "Jerry",category: "Personagens",related: ["Tom"],hint: "O pequeno rato marrom que sempre encontra uma forma de vencer o felino.",},
  {word: "Scooby-Doo",category: "Personagens",related: ["Salsicha"],hint: "Um cão medroso que ajuda um grupo de jovens a desvendar mistérios.",},
  {word: "Salsicha",category: "Personagens",related: ["Scooby-Doo"],hint: "O melhor amigo de um cachorro, conhecido pelo seu apetite insaciável.",},
  {word: "Pica-Pau",category: "Personagens",related: ["Chapolin"],hint: "Uma ave de cabeça vermelha extremamente persistente e debochada.",},
  {word: "Chapolin",category: "Personagens",related: ["Pica-Pau"],hint: "O herói de vermelho que aparece quando alguém exclama: 'E agora, quem poderá me defender?'",},
  // --- FAMOSOS DO BRASIL (Jornalismo e TV) ---
  {word: "William Bonner",category: "Famosos",related: ["Galvão Bueno"],hint: "A voz principal do telejornalismo noturno brasileiro há décadas.",},
  {word: "Galvão Bueno",category: "Famosos",related: ["William Bonner"],hint: "O locutor esportivo que narrou os maiores títulos do esporte nacional.",},
  {word: "Fátima Bernardes",category: "Famosos",related: ["Ana Maria Braga"],hint: "Iniciou no jornalismo sério e migrou com sucesso para o entretenimento matinal.",},
  {word: "Ana Maria Braga",category: "Famosos",related: ["Fátima Bernardes"],hint: "Apresentadora veterana que recebe convidados para tomar café e cozinhar.",},
  {word: "Chico Anysio",category: "Famosos",related: ["Paulo Gustavo"],hint: "O mestre dos mil personagens e da 'Escolinha' mais famosa do Brasil.",},
  {word: "Paulo Gustavo",category: "Famosos",related: ["Chico Anysio"],hint: "Ator que imortalizou a figura da 'Dona Hermínia' no cinema nacional.",},
  // --- GRAMÁTICA (Coletivos e Compostos) ---
  {word: "Banca",category: "Substantivos variados",related: ["Júri"],hint: "Coletivo de examinadores que avaliam um trabalho ou prova.",},
  {word: "Júri",category: "Substantivos variados",related: ["Banca"],hint: "Grupo de cidadãos convocados para decidir o destino de um réu.",},
  {word: "Quadrilha",category: "Substantivos variados",related: ["Bando"],hint: "Coletivo para um grupo de bandidos ou uma dança típica de festa junina.",},
  {word: "Bando",category: "Substantivos variados",related: ["Quadrilha"],hint: "Termo coletivo para malfeitores ou grupos nômades de aves.",},
  {word: "Guarda-sol",category: "Substantivos variados",related: ["Sombrinha"],hint: "Substantivo composto para um objeto grande usado para criar sombra na praia.",},
  {word: "Sombrinha",category: "Substantivos variados",related: ["Guarda-sol"],hint: "Objeto leve e portátil usado para proteger contra o sol ou garoa leve.",},
  {word: "Para-choque",category: "Substantivos variados",related: ["Para-brisa"],hint: "Peça do carro feita para absorver o impacto de colisões leves.",},
  {word: "Para-brisa",category: "Substantivos variados",related: ["Para-choque"],hint: "A grande placa de vidro frontal que protege os ocupantes do vento e chuva.",},
  // --- COMIDA (Básico e Brasil) ---
  {word: "Arroz",category: "Comida",related: ["Feijão"],hint: "O grão branco que serve como base neutra para quase toda refeição brasileira.",},
  {word: "Feijão",category: "Comida",related: ["Arroz"],hint: "O grão caldoso que fornece o ferro necessário no prato do dia a dia.",},
  {word: "Pizza",category: "Comida",related: ["Lasanha"],hint: "Disco de massa coberto, assado rapidamente em forno de alta temperatura.",},
  {word: "Lasanha",category: "Comida",related: ["Pizza"],hint: "Camadas intercaladas de massa, molho e queijo assadas em uma travessa.",},
  {word: "Sushi",category: "Comida",related: ["Sashimi"],hint: "Pequenos bolinhos de arroz temperado acompanhados de peixe ou vegetais.",},
  {word: "Sashimi",category: "Comida",related: ["Sushi"],hint: "Fatias finas e puras de peixe cru, sem acompanhamento de arroz.",},
  {word: "Açaí",category: "Comida",related: ["Sorvete"],hint: "Fruto amazônico roxo consumido gelado, muitas vezes com granola.",},
  {word: "Sorvete",category: "Comida",related: ["Açaí"],hint: "Sobremesa gelada industrializada com diversos sabores artificiais e leite.",},
  // --- SUBSTANTIVOS ABSTRATOS (Conceitos) ---
  {word: "Respeito",category: "Emoções",related: ["Admiração"],hint: "O reconhecimento do valor e dos limites de outra pessoa.",},
  {word: "Admiração",category: "Emoções",related: ["Respeito"],hint: "Um sentimento de espanto positivo e estima por alguém notável.",},
  {word: "Inveja",category: "Emoções",related: ["Cobiça"],hint: "O desejo negativo de possuir o que é do outro ou que o outro não tenha.",},
  {word: "Cobiça",category: "Emoções",related: ["Inveja"],hint: "Desejo ardente e excessivo de possuir riquezas ou bens materiais.",},
  {word: "Honra",category: "Emoções",related: ["Dignidade"],hint: "A reputação e a integridade de alguém perante a sociedade.",},
  {word: "Dignidade",category: "Emoções",related: ["Honra"],hint: "O valor intrínseco de cada ser humano que deve ser preservado.",},
  {word: "Fé",category: "Emoções",related: ["Esperança"],hint: "A crença absoluta naquilo que não se pode ver ou provar.",},
  {word: "Esperança",category: "Emoções",related: ["Fé"],hint: "O sentimento de que algo desejado ainda é possível de acontecer.",},
  // --- NATUREZA E ESPAÇO ---
  {word: "Cometa",category: "Natureza",related: ["Asteroide"],hint: "Corpo celeste feito de gelo e poeira que deixa uma cauda ao se aproximar do sol.",},
  {word: "Asteroide",category: "Natureza",related: ["Cometa"],hint: "Fragmento rochoso espacial que orbita o sol, geralmente entre Marte e Júpiter.",},
  {word: "Planeta",category: "Natureza",related: ["Estrela"],hint: "Corpo celeste sólido ou gasoso que orbita uma fonte de luz e calor.",},
  {word: "Estrela",category: "Natureza",related: ["Planeta"],hint: "Grande esfera de plasma que produz sua própria energia e luz.",},
  {word: "Tsunami",category: "Natureza",related: ["Maremoto"],hint: "O resultado visual de uma grande onda que atinge a costa com força.",},
  {word: "Maremoto",category: "Natureza",related: ["Tsunami"],hint: "O evento sísmico que ocorre no leito oceânico e desloca a água.",},
  // --- LUGARES E OBJETOS ---
  {word: "Cinema",category: "Lugares",related: ["Teatro"],hint: "Local destinado à exibição de obras audiovisuais em uma grande tela.",},
  {word: "Teatro",category: "Lugares",related: ["Cinema"],hint: "Espaço onde atores realizam performances ao vivo diante de um público.",},
  {word: "Lápis",category: "Objetos",related: ["Grafite"],hint: "Instrumento de escrita clássico envolto em madeira que precisa ser apontado.",},
  {word: "Grafite",category: "Objetos",related: ["Lápis"],hint: "O mineral escuro que deixa a marca no papel ou a carga de uma lapiseira.",},
  {word: "Mesa",category: "Objetos",related: ["Escrivaninha"],hint: "Móvel plano e genérico usado para refeições ou apoio variado.",},
  {word: "Escrivaninha",category: "Objetos",related: ["Mesa"],hint: "Móvel específico para trabalho ou estudo, geralmente com gavetas.",},
  {word: "Balde",category: "Objetos",related: ["Bacia"],hint: "Recipiente cilíndrico e fundo, usado para transportar líquidos com uma alça.",},
  {word: "Bacia",category: "Objetos",related: ["Balde"],hint: "Recipiente largo e raso usado para limpeza ou higiene pessoal.",},

]

export const categories = Array.from(
  new Set(WORDS.map((word) => word.category)),
).sort();
