// prettier-ignore



export const WORDS_KO = [
  // === 동물계 / REINO ANIMAL (80단어 / 40쌍) ===
  { word: "호랑이", category: "동물계", related: ["사자"], hint: "한국 전래동화에 자주 등장하는 줄무늬 맹수이자 국가 상징 동물." },
  { word: "사자", category: "동물계", related: ["호랑이"], hint: "갈기가 위엄 있는 밀림의 왕." },
  { word: "개", category: "동물계", related: ["늑대"], hint: "사람과 가장 친밀한 반려동물." },
  { word: "진돗개", category: "동물계", related: ["삽살개"], hint: "한국의 천연기념물이자 영리하고 충성심 강한 토종개." },
  { word: "늑대", category: "동물계", related: ["개"], hint: "무리 생활을 하며 달을 향해 짖는 야생 동물." },
  { word: "고양이", category: "동물계", related: ["호랑이"], hint: "울음소리가 독특하고 유연한 반려동물." },
  { word: "코끼리", category: "동물계", related: ["매머드"], hint: "긴 코와 큰 귀를 가진 지상 최대의 동물." },
  { word: "매머드", category: "동물계", related: ["코끼리"], hint: "긴 털과 굽은 상아를 가졌던 멸종된 고대 동물." },
  { word: "기린", category: "동물계", related: ["얼룩말"], hint: "세상에서 목이 가장 긴 동물." },
  { word: "얼룩말", category: "동물계", related: ["기린"], hint: "검은색과 흰색 줄무늬가 특징인 아프리카 동물." },
  { word: "돌고래", category: "동물계", related: ["고래"], hint: "지능이 높고 초음파로 소통하는 바다 포유류." },
  { word: "고래", category: "동물계", related: ["돌고래"], hint: "바다에 사는 거대한 포유류." },
  { word: "상어", category: "동물계", related: ["범고래"], hint: "바다의 무서운 포식자이자 날카로운 이빨을 가진 물고기." },
  { word: "범고래", category: "동물계", related: ["상어"], hint: "흑백 무늬가 특징인 바다 최상위 포식자." },
  { word: "문어", category: "동물계", related: ["오징어"], hint: "8개의 다리와 높은 지능을 가진 바다 생물." },
  { word: "오징어", category: "동물계", related: ["문어"], hint: "10개의 다리를 가졌으며 먹물을 쏘는 바다 생물." },
  { word: "독수리", category: "동물계", related: ["매"], hint: "하늘의 제왕이라 불리는 시력이 아주 좋은 맹금류." },
  { word: "매", category: "동물계", related: ["독수리"], hint: "사냥에 주로 이용되었던 아주 빠르고 날카로운 새." },
  { word: "닭", category: "동물계", related: ["오리"], hint: "아침을 알리는 울음소리를 내며 알을 낳는 가축." },
  { word: "오리", category: "동물계", related: ["닭"], hint: "부리가 넓적하고 헤엄을 잘 치는 조류." },
  { word: "캥거루", category: "동물계", related: ["코알라"], hint: "주머니에 새끼를 넣고 뛰어다니는 호주 동물." },
  { word: "코알라", category: "동물계", related: ["캥거루"], hint: "유칼립투스 잎을 먹으며 잠을 많이 자는 나무 위 동물." },
  { word: "악어", category: "동물계", related: ["도마뱀"], hint: "물과 육지를 오가며 강력한 턱을 가진 파충류." },
  { word: "거북이", category: "동물계", related: ["자라"], hint: "느리지만 딱딱한 등껍질을 가진 장수의 상징." },
  { word: "개구리", category: "동물계", related: ["두꺼비"], hint: "뒷다리가 발달해 잘 뛰고 매끄러운 피부를 가진 양서류." },
  { word: "두꺼비", category: "동물계", related: ["개구리"], hint: "피부가 울퉁불퉁하고 독이 있는 양서류." },
  { word: "꿀벌", category: "동물계", related: ["말벌"], hint: "꿀을 만들고 꽃가루를 옮기는 곤충." },
  { word: "말벌", category: "동물계", related: ["꿀벌"], hint: "공격적이고 쏘이면 위험한 큰 벌." },
  { word: "거미", category: "동물계", related: ["전갈"], hint: "8개의 다리로 줄을 쳐서 사냥하는 생물." },
  { word: "전갈", category: "동물계", related: ["거미"], hint: "꼬리에 독침이 있고 집게발을 가진 생물." },
  { word: "곰", category: "동물계", related: ["판다"], hint: "겨울잠을 자며 꿀을 좋아하는 덩치 큰 동물." },
  { word: "판다", category: "동물계", related: ["곰"], hint: "대나무를 주식으로 하는 흑백 무늬의 곰." },
  { word: "하마", category: "동물계", related: ["코뿔소"], hint: "입이 아주 크고 물속에서 시간을 많이 보내는 동물." },
  { word: "코뿔소", category: "동물계", related: ["하마"], hint: "코 위에 크고 딱딱한 뿔이 있는 동물." },
  { word: "박쥐", category: "동물계", related: ["부엉이"], hint: "동굴에 살며 거꾸로 매달려 잠을 자는 날아다니는 포유류." },
  { word: "부엉이", category: "동물계", related: ["올빼미"], hint: "밤에 활동하며 머리 위에 깃 장식이 있는 새." },
  { word: "펭귄", category: "동물계", related: ["북극곰"], hint: "날지 못하지만 수영을 잘하는 남극의 새." },
  { word: "북극곰", category: "동물계", related: ["펭귄"], hint: "북극에 살며 하얀 털을 가진 거대한 포식자." },
  { word: "나비", category: "동물계", related: ["나방"], hint: "화려한 날개를 가졌으며 낮에 활동하는 곤충." },
  { word: "말", category: "동물계", related: ["당나귀"], hint: "사람을 태우거나 달리기 경주를 하는 발굽 달린 동물." },
  { word: "소", category: "동물계", related: ["황소"], hint: "농사를 돕고 우유를 제공하는 가축." },
  { word: "돼지", category: "동물계", related: ["멧돼지"], hint: "코가 뭉툭하고 복의 상징으로 여겨지는 가축." },
  { word: "멧돼지", category: "동물계", related: ["돼지"], hint: "산에 살며 날카로운 송곳니가 있는 야생 돼지." },
  { word: "토끼", category: "동물계", related: ["거북이"], hint: "귀가 길고 앞니가 발달한 점프 잘하는 동물." },
  { word: "다람쥐", category: "동물계", related: ["청설모"], hint: "볼에 먹이를 저장하고 도토리를 좋아하는 귀여운 동물." },
  { word: "꽃사슴", category: "동물계", related: ["고라니"], hint: "몸에 하얀 반점이 있고 뿔이 예쁜 동물." },
  { word: "고라니", category: "동물계", related: ["꽃사슴"], hint: "한국 산에서 자주 보이며 비명 같은 울음소리를 내는 동물." },
  { word: "까치", category: "동물계", related: ["까마귀"], hint: "반가운 손님이 온다는 길조로 여겨지는 한국의 새." },
  { word: "까마귀", category: "동물계", related: ["까치"], hint: "검은색 깃털을 가진 영리한 새." },
  { word: "학", category: "동물계", related: ["백로"], hint: "고고한 자태를 뽐내며 십장생 중 하나인 새 (두루미)." },

  // === 식문화 / GASTRONOMY (100단어 / 50쌍) ===
  { word: "김치", category: "식문화", related: ["깍두기"], hint: "한국의 대표적인 발효 채소 음식." },
  { word: "깍두기", category: "식문화", related: ["김치"], hint: "무를 네모나게 썰어 담근 매콤한 김치." },
  { word: "비빔밥", category: "식문화", related: ["볶음밥"], hint: "여러 가지 나물과 고추장을 넣어 비벼 먹는 한국 요리." },
  { word: "불고기", category: "식문화", related: ["갈비"], hint: "얇게 썬 소고기를 양념에 재워 구워 먹는 음식." },
  { word: "삼겹살", category: "식문화", related: ["목살"], hint: "한국인이 가장 즐겨 먹는 돼지고기 구이 부위." },
  { word: "냉면", category: "식문화", related: ["쫄면"], hint: "시원한 육수나 비빔 양념에 먹는 메밀 국수 요리." },
  { word: "떡볶이", category: "식문화", related: ["순대"], hint: "고추장 양념에 떡을 볶아 만든 한국의 대표 길거리 음식." },
  { word: "순대", category: "식문화", related: ["떡볶이"], hint: "당면과 선지로 속을 채운 한국식 소시지." },
  { word: "라면", category: "식문화", related: ["국수"], hint: "간편하게 끓여 먹는 인스턴트 면 요리." },
  { word: "된장찌개", category: "식문화", related: ["김치찌개"], hint: "콩을 발효시킨 장으로 끓인 구수한 한국의 찌개." },
  { word: "김치찌개", category: "식문화", related: ["된장찌개"], hint: "잘 익은 김치와 돼지고기를 넣어 끓인 얼큰한 요리." },
  { word: "소주", category: "식문화", related: ["막걸리"], hint: "한국의 가장 대중적인 투명한 증류주." },
  { word: "막걸리", category: "식문화", related: ["동동주"], hint: "쌀로 빚은 한국 전통의 탁한 술." },
  { word: "치킨", category: "식문화", related: ["맥주"], hint: "한국에서 야식으로 가장 인기 있는 튀긴 닭 요리." },
  { word: "맥주", category: "식문화", related: ["소주"], hint: "보리를 발효시켜 만든 시원한 탄산 술." },
  { word: "삼계탕", category: "식문화", related: ["백숙"], hint: "어린 닭에 인삼과 찹쌀을 넣어 고은 보양식." },
  { word: "잡채", category: "식문화", related: ["당면"], hint: "당면과 여러 채소를 볶아 만든 잔치 음식." },
  { word: "김밥", category: "식문화", related: ["주먹밥"], hint: "김 위에 밥과 재료를 올려 돌돌 말아 만든 음식." },
  { word: "미역국", category: "식문화", related: ["소고기뭇국"], hint: "생일날 한국인이 꼭 먹는 국 요리." },
  { word: "식혜", category: "식문화", related: ["수정과"], hint: "엿기름과 밥알로 만든 달콤한 한국 전통 음료." },
  { word: "수정과", category: "식문화", related: ["식혜"], hint: "생강과 계피를 달여 곶감을 넣어 먹는 전통 음료." },
  { word: "붕어빵", category: "식문화", related: ["호떡"], hint: "물고기 모양 틀에 팥소를 넣어 구운 겨울 간식." },
  { word: "호떡", category: "식문화", related: ["붕어빵"], hint: "밀가루 반죽에 설탕 속을 넣어 구운 호호 불어 먹는 간식." },
  { word: "만두", category: "식문화", related: ["찐빵"], hint: "밀가루 피에 고기와 채소를 채워 찌거나 튀긴 음식." },
  { word: "커피", category: "식문화", related: ["녹차"], hint: "현대 한국인이 식후에 가장 많이 마시는 음료." },
  { word: "피자", category: "식문화", related: ["파스타"], hint: "이탈리아에서 왔지만 한국식 토핑이 발달한 밀가루 요리." },
  { word: "탕수육", category: "식문화", related: ["짜장면"], hint: "고기를 튀겨 달콤새콤한 소스를 부어 먹는 요리." },
  { word: "짜장면", category: "식문화", related: ["짬뽕"], hint: "검은색 춘장 양념에 면을 비벼 먹는 한국식 중화요리." },
  { word: "짬뽕", category: "식문화", related: ["짜장면"], hint: "해산물이 듬뿍 들어간 얼큰하고 매운 국물 면 요리." },
  { word: "죽", category: "식문화", related: ["미음"], hint: "쌀을 오래 끓여 부드럽게 만든 음식으로 아플 때 주로 먹음." },
  { word: "팥빙수", category: "식문화", related: ["아이스크림"], hint: "간 얼음 위에 팥과 떡 등을 올려 먹는 여름 디저트." },
  { word: "우유", category: "식문화", related: ["두유"], hint: "소가 제공하는 하얀색 영양 음료." },
  { word: "치즈", category: "식문화", related: ["버터"], hint: "우유를 발효시켜 고체로 만든 음식." },
  { word: "초콜릿", category: "식문화", related: ["사탕"], hint: "카카오로 만든 달콤하고 쌉싸름한 간식." },
  { word: "사탕", category: "식문화", related: ["초콜릿"], hint: "설탕을 녹여 굳힌 딱딱하고 달콤한 간식." },
  { word: "빵", category: "식문화", related: ["샌드위치"], hint: "밀가루 반죽을 구워 만든 서양식 주식." },
  { word: "달걀", category: "식문화", related: ["메추리알"], hint: "닭이 낳은 알로 요리에 가장 많이 쓰임." },
  { word: "사과", category: "식문화", related: ["배"], hint: "아삭하고 달콤한 빨간색 대표 과일." },
  { word: "배", category: "식문화", related: ["사과"], hint: "한국에서 제사나 선물용으로 많이 쓰이는 크고 시원한 과일." },
  { word: "포도", category: "식문화", related: ["머루"], hint: "송이째 열리는 보라색 과일." },
  { word: "수박", category: "식문화", related: ["참외"], hint: "줄무늬가 있고 속이 빨간 여름 대표 과일." },
  { word: "딸기", category: "식문화", related: ["토마토"], hint: "빨간색에 씨가 겉에 박힌 달콤한 봄 과일." },
  { word: "감", category: "식문화", related: ["귤"], hint: "가을에 열리는 주황색 과일로 말려서 곶감을 만듦." },
  { word: "귤", category: "식문화", related: ["오렌지"], hint: "겨울철 한국인이 가장 많이 까먹는 과일." },
  { word: "감자", category: "식문화", related: ["고구마"], hint: "땅속에서 자라는 대표적인 구황작물." },
  { word: "고구마", category: "식문화", related: ["감자"], hint: "겨울철 구워 먹으면 맛있는 달콤한 땅속 작물." },
  { word: "두부", category: "식문화", related: ["콩나물"], hint: "콩으로 만든 하얗고 부드러운 단백질 음식." },
  { word: "콜라", category: "식문화", related: ["사이다"], hint: "검은색 톡 쏘는 탄산음료." },
  { word: "사이다", category: "식문화", related: ["콜라"], hint: "투명하고 시원한 한국식 탄산음료." },
  { word: "호두", category: "식문화", related: ["땅콩"], hint: "뇌 모양을 닮은 고소한 견과류." },
  // === 사물 (1부: 80단어) ===
  { word: "숟가락", category: "사물", related: ["젓가락"], hint: "밥이나 국을 떠먹을 때 사용하는 둥근 도구." },
  { word: "젓가락", category: "사물", related: ["숟가락"], hint: "음식을 집어 먹을 때 사용하는 가늘고 긴 한 쌍의 도구." },
  { word: "망치", category: "사물", related: ["못"], hint: "못을 박거나 물건을 두드릴 때 쓰는 연장." },
  { word: "못", category: "사물", related: ["망치"], hint: "물건을 고정하기 위해 망치로 박는 뾰족한 철사." },
  { word: "가위", category: "사물", related: ["칼"], hint: "두 개의 날을 교차시켜 물건을 자르는 도구." },
  { word: "칼", category: "사물", related: ["가위"], hint: "물건을 베거나 자를 때 쓰는 날카로운 도구." },
  { word: "의자", category: "사물", related: ["소파"], hint: "사람이 앉기 위해 다리와 등받이가 있는 가구." },
  { word: "소파", category: "사물", related: ["의자"], hint: "거실에 두는 푹신하고 긴 의자." },
  { word: "침대", category: "사물", related: ["온돌"], hint: "잠을 자기 위해 매트리스가 깔린 가구." },
  { word: "온돌", category: "사물", related: ["침대"], hint: "방바닥을 따뜻하게 데워 잠을 자는 한국 전통 난방 방식." },
  { word: "책상", category: "사물", related: ["식탁"], hint: "공부를 하거나 업무를 볼 때 쓰는 가구." },
  { word: "식탁", category: "사물", related: ["책상"], hint: "밥을 먹을 때 음식을 올려두는 가구." },
  { word: "거울", category: "사물", related: ["액자"], hint: "자신의 모습을 비추어 볼 수 있는 유리 도구." },
  { word: "액자", category: "사물", related: ["거울"], hint: "사진이나 그림을 끼워 보관하는 틀." },
  { word: "시계", category: "사물", related: ["알람시계"], hint: "시간을 확인하기 위해 사용하는 기기." },
  { word: "알람시계", category: "사물", related: ["시계"], hint: "정해진 시간에 소리를 내어 깨워주는 시계." },
  { word: "안경", category: "사물", related: ["렌즈"], hint: "시력을 교정하기 위해 눈앞에 쓰는 도구." },
  { word: "렌즈", category: "사물", related: ["안경"], hint: "눈에 직접 넣어 시력을 교정하는 얇은 막." },
  { word: "우산", category: "사물", related: ["우비"], hint: "비가 올 때 머리 위로 펼쳐서 쓰는 도구." },
  { word: "우비", category: "사물", related: ["우산"], hint: "비에 젖지 않기 위해 입는 방수 옷." },
  { word: "손전등", category: "사물", related: ["전등"], hint: "어두운 곳을 비추는 휴대용 조명 기기." },
  { word: "전등", category: "사물", related: ["손전등"], hint: "방이나 거리를 밝혀주는 고정된 조명." },
  { word: "빗자루", category: "사물", related: ["걸레"], hint: "바닥의 먼지나 쓰레기를 쓸어내는 청소 도구." },
  { word: "걸레", category: "사물", related: ["빗자루"], hint: "바닥을 물로 닦을 때 쓰는 천." },
  { word: "냄비", category: "사물", related: ["프라이팬"], hint: "국이나 찌개를 끓일 때 쓰는 깊은 조리 기구." },
  { word: "프라이팬", category: "사물", related: ["냄비"], hint: "기름을 두르고 음식을 굽거나 볶을 때 쓰는 얕은 조리 기구." },
  { word: "접시", category: "사물", related: ["대접"], hint: "음식을 덜어 먹는 얕고 평평한 그릇." },
  { word: "대접", category: "사물", related: ["접시"], hint: "국이나 숭늉을 담는 크고 깊은 그릇." },
  { word: "포크", category: "사물", related: ["나이프"], hint: "음식을 찍어 먹을 때 쓰는 갈퀴 모양의 양식 도구." },
  { word: "나이프", category: "사물", related: ["포크"], hint: "고기를 썰 때 쓰는 양식용 칼." },
  { word: "컵", category: "사물", related: ["텀블러"], hint: "물이나 음료를 담아 마시는 그릇." },
  { word: "텀블러", category: "사물", related: ["컵"], hint: "음료의 온도를 유지해 주는 휴대용 컵." },
  { word: "텔레비전", category: "사물", related: ["모니터"], hint: "방송 신호를 받아 화면과 소리를 출력하는 가전제품." },
  { word: "모니터", category: "사물", related: ["텔레비전"], hint: "컴퓨터의 화면을 보여주는 출력 장치." },
  { word: "키보드", category: "사물", related: ["마우스"], hint: "글자를 입력하는 컴퓨터 자판." },
  { word: "마우스", category: "사물", related: ["키보드"], hint: "화면의 커서를 움직여 클릭하는 컴퓨터 입력 장치." },
  { word: "카메라", category: "사물", related: ["캠코더"], hint: "사진을 촬영하는 기기." },
  { word: "캠코더", category: "사물", related: ["카메라"], hint: "움직이는 영상을 녹화하는 기기." },
  { word: "이어폰", category: "사물", related: ["스피커"], hint: "귀에 꽂아 혼자 소리를 듣는 음향 기기." },
  { word: "스피커", category: "사물", related: ["이어폰"], hint: "소리를 크게 울려 공간을 채우는 음향 기기." },
  { word: "배낭", category: "사물", related: ["캐리어"], hint: "등에 메는 형태의 가방." },
  { word: "캐리어", category: "사물", related: ["배낭"], hint: "여행 갈 때 짐을 넣어 끄는 바퀴 달린 가방." },
  { word: "지갑", category: "사물", related: ["가방"], hint: "돈이나 카드를 넣어 다니는 작은 소지품." },
  { word: "가방", category: "사물", related: ["지갑"], hint: "물건을 넣어 들거나 메고 다니는 주머니." },
  { word: "연필", category: "사물", related: ["볼펜"], hint: "지우개로 지울 수 있는 흑연 필기구." },
  { word: "볼펜", category: "사물", related: ["연필"], hint: "잉크를 사용해 지워지지 않는 필기구." },
  { word: "빗", category: "사물", related: ["헤어브러시"], hint: "머리카락을 단정하게 빗는 도구." },
  { word: "쿠션", category: "사물", related: ["베개"], hint: "소파나 의자에서 편안함을 주는 푹신한 방석." },
  { word: "베개", category: "사물", related: ["쿠션"], hint: "잠잘 때 머리를 받치는 푹신한 물건." },
  { word: "이불", category: "사물", related: ["매트리스"], hint: "잘 때 몸을 덮어 따뜻하게 하는 천." },
  { word: "도장", category: "사물", related: ["사인"], hint: "한국에서 계약이나 증명을 할 때 이름을 새겨 찍는 도구." },
  { word: "한복", category: "사물", related: ["양복"], hint: "한국의 전통 의상." },
  { word: "짚신", category: "사물", related: ["고무신"], hint: "짚을 엮어 만든 한국 전통 신발." },
  { word: "고무신", category: "사물", related: ["짚신"], hint: "고무로 만든 한국 근대 전통 신발." },
  { word: "부채", category: "사물", related: ["선풍기"], hint: "손으로 흔들어 바람을 일으키는 전통 도구." },
  { word: "선풍기", category: "사물", related: ["부채"], hint: "전기를 이용해 날개를 돌려 바람을 내는 기계." },
  { word: "갓", category: "사물", related: ["두건"], hint: "조선시대 선비들이 머리에 쓰던 전통 모자." },
  { word: "맷돌", category: "사물", related: ["절구"], hint: "곡식을 갈 때 쓰는 둥근 돌 두 개로 된 전통 도구." },
  { word: "절구", category: "사물", related: ["맷돌"], hint: "곡식을 넣고 공이로 찧는 전통 도구." },
  { word: "호미", category: "사물", related: ["삽"], hint: "밭을 매거나 김을 맬 때 쓰는 한국 특유의 작은 농기구." },
  { word: "삽", category: "사물", related: ["호미"], hint: "흙이나 눈을 파고 옮길 때 쓰는 큰 농기구." },
  { word: "지게", category: "사물", related: ["수레"], hint: "등에 지고 짐을 나르는 한국의 전통 운반 도구." },
  { word: "수레", category: "사물", related: ["지게"], hint: "바퀴를 이용해 짐을 끄는 운반 도구." },
  { word: "족자", category: "사물", related: ["병풍"], hint: "그림이나 글씨를 벽에 걸 수 있게 만든 전통 소품." },
  { word: "병풍", category: "사물", related: ["족자"], hint: "바람을 막거나 방을 가리기 위해 세워두는 그림 병풍." },
  { word: "주전자", category: "사물", related: ["찻잔"], hint: "물을 끓이거나 따르는 주둥이가 있는 그릇." },
  { word: "밥그릇", category: "사물", related: ["국그릇"], hint: "한국 식탁에서 밥을 담는 오목한 그릇." },
  { word: "가마", category: "사물", related: ["마차"], hint: "사람이 메고 가던 한국 전통 이동 수단." },
  { word: "놋그릇", category: "사물", related: ["도자기"], hint: "구리와 주석을 합금한 한국 전통 금속 그릇 (유기그릇)." },
    { word: "냄비", category: "사물", related: ["프라이팬"], hint: "국이나 찌개를 끓일 때 사용하는 깊은 조리 도구." },
  { word: "프라이팬", category: "사물", related: ["냄비"], hint: "기름을 두르고 음식을 굽거나 볶을 때 쓰는 넓은 도구." },
  { word: "그릇", category: "사물", related: ["접시"], hint: "음식을 담는 오목한 형태의 식기." },
  { word: "접시", category: "사물", related: ["그릇"], hint: "음식을 덜어 먹거나 담는 평평한 식기." },
  { word: "컵", category: "사물", related: ["물병"], hint: "물을 담아 마시는 작은 용기." },
  { word: "물병", category: "사물", related: ["컵"], hint: "물을 담아 보관하거나 휴대하는 통." },
  { word: "도마", category: "사물", related: ["식칼"], hint: "재료를 썰 때 바닥에 받치는 판." },
  { word: "국자", category: "사물", related: ["주걱"], hint: "국을 뜰 때 사용하는 커다란 숟가락 모양 도구." },
  { word: "주걱", category: "사물", related: ["국자"], hint: "밥을 솥에서 퍼낼 때 사용하는 도구." },
  { word: "전자레인지", category: "사물", related: ["오븐"], hint: "전자기파를 이용해 음식을 빠르게 데우는 가전." },
  { word: "진공청소기", category: "사물", related: ["빗자루"], hint: "먼지를 빨아들여 바닥을 청소하는 기계." },
  { word: "빗자루", category: "사물", related: ["진공청소기"], hint: "바닥의 쓰레기를 쓸어내는 고전적인 도구." },
  { word: "다리미", category: "사물", related: ["다림질판"], hint: "옷의 주름을 펴기 위해 뜨거운 열을 이용하는 도구." },
  { word: "빨래건조대", category: "사물", related: ["세탁기"], hint: "젖은 옷을 걸어서 말리는 틀." },
  { word: "쓰레기통", category: "사물", related: ["쓰레받기"], hint: "버릴 물건들을 모아두는 통." },
  { word: "걸레", category: "사물", related: ["대걸레"], hint: "바닥을 닦는 데 쓰는 헝겊." },
  { word: "빗", category: "사물", related: ["헤어드라이어"], hint: "머리카락을 정돈하는 도구." },
  { word: "헤어드라이어", category: "사물", related: ["빗"], hint: "머리카락을 말리는 바람이 나오는 기구." },
  { word: "베개", category: "사물", related: ["이불"], hint: "잠잘 때 머리에 베는 물건." },
  { word: "이불", category: "사물", related: ["베개"], hint: "잠잘 때 몸을 덮어 따뜻하게 유지하는 침구." },
  { word: "화장대", category: "사물", related: ["전신거울"], hint: "화장품을 올려두고 거울을 보며 단장하는 가구." },
  { word: "칫솔", category: "사물", related: ["치약"], hint: "이를 닦을 때 쓰는 솔." },
  { word: "치약", category: "사물", related: ["칫솔"], hint: "이를 닦을 때 칫솔에 묻혀 쓰는 약제." },
  { word: "면도기", category: "사물", related: ["쉐이빙폼"], hint: "수염을 깎는 도구." },
  { word: "연필", category: "사물", related: ["볼펜"], hint: "흑연심을 이용해 글씨를 쓰는 도구." },
  { word: "볼펜", category: "사물", related: ["연필"], hint: "잉크와 작은 구슬을 이용해 글씨를 쓰는 도구." },
  { word: "지우개", category: "사물", related: ["수정테이프"], hint: "연필로 쓴 글씨를 지우는 물건." },
  { word: "필통", category: "사물", related: ["연필"], hint: "필기구들을 담아 보관하는 상자." },
  { word: "공책", category: "사물", related: ["책"], hint: "글씨를 쓸 수 있도록 묶어 놓은 종이 뭉치." },
  { word: "책", category: "사물", related: ["공책"], hint: "내용이 인쇄된 종이를 묶어 만든 저작물." },
  { word: "자", category: "사물", related: ["컴퍼스"], hint: "길이를 재거나 선을 긋는 도구." },
  { word: "스테이플러", category: "사물", related: ["클립"], hint: "종이를 철심으로 찍어 고정하는 도구." },
  { word: "도자기", category: "사물", related: ["화병"], hint: "흙을 구워 만든 한국의 전통적인 그릇." },
  { word: "비녀", category: "사물", related: ["쪽머리"], hint: "옛 여인들이 머리를 고정하기 위해 꽂던 장신구." },
  { word: "돗자리", category: "사물", related: ["카페트"], hint: "바닥에 깔고 앉는 대나무나 풀로 엮은 판." },
  { word: "항아리", category: "사물", related: ["장독대"], hint: "김치나 장을 담아두는 흙으로 구운 큰 단지." },
  { word: "절구", category: "사물", related: ["공이"], hint: "곡식이나 양념을 넣고 찧는 도구." },
  { word: "외장하드", category: "사물", related: ["USB 메모리"], hint: "데이터를 많이 저장할 수 있는 휴대용 저장장치." },
  { word: "이어폰", category: "사물", related: ["스피커"], hint: "귀에 꽂아 소리를 듣는 개인용 음향 기기." },
  { word: "스피커", category: "사물", related: ["이어폰"], hint: "전기 신호를 소리로 바꾸어 크게 들려주는 장치." },
  { word: "공유기", category: "사물", related: ["모뎀"], hint: "무선 인터넷(Wi-Fi) 신호를 쏴주는 기기." },
  { word: "보조배터리", category: "사물", related: ["충전기"], hint: "밖에서 휴대폰을 충전할 수 있게 전기를 담아둔 기기." },
  { word: "카메라", category: "사물", related: ["삼각대"], hint: "사진이나 영상을 촬영하는 장치." },
  { word: "구두", category: "사물", related: ["운동화"], hint: "정장이나 격식 있는 옷에 신는 가죽 신발." },
  { word: "운동화", category: "사물", related: ["구두"], hint: "활동하기 편하게 만든 스포츠용 신발." },
  { word: "옷걸이", category: "사물", related: ["행거"], hint: "옷을 걸어서 보관하는 도구." },
  { word: "열쇠", category: "사물", related: ["자물쇠"], hint: "잠긴 문을 열 때 사용하는 도구." },
  { word: "자물쇠", category: "사물", related: ["열쇠"], hint: "문이나 상자를 잠그는 장치." },
  { word: "선글라스", category: "사물", related: ["안경"], hint: "눈을 햇빛으로부터 보호하기 위해 쓴 검은 안경." },
  { word: "모자", category: "사물", related: ["비니"], hint: "머리에 써서 햇빛을 가리거나 멋을 내는 물건." },
  { word: "캐리어", category: "사물", related: ["여행가방"], hint: "여행 갈 때 짐을 넣어 끄는 바퀴 달린 가방." },
  { word: "여권", category: "사물", related: ["비자"], hint: "해외로 나갈 때 신분을 증명하는 증명서." },
  // === 지리 / GEOGRAPHY (150단어 / 75쌍) ===
  { word: "서울", category: "지리", related: ["부산"], hint: "한국의 수도이자 최대 도시." },
  { word: "부산", category: "지리", related: ["서울"], hint: "한국 제2의 도시이자 최대의 항구 도시." },
  { word: "한강", category: "지리", related: ["낙동강"], hint: "서울의 중심을 가로질러 흐르는 한국의 대표적인 강." },
  { word: "낙동강", category: "지리", related: ["한강"], hint: "영남 지방을 가로질러 남해로 흐르는 한국에서 가장 긴 강." },
  { word: "한라산", category: "지리", related: ["설악산"], hint: "제주도에 위치한 한국에서 가장 높은 산." },
  { word: "설악산", category: "지리", related: ["한라산"], hint: "강원도에 위치하며 단풍과 흔들바위가 유명한 산." },
  { word: "독도", category: "지리", related: ["울릉도"], hint: "동해 최동단에 위치한 한국의 영토." },
  { word: "울릉도", category: "지리", related: ["독도"], hint: "동해에 위치한 화산섬으로 호박엿과 오징어가 유명함." },
  { word: "제주도", category: "지리", related: ["거제도"], hint: "한국 최대의 섬이자 대표적인 관광 휴양지." },
  { word: "인천", category: "지리", related: ["경기도"], hint: "국제공항이 위치한 서해안의 관문 도시." },
  { word: "광주", category: "지리", related: ["대전"], hint: "호남 지방의 중심 도시이자 민주화 운동의 상징적인 곳." },
  { word: "대전", category: "지리", related: ["광주"], hint: "한국의 중앙에 위치한 과학과 교통의 중심 도시." },
  { word: "대구", category: "지리", related: ["울산"], hint: "사과와 섬유 산업으로 유명했던 경상도의 분지 도시." },
  { word: "울산", category: "지리", related: ["대구"], hint: "현대자동차와 조선소가 있는 한국 최대의 공업 도시." },
  { word: "경주", category: "지리", related: ["부여"], hint: "신라 천 년의 역사를 간직한 노천 박물관 같은 도시." },
  { word: "동해", category: "지리", related: ["서해"], hint: "한국의 동쪽에 위치한 깊고 푸른 바다." },
  { word: "서해", category: "지리", related: ["동해"], hint: "갯벌이 발달하고 조수 간만의 차가 큰 바다 (황해)." },
  { word: "남해", category: "지리", related: ["동해"], hint: "다도해가 펼쳐진 한국 남쪽의 따뜻한 바다." },
  { word: "백두산", category: "지리", related: ["천지"], hint: "한반도에서 가장 높은 산으로 정상이 호수로 되어 있음." },
  { word: "천지", category: "지리", related: ["백두산"], hint: "백두산 정상에 위치한 거대한 화산호." },
  { word: "판문점", category: "지리", related: ["DMZ"], hint: "남북한의 행정 구역이 맞닿아 있는 공동경비구역(JSA)." },
  { word: "DMZ", category: "지리", related: ["판문점"], hint: "군사 행위가 금지된 비무장 지대." },
  { word: "미국", category: "지리", related: ["캐나다"], hint: "북미에 위치한 50개 주로 구성된 세계 최강대국." },
  { word: "캐나다", category: "지리", related: ["미국"], hint: "세계에서 두 번째로 면적이 넓은 북미의 국가." },
  { word: "일본", category: "지리", related: ["중국"], hint: "한국의 동쪽에 위치한 섬나라로 후지산이 유명함." },
  { word: "중국", category: "지리", related: ["일본"], hint: "세계에서 인구가 가장 많은 아시아의 대국이자 만리장성의 나라." },
  { word: "프랑스", category: "지리", related: ["이탈리아"], hint: "에펠탑과 예술, 미식으로 유명한 유럽 국가." },
  { word: "이탈리아", category: "지리", related: ["프랑스"], hint: "장화 모양의 지형을 가진 로마 제국의 발상지." },
  { word: "영국", category: "지리", related: ["독일"], hint: "신사의 나라로 불리며 런던의 빅벤이 유명한 섬나라." },
  { word: "독일", category: "지리", related: ["영국"], hint: "맥주와 자동차 산업, 베를린 장벽의 역사가 있는 나라." },
  { word: "러시아", category: "지리", related: ["우크라이나"], hint: "세계에서 영토 면적이 가장 넓은 나라." },
  { word: "브라질", category: "지리", related: ["아르헨티나"], hint: "축구와 삼바 축제, 아마존 강이 있는 남미 국가." },
  { word: "아르헨티나", category: "지리", related: ["브라질"], hint: "남미에 위치하며 탱고와 메시의 고향인 나라." },
  { word: "호주", category: "지리", related: ["뉴질랜드"], hint: "캥거루와 코알라가 사는 거대한 대륙 국가 (오스트레일리아)." },
  { word: "이집트", category: "지리", related: ["그리스"], hint: "피라미드와 스핑크스, 나일 강의 기적이 있는 나라." },
  { word: "그리스", category: "지리", related: ["이집트"], hint: "민주주의와 철학의 발상지이자 신화의 나라." },
  { word: "스페인", category: "지리", related: ["포르투갈"], hint: "투우와 플라멩코, 가우디의 건축물이 유명한 나라." },
  { word: "베트남", category: "지리", related: ["태국"], hint: "하롱베이와 쌀국수로 유명한 동남아시아 국가." },
  { word: "태국", category: "지리", related: ["베트남"], hint: "미소의 나라로 불리며 방콕이 수도인 관광 대국." },
  { word: "인도", category: "지리", related: ["중국"], hint: "타지마할이 있고 힌두교 문화가 발달한 인구 대국." },
  { word: "파리", category: "지리", related: ["런던"], hint: "예술과 낭만의 도시라 불리는 프랑스의 수도." },
  { word: "런던", category: "지리", related: ["뉴욕"], hint: "영국의 수도이자 템스 강이 흐르는 역사적인 도시." },
  { word: "뉴욕", category: "지리", related: ["런던"], hint: "미국 최대의 도시이자 세계 경제의 중심지 (자유의 여신상)." },
  { word: "로마", category: "지리", related: ["바티칸"], hint: "이탈리아의 수도이자 도시 전체가 유적인 곳." },
  { word: "도쿄", category: "지리", related: ["오사카"], hint: "일본의 수도이자 세계적인 거대 메트로폴리스." },
  { word: "베이징", category: "지리", related: ["상하이"], hint: "중국의 수도이자 자금성이 위치한 곳." },
  { word: "에베레스트", category: "지리", related: ["히말라야"], hint: "세상에서 가장 높은 산." },
  { word: "히말라야", category: "지리", related: ["안데스"], hint: "아시아에 위치한 세계에서 가장 높은 산맥." },
  { word: "사하라 사막", category: "지리", related: ["고비 사막"], hint: "아프리카에 있는 세계 최대의 뜨거운 사막." },
  { word: "태평양", category: "지리", related: ["대서양"], hint: "지구에서 가장 넓고 깊은 바다." },
  { word: "대서양", category: "지리", related: ["태평양"], hint: "아메리카와 유럽, 아프리카 사이에 있는 바다." },
  { word: "북극", category: "지리", related: ["남극"], hint: "지구의 가장 북쪽 지점으로 북극곰이 삼." },
  { word: "남극", category: "지리", related: ["북극"], hint: "지구의 가장 남쪽 지점으로 펭귄이 삼." },
  { word: "유럽", category: "지리", related: ["아시아"], hint: "서구 문화의 발상지인 대륙." },
  { word: "아시아", category: "지리", related: ["유럽"], hint: "지구에서 가장 크고 인구가 많은 대륙." },
  { word: "아프리카", category: "지리", related: ["남미"], hint: "사바나와 정글, 다양한 야생 동물이 사는 대륙." },
  { word: "나일 강", category: "지리", related: ["아마존 강"], hint: "이집트를 흐르는 세계에서 가장 긴 강 중 하나." },
  { word: "알프스", category: "지리", related: ["히말라야"], hint: "유럽 중부에 위치한 아름다운 설산 산맥." },
  { word: "싱가포르", category: "지리", related: ["홍콩"], hint: "동남아시아의 깨끗하고 현대적인 도시 국가." },
  { word: "스위스", category: "지리", related: ["오스트리아"], hint: "알프스 산맥과 시계, 초콜릿으로 유명한 영구 중립국." },
  { word: "대만", category: "지리", related: ["홍콩"], hint: "타이베이 101 빌딩과 야시장이 유명한 아시아의 섬." },
  { word: "필리핀", category: "지리", related: ["인도네시아"], hint: "7,000개가 넘는 섬으로 이루어진 휴양 국가." },
  { word: "멕시코", category: "지리", related: ["스페인"], hint: "타코와 데킬라, 마야 문명의 유적이 있는 나라." },
  { word: "이스라엘", category: "지리", related: ["터키"], hint: "중동에 위치하며 예루살렘이 있는 성지의 나라." },
  { word: "베네치아", category: "지리", related: ["피렌체"], hint: "운하와 곤돌라로 유명한 이탈리아의 물의 도시." },
  { word: "두바이", category: "지리", related: ["아부다비"], hint: "부르즈 할리파 등 초현대적 건축물이 가득한 사막의 도시." },
  { word: "그린란드", category: "지리", related: ["아이슬란드"], hint: "세계에서 가장 큰 섬으로 대부분 얼음으로 덮여 있음." },
  { word: "적도", category: "지리", related: ["위도"], hint: "지구의 위도 0도인 가상의 선으로 가장 더운 지역." },
  { word: "반도", category: "지리", related: ["섬"], hint: "삼면이 바다로 둘러싸인 지형 (예: 한반도)." },
  { word: "사천", category: "지리", related: ["상하이"], hint: "매운 요리로 유명한 중국의 지역 (쓰촨)." },
  { word: "시베리아", category: "지리", related: ["알래스카"], hint: "러시아의 광활하고 추운 동쪽 벌판." },
  { word: "나이아가라 폭포", category: "지리", related: ["빅토리아 폭포"], hint: "미국과 캐나다 국경에 있는 거대한 폭포." },
  { word: "만리장성", category: "지리", related: ["자금성"], hint: "달에서도 보인다는 중국의 거대한 성벽." },
  { word: "자유의 여신상", category: "지리", related: ["엠파이어 스테이트 빌딩"], hint: "뉴욕 항구에 서 있는 미국의 상징적인 조각상." },
  { word: "에펠탑", category: "지리", related: ["루브르 박물관"], hint: "파리의 상징인 거대한 철탑." },
  // === 장소 / PLACES (80단어 / 40쌍) ===
  { word: "병원", category: "장소", related: ["약국"], hint: "아픈 사람을 치료하고 수술하는 곳." },
  { word: "약국", category: "장소", related: ["병원"], hint: "처방전을 가져가거나 상비약을 사는 곳." },
  { word: "학교", category: "장소", related: ["대학교"], hint: "학생들이 공부하고 배움을 얻는 교육 기관." },
  { word: "대학교", category: "장소", related: ["학교"], hint: "고등학교 졸업 후 전공 지식을 배우는 고등 교육 기관." },
  { word: "공항", category: "장소", related: ["항구"], hint: "비행기가 이착륙하고 여행객들이 모이는 곳." },
  { word: "항구", category: "장소", related: ["공항"], hint: "배가 정박하고 물자를 실어 나르는 바닷가 장소." },
  { word: "노래방", category: "장소", related: ["PC방"], hint: "한국인이 스트레스를 풀러 가서 마이크를 잡는 곳." },
  { word: "PC방", category: "장소", related: ["노래방"], hint: "컴퓨터 게임을 즐기며 음식을 시켜 먹을 수 있는 곳." },
  { word: "편의점", category: "장소", related: ["대형마트"], hint: "24시간 운영하며 간식이나 생필품을 파는 작은 상점." },
  { word: "대형마트", category: "장소", related: ["편의점"], hint: "카트를 끌며 대량으로 장을 보는 커다란 상점." },
  { word: "지하철역", category: "장소", related: ["버스정류장"], hint: "땅속으로 다니는 기차를 타기 위해 가는 곳." },
  { word: "버스정류장", category: "장소", related: ["지하철역"], hint: "도로변에서 버스를 기다리는 장소." },
  { word: "영화관", category: "장소", related: ["공연장"], hint: "큰 스크린에서 상영하는 영상을 보러 가는 곳." },
  { word: "공연장", category: "장소", related: ["영화관"], hint: "콘서트나 뮤지컬 등을 직접 관람하는 장소." },
  { word: "찜질방", category: "장소", related: ["목욕탕"], hint: "양머리를 하고 식혜와 구운 계란을 먹으며 쉬는 한국식 사우나." },
  { word: "목욕탕", category: "장소", related: ["찜질방"], hint: "따뜻한 탕에 몸을 담그고 때를 미는 곳." },
  { word: "우체국", category: "장소", related: ["은행"], hint: "편지나 택배를 보내기 위해 방문하는 공공기관." },
  { word: "은행", category: "장소", related: ["우체국"], hint: "돈을 저금하거나 대출을 받는 금융 기관." },
  { word: "경찰서", category: "장소", related: ["소방서"], hint: "범죄를 예방하고 시민의 안전을 지키는 곳." },
  { word: "소방서", category: "장소", related: ["경찰서"], hint: "불이 났을 때 출동하여 화재를 진압하는 곳." },
  { word: "도서관", category: "장소", related: ["서점"], hint: "책을 무료로 빌려보거나 공부를 하는 조용한 공간." },
  { word: "서점", category: "장소", related: ["도서관"], hint: "새로 나온 책을 직접 사러 가는 곳." },
  { word: "공원", category: "장소", related: ["산책로"], hint: "도시 속에서 나무와 풀을 보며 휴식하는 녹지 공간." },
  { word: "놀이터", category: "장소", related: ["공원"], hint: "그네, 미끄럼틀 등 아이들이 뛰어노는 시설이 있는 곳." },
  { word: "카페", category: "장소", related: ["빵집"], hint: "커피나 차를 마시며 대화를 나누는 곳." },
  { word: "빵집", category: "장소", related: ["카페"], hint: "맛있는 빵과 케이크를 구워 파는 곳 (베이커리)." },
  { word: "백화점", category: "장소", related: ["면세점"], hint: "여러 브랜드가 입점한 크고 화려한 쇼핑 건물." },
  { word: "면세점", category: "장소", related: ["백화점"], hint: "해외 여행객을 위해 세금을 빼고 물건을 파는 상점." },
  { word: "횟집", category: "장소", related: ["고기집"], hint: "신선한 물고기 회를 파는 식당." },
  { word: "고기집", category: "장소", related: ["횟집"], hint: "삼겹살이나 갈비 등을 구워 먹는 식당." },
  { word: "학원", category: "장소", related: ["독서실"], hint: "한국 학생들이 방과 후에 추가로 공부하러 가는 교육 시설." },
  { word: "독서실", category: "장소", related: ["학원"], hint: "칸막이 책상이 있는 조용히 집중해서 공부하는 곳." },
  { word: "미용실", category: "장소", related: ["이발소"], hint: "머리카락을 자르거나 파마를 하는 곳." },
  { word: "이발소", category: "장소", related: ["미용실"], hint: "주로 남성들이 머리를 깎고 면도를 하는 고전적인 장소." },
  { word: "박물관", category: "장소", related: ["미술관"], hint: "역사적인 유물과 자료를 전시하는 곳." },
  { word: "미술관", category: "장소", related: ["박물관"], hint: "그림이나 조각 등 예술 작품을 감상하는 곳." },
  { word: "주민센터", category: "장소", related: ["구청"], hint: "동네의 행정 업무를 처리해 주는 민원 센터." },
  { word: "구청", category: "장소", related: ["주민센터"], hint: "주민센터보다 더 넓은 지역의 행정을 담당하는 기관." },
  { word: "전통시장", category: "장소", related: ["대형마트"], hint: "길거리 음식을 즐기며 흥정의 재미가 있는 재래 상점가." },
  { word: "놀이공원", category: "장소", related: ["동물원"], hint: "롤러코스터와 같은 놀이기구를 타는 유원지." },
  { word: "동물원", category: "장소", related: ["놀이공원"], hint: "다양한 야생 동물을 직접 볼 수 있도록 꾸며놓은 곳." },
  { word: "바다", category: "장소", related: ["산"], hint: "파도가 치고 모래사장이 펼쳐진 넓은 물가." },
  { word: "산", category: "장소", related: ["바다"], hint: "등산을 하러 가는 높고 숲이 우거진 지형." },
  { word: "카페테리아", category: "장소", related: ["식당"], hint: "회사나 학교 안에 있는 간이 식당 공간." },
  { word: "주차장", category: "장소", related: ["주유소"], hint: "자동차를 세워두는 공간." },
  { word: "주유소", category: "장소", related: ["주차장"], hint: "차에 기름(연료)을 넣는 곳." },
  { word: "헬스장", category: "장소", related: ["수영장"], hint: "운동기구로 몸을 단련하는 체육 시설." },
  { word: "수영장", category: "장소", related: ["헬스장"], hint: "물속에서 수영 연습을 하는 시설." },
  { word: "교회", category: "장소", related: ["성당"], hint: "기독교인들이 모여 예배를 드리는 곳." },
  { word: "성당", category: "장소", related: ["교회"], hint: "천주교 신자들이 모여 미사를 드리는 곳." },
  { word: "절", category: "장소", related: ["한옥"], hint: "불교 승려들이 수행하고 법회를 여는 곳 (사찰)." },
  { word: "동사무소", category: "장소", related: ["시청"], hint: "주민등록등본 등 서류를 떼러 가는 동네 행정 기관." },
  { word: "스키장", category: "장소", related: ["워터파크"], hint: "겨울에 눈 위에서 스키나 보드를 타는 곳." },
  { word: "워터파크", category: "장소", related: ["스키장"], hint: "여름에 물놀이와 슬라이드를 즐기는 대형 시설." },
  { word: "호텔", category: "장소", related: ["펜션"], hint: "고급스러운 서비스와 숙박을 제공하는 건물." },
  { word: "펜션", category: "장소", related: ["호텔"], hint: "여행지에서 가족이나 친구들과 요리를 해 먹으며 머무는 집 모양 숙소." },
  { word: "편의점", category: "장소", related: ["구멍가게"], hint: "물건을 편리하게 살 수 있는 체인 상점." },
  { word: "고시원", category: "장소", related: ["자취방"], hint: "시험 공부를 위해 머무는 아주 좁은 방들이 모인 숙소." },
  { word: "세탁소", category: "장소", related: ["수선집"], hint: "옷을 깨끗하게 빨거나 드라이클리닝 해주는 곳." },
  { word: "장례식장", category: "장소", related: ["결혼식장"], hint: "고인을 추모하고 조문객을 맞이하는 곳." },
  // === 직업 / PROFESSIONS (60단어 / 30쌍) ===
  { word: "의사", category: "직업", related: ["간호사"], hint: "환자를 진찰하고 병을 고치는 전문 면허를 가진 사람." },
  { word: "간호사", category: "직업", related: ["의사"], hint: "병원이 나 보건소에서 환자를 돌보고 의사를 돕는 사람." },
  { word: "변호사", category: "직업", related: ["판사"], hint: "법률적인 도움을 주거나 법정에서 의뢰인을 변호하는 사람." },
  { word: "판사", category: "직업", related: ["검사"], hint: "재판을 진행하고 법에 따라 판결을 내리는 공무원." },
  { word: "검사", category: "직업", related: ["판사"], hint: "범죄 사건을 수사하고 범인에게 벌을 줄 것을 법원에 요청하는 사람." },
  { word: "교사", category: "직업", related: ["교수"], hint: "학교에서 학생들을 가르치고 지도하는 선생님." },
  { word: "교수", category: "직업", related: ["교사"], hint: "대학교에서 학문을 연구하고 학생들을 가르치는 전문가." },
  { word: "경찰관", category: "직업", related: ["소방관"], hint: "범죄를 예방하고 사회의 질서를 유지하는 사람." },
  { word: "소방관", category: "직업", related: ["경찰관"], hint: "화재를 진압하고 재난 현장에서 인명을 구조하는 사람." },
  { word: "군인", category: "직업", related: ["장교"], hint: "나라를 지키기 위해 군대에 복무하는 사람." },
  { word: "직장인", category: "직업", related: ["공무원"], hint: "회사에 다니며 월급을 받고 일하는 사무직 근로자." },
  { word: "공무원", category: "직업", related: ["직장인"], hint: "국가나 지방 공공 단체의 업무를 담당하는 사람." },
  { word: "아이돌", category: "직업", related: ["배우"], hint: "K-POP 노래와 춤으로 큰 인기를 얻는 젊은 연예인." },
  { word: "배우", category: "직업", related: ["아이돌"], hint: "영화, 드라마, 연극 등에서 연기를 하는 사람." },
  { word: "가수", category: "직업", related: ["댄서"], hint: "전문적으로 노래를 부르는 예술가." },
  { word: "개발자", category: "직업", related: ["디자이너"], hint: "컴퓨터 프로그램이나 앱을 만드는 소프트웨어 엔지니어." },
  { word: "웹툰 작가", category: "직업", related: ["소설가"], hint: "인터넷에 연재되는 만화를 그리는 창작자." },
  { word: "요리사", category: "직업", related: ["제과제빵사"], hint: "음식을 전문적으로 만드는 사람 (셰프)." },
  { word: "제과제빵사", category: "직업", related: ["요리사"], hint: "빵, 케이크, 과자 등을 전문적으로 굽는 사람." },
  { word: "승무원", category: "직업", related: ["조종사"], hint: "비행기에서 승객의 안전과 편의를 돕는 사람 (스튜어디스)." },
  { word: "조종사", category: "직업", related: ["승무원"], hint: "비행기나 헬리콥터를 운전하는 파일럿." },
  { word: "미용사", category: "직업", related: ["메이크업 아티스트"], hint: "머리카락을 자르거나 파마를 해주는 전문가." },
  { word: "메이크업 아티스트", category: "직업", related: ["미용사"], hint: "화장을 통해 얼굴이나 몸을 아름답게 꾸며주는 사람." },
  { word: "농부", category: "직업", related: ["어부"], hint: "논밭을 일구어 곡식이나 채소를 재배하는 사람." },
  { word: "어부", category: "직업", related: ["농부"], hint: "바다나 강에서 수산물을 잡는 사람." },
  { word: "기자", category: "직업", related: ["아나운서"], hint: "뉴스를 취재하고 기사를 쓰는 사람." },
  { word: "아나운서", category: "직업", related: ["기자"], hint: "방송국에서 소식을 전달하거나 프로그램을 진행하는 사람." },
  { word: "택시 기사", category: "직업", related: ["버스 기사"], hint: "영업용 승용차로 승객을 원하는 목적지까지 태워주는 사람." },
  { word: "배달원", category: "직업", related: ["집배원"], hint: "음식이나 물건을 주문한 곳으로 직접 가져다주는 사람." },
  { word: "집배원", category: "직업", related: ["배달원"], hint: "우편물이나 택배를 각 가정에 배달해 주는 우체국 직원." },
  { word: "회계사", category: "직업", related: ["은행원"], hint: "개인이나 기업의 돈의 흐름을 계산하고 기록하는 전문가." },
  { word: "은행원", category: "직업", related: ["회계사"], hint: "금융 기관의 창구에서 고객의 예금이나 대출 업무를 돕는 사람." },
  { word: "과학자", category: "직업", related: ["연구원"], hint: "자연 현상을 관찰하고 실험하여 원리를 밝혀내는 사람." },
  { word: "운동선수", category: "직업", related: ["코치"], hint: "스포츠 경기에 직접 참여하여 경쟁하는 사람." },
  { word: "정치인", category: "직업", related: ["외교관"], hint: "국가의 정책을 결정하거나 선거를 통해 선출된 사람." },
  { word: "외교관", category: "직업", related: ["정치인"], hint: "외국에서 자기 나라를 대표하여 업무를 처리하는 공무원." },
  { word: "건축가", category: "직업", related: ["목수"], hint: "건물을 설계하고 공사를 관리하는 사람." },
  { word: "목수", category: "직업", related: ["건축가"], hint: "나무를 다루어 집을 짓거나 가구를 만드는 기술자." },
  { word: "수의사", category: "직업", related: ["사육사"], hint: "아픈 동물을 진료하고 치료하는 전문 의사." },
  { word: "사육사", category: "직업", related: ["수의사"], hint: "동물원에서 동물을 돌보고 먹이를 주는 사람." },
  { word: "통역사", category: "직업", related: ["번역가"], hint: "서로 다른 언어를 쓰는 사람들 사이에서 말을 전달해 주는 사람." },
  { word: "번역가", category: "직업", related: ["통역사"], hint: "글로 된 외국어를 다른 언어로 바꾸어 쓰는 사람." },
  { word: "비서", category: "직업", related: ["보좌관"], hint: "상사를 도와 일정을 관리하고 업무를 보조하는 사람." },
  { word: "탐정", category: "직업", related: ["추리"], hint: "비밀리에 사건을 조사하고 정보를 수집하는 사람." },
  { word: "점원", category: "직업", related: ["가게 주인"], hint: "가게에서 손님에게 물건을 팔거나 응대하는 사람." },
  { word: "환경미화원", category: "직업", related: ["경비원"], hint: "거리나 공공장소를 깨끗하게 청소하는 사람." },
  { word: "경비원", category: "직업", related: ["환경미화원"], hint: "건물을 지키고 외부인의 출입을 관리하는 사람." },
  { word: "사진작가", category: "직업", related: ["모델"], hint: "카메라로 사진을 예술적으로 촬영하는 사람." },
  { word: "만화가", category: "직업", related: ["애니메이터"], hint: "만화를 전문적으로 그리는 창작자." },
  { word: "애니메이터", category: "직업", related: ["만화가"], hint: "만화 영화를 만들기 위해 그림을 움직이게 작업하는 사람." },
  { word: "변리사", category: "직업", related: ["특허"], hint: "특허나 상표 같은 지식재산권을 보호해 주는 전문가." },
  { word: "공인중개사", category: "직업", related: ["부동산"], hint: "집이나 땅을 사고팔 때 다리를 놓아주는 부동산 전문가." },
  { word: "작곡가", category: "직업", related: ["작사가"], hint: "음악의 멜로디를 만드는 사람." },
  { word: "지휘자", category: "직업", related: ["연주자"], hint: "오케스트라나 합창단을 지휘하여 음악을 완성하는 사람." },
  { word: "디자이너", category: "직업", related: ["패션"], hint: "의상, 인테리어, 그래픽 등을 설계하고 꾸미는 사람." },
  { word: "유튜버", category: "직업", related: ["인플루언서"], hint: "인터넷 동영상 플랫폼에 콘텐츠를 올려 수익을 내는 창작자." },
  { word: "심리상담사", category: "직업", related: ["사회복지사"], hint: "마음이 힘든 사람들의 고민을 들어주고 도와주는 전문가." },
  { word: "치과의사", category: "직업", related: ["약사"], hint: "충치를 치료하거나 치아 건강을 돌보는 의사." },
  { word: "약사", category: "직업", related: ["치과의사"], hint: "처방전에 따라 약을 짓거나 파는 전문가." },
  { word: "알바생", category: "직업", related: ["매니저"], hint: "아르바이트로 일하는 단기 근로자." },
  // === 역사 / HISTORY (100단어 / 50쌍) ===
  { word: "세종대왕", category: "역사", related: ["훈민정음"], hint: "한글을 창제하고 측우기를 만드는 등 과학과 문화를 발전시킨 조선의 성군." },
  { word: "훈민정음", category: "역사", related: ["세종대왕"], hint: "백성을 가르치는 바른 소리라는 뜻으로 창제된 한국 고유의 문자." },
  { word: "이순신", category: "역사", related: ["거북선"], hint: "임진왜란 때 거북선을 이끌고 바다에서 큰 승리를 거둔 영웅." },
  { word: "거북선", category: "역사", related: ["이순신"], hint: "등에 가시를 박고 철갑을 두른 거북이 모양의 군함." },
  { word: "유관순", category: "역사", related: ["3.1 운동"], hint: "아우내 장터에서 만세 운동을 주도한 독립운동가 소녀." },
  { word: "3.1 운동", category: "역사", related: ["유관순"], hint: "1919년 한국인들이 일제의 지배에 항거하여 일어난 거국적 만세 운동." },
  { word: "광개토대왕", category: "역사", related: ["고구려"], hint: "영토를 크게 넓혀 고구려의 전성기를 이끈 왕." },
  { word: "고구려", category: "역사", related: ["광개토대왕"], hint: "고대 삼국 중 가장 용맹하고 넓은 영토를 가졌던 국가." },
  { word: "단군왕검", category: "역사", related: ["고조선"], hint: "한국 역사상 최초의 국가를 세운 시조." },
  { word: "고조선", category: "역사", related: ["단군왕검"], hint: "한반도에 세워진 최초의 국가." },
  { word: "6.25 전쟁", category: "역사", related: ["휴전선"], hint: "1950년 한반도에서 일어난 남북 간의 비극적인 전쟁." },
  { word: "휴전선", category: "역사", related: ["6.25 전쟁"], hint: "남한과 북한을 가로질러 경계를 짓는 군사 분계선 (38선)." },
  { word: "8.15 광복", category: "역사", related: ["대한독립만세"], hint: "1945년 일제 강점기에서 벗어나 주권을 되찾은 날." },
  { word: "첨성대", category: "역사", related: ["신라"], hint: "경주에 위치한 동양에서 가장 오래된 천문 관측소." },
  { word: "신라", category: "역사", related: ["첨성대"], hint: "삼국을 통일하고 천 년 동안 지속되었던 국가." },
  { word: "석굴암", category: "역사", related: ["불국사"], hint: "경주 토함산에 있는 통일 신라 시대의 인공 석굴 사찰." },
  { word: "불국사", category: "역사", related: ["석굴암"], hint: "다보탑과 석가탑이 있는 경주의 대표적인 사찰." },
  { word: "고려", category: "역사", related: ["금속활자"], hint: "코리아(Korea)라는 이름의 유래가 된 국가." },
  { word: "금속활자", category: "역사", related: ["고려"], hint: "세계 최초로 발명된 금속으로 만든 인쇄용 글자 (직지)." },
  { word: "암행어사", category: "역사", related: ["마패"], hint: "왕의 명을 받아 관리들의 잘못을 몰래 조사하던 관리." },
  { word: "마패", category: "역사", related: ["암행어사"], hint: "말 그림이 그려져 있어 암행어사의 신분을 증명하던 증표." },
  { word: "과거시험", category: "역사", related: ["장원급제"], hint: "선비들이 관리가 되기 위해 치르던 국가 시험." },
  { word: "장원급제", category: "역사", related: ["과거시험"], hint: "국가 시험에서 당당히 1등으로 합격함." },
  { word: "선비", category: "역사", related: ["서원"], hint: "학문과 인격을 닦던 유교 사회의 지식인 계층." },
  { word: "장영실", category: "역사", related: ["측우기"], hint: "세종대왕 시대에 수많은 과학 기구를 발명한 천재 과학자." },
  { word: "측우기", category: "역사", related: ["장영실"], hint: "비가 내린 양을 측정하기 위해 만든 세계 최초의 우량계." },
  { word: "허준", category: "역사", related: ["동의보감"], hint: "조선 시대 최고의 의사이자 의학 서적을 집필한 인물." },
  { word: "동의보감", category: "역사", related: ["허준"], hint: "조선 시대에 편찬된 동양 의학의 보물과 같은 책." },
  { word: "김정호", category: "역사", related: ["대동여지도"], hint: "한반도 구석구석을 누비며 정밀한 지도를 만든 인물." },
  { word: "대동여지도", category: "역사", related: ["김정호"], hint: "조선 시대에 제작된 거대하고 정교한 한반도 지도." },
  { word: "피라미드", category: "역사", related: ["파라오"], hint: "이집트 왕들의 무덤으로 쓰인 거대한 돌 건축물." },
  { word: "파라오", category: "역사", related: ["피라미드"], hint: "고대 이집트의 절대 권력을 가진 왕을 부르는 칭호." },
  { word: "로마 제국", category: "역사", related: ["콜로세움"], hint: "지중해 세계를 제패했던 거대하고 강력한 고대 국가." },
  { word: "콜로세움", category: "역사", related: ["로마 제국"], hint: "검투사 경기 등이 열렸던 로마의 거대 원형 경기장." },
  { word: "검투사", category: "역사", related: ["아레나"], hint: "고대 로마 경기장에서 관중들을 위해 싸우던 무사 (글래디에이터)." },
  { word: "고대 그리스", category: "역사", related: ["민주주의"], hint: "철학, 민주주의, 올림픽이 시작된 문명의 발상지." },
  { word: "민주주의", category: "역사", related: ["고대 그리스"], hint: "국민이 국가의 주인이 되어 권력을 행사하는 정치 체제." },
  { word: "철학", category: "역사", related: ["소크라테스"], hint: "세계와 인간의 삶에 대해 근본적인 질문을 던지는 학문." },
  { word: "알렉산더 대왕", category: "역사", related: ["마케도니아"], hint: "그리스, 이집트, 인도를 잇는 대제국을 건설한 정복자." },
  { word: "중세 시대", category: "역사", related: ["봉건제"], hint: "고대와 근대 사이, 성과 기사들이 활약하던 유럽의 시대." },
  { word: "기사", category: "역사", related: ["갑옷"], hint: "말을 타고 전장을 누비며 명예를 중시하던 중세 전사." },
  { word: "갑옷", category: "역사", related: ["기사"], hint: "전투 중에 몸을 보호하기 위해 입던 금속 옷." },
  { word: "성", category: "역사", related: ["요새"], hint: "침입을 막기 위해 높고 두껍게 쌓은 방어용 건축물." },
  { word: "십자군 전쟁", category: "역사", related: ["예루살렘"], hint: "성지를 탈환하기 위해 유럽 기독교 국가들이 벌인 대규모 원정." },
  { word: "르네상스", category: "역사", related: ["인문주의"], hint: "유럽에서 고대 그리스, 로마 문화를 부활시키려 했던 예술 문화 부흥기." },
  { word: "레오나르도 다 빈치", category: "역사", related: ["모나리자"], hint: "예술과 과학 모두에서 천재성을 발휘한 르네상스의 거장." },
  { word: "프랑스 혁명", category: "역사", related: ["단두대"], hint: "시민들이 왕정을 무너뜨리고 자유와 평등을 외쳤던 사건." },
  { word: "나폴레옹", category: "역사", related: ["황제"], hint: "유럽을 정복하려 했던 프랑스의 군사 지도자이자 황제." },
  { word: "산업혁명", category: "역사", related: ["증기기관"], hint: "기계의 발명으로 생산 방식이 획기적으로 변한 경제적 대변혁." },
  { word: "2차 세계대전", category: "역사", related: ["홀로코스트"], hint: "전 세계가 참여한 인류 역사상 가장 큰 규모의 전쟁." },
  { word: "냉전", category: "역사", related: ["베를린 장벽"], hint: "미국과 소련을 중심으로 한 자본주의와 공산주의의 대립기." },
  { word: "아폴로 11호", category: "역사", related: ["달 착륙"], hint: "인류 최초로 사람을 달에 착륙시킨 우주선." },
  { word: "콜럼버스", category: "역사", related: ["신대륙"], hint: "유럽인으로서 아메리카 대륙에 도달하여 항로를 개척한 탐험가." },
  { word: "마틴 루터 킹", category: "역사", related: ["인권 운동"], hint: "비폭력 저항을 통해 인종 차별에 맞선 미국의 목사." },
  { word: "아인슈타인", category: "역사", related: ["상대성 이론"], hint: "현대 물리학의 기틀을 마련한 천재 과학자." },
  { word: "바이킹", category: "역사", related: ["스칸디나비아"], hint: "배를 타고 유럽 곳곳을 누비던 북유럽의 전사들이자 항해사." },
  { word: "흑사병", category: "역사", related: ["전염병"], hint: "중세 유럽 인구의 3분의 1을 숨지게 한 무서운 전염병." },
  { word: "사무라이", category: "역사", related: ["일본"], hint: "봉건 시대 일본에서 영주를 섬기던 무사 계급." },
  { word: "안중근", category: "역사", related: ["하얼빈"], hint: "이토 히로부미를 저격하여 한국의 독립 의지를 알린 독립운동가." },
  { word: "발해", category: "역사", related: ["대조영"], hint: "고구려를 계승하여 만주 지역에 세워진 '해동성국'." },
  // === 대중문화 / POP CULTURE (150단어 / 75쌍) ===
  { word: "오징어 게임", category: "대중문화", related: ["달고나"], hint: "넷플릭스 세계 1위를 기록한 한국의 서바이벌 드라마." },
  { word: "달고나", category: "대중문화", related: ["오징어 게임"], hint: "설탕을 녹여 만든 과자로, 모양대로 뽑아야 사는 게임에 등장함." },
  { word: "기생충", category: "대중문화", related: ["봉준호"], hint: "한국 영화 최초로 칸 황금종려상과 오스카 작품상을 받은 영화." },
  { word: "봉준호", category: "대중문화", related: ["기생충"], hint: "영화 '기생충', '괴물', '설국열차'를 연출한 세계적인 감독." },
  { word: "도깨비", category: "대중문화", related: ["공유"], hint: "불멸의 삶을 끝내기 위해 신부를 찾는 내용을 담은 인기 판타지 드라마." },
  { word: "공유", category: "대중문화", related: ["도깨비"], hint: "드라마 '도깨비'와 영화 '부산행'의 주연 배우." },
  { word: "더 글로리", category: "대중문화", related: ["송혜교"], hint: "학교 폭력 피해자의 처절한 복수극을 그린 드라마." },
  { word: "송혜교", category: "대중문화", related: ["더 글로리"], hint: "드라마 '더 글로리'에서 문동은 역을 맡은 톱배우." },
  { word: "사랑의 불시착", category: "대중문화", related: ["현빈"], hint: "패러글라이딩 사고로 북한에 불시착한 재벌 상속녀의 로맨스 드라마." },
  { word: "현빈", category: "대중문화", related: ["사랑의 불시착"], hint: "드라마 '사랑의 불시착'에서 북한 장교 리정혁을 연기한 배우." },
  { word: "부산행", category: "대중문화", related: ["좀비"], hint: "KTX 열차 안에서 벌어지는 사투를 그린 한국형 좀비 재난 영화." },
  { word: "좀비", category: "대중문화", related: ["부산행"], hint: "죽지 않고 살아 움직이며 사람을 공격하는 괴물." },
  { word: "이상한 변호사 우영우", category: "대중문화", related: ["고래"], hint: "천재적인 두뇌와 자폐 스펙트럼을 가진 변호사의 성장 드라마." },
  { word: "고래", category: "대중문화", related: ["이상한 변호사 우영우"], hint: "주인공 우영우가 가장 사랑하고 영감을 얻는 동물." },
  { word: "킹덤", category: "대중문화", related: ["갓"], hint: "조선 시대를 배경으로 한 넷플릭스의 좀비 스릴러 드라마." },
  { word: "태양의 후예", category: "대중문화", related: ["송중기"], hint: "군인과 의사의 사랑을 그린 '단결!'이라는 유행어의 드라마." },
  { word: "아이돌", category: "대중문화", related: ["연습생"], hint: "K-POP을 이끄는 화려한 스타 가수들." },
  { word: "연습생", category: "대중문화", related: ["아이돌"], hint: "데뷔를 꿈꾸며 춤과 노래를 훈련하는 기간에 있는 사람." },
  { word: "응원봉", category: "대중문화", related: ["팬덤"], hint: "K-POP 콘서트에서 팬들이 흔드는 빛나는 도구." },
  { word: "방탄소년단", category: "대중문화", related: ["아미"], hint: "세계를 정복한 K-POP 그룹 (BTS)." },
  { word: "아미", category: "대중문화", related: ["방탄소년단"], hint: "글로벌 그룹 BTS의 공식 팬클럽 이름." },
  { word: "런닝맨", category: "대중문화", related: ["이름표"], hint: "등 뒤의 이름표를 떼는 게임으로 유명한 장수 예능 프로그램." },
  { word: "무한도전", category: "대중문화", related: ["유재석"], hint: "한국 예능의 전설이라 불리는 리얼 버라이어티 쇼." },
  { word: "유재석", category: "대중문화", related: ["무한도전"], hint: "한국에서 '국민 MC'라고 불리는 최고의 예능인." },
  { word: "해리 포터", category: "대중문화", related: ["볼드모트"], hint: "번개 모양 흉터를 가진 안경 쓴 소년 마법사." },
  { word: "볼드모트", category: "대중문화", related: ["해리 포터"], hint: "이름을 불러서는 안 되는 마법 세계의 악당." },
  { word: "스타워즈", category: "대중문화", related: ["다스 베이더"], hint: "우주를 배경으로 한 서사시적인 SF 영화 시리즈." },
  { word: "다스 베이더", category: "대중문화", related: ["스타워즈"], hint: "검은 가면을 쓰고 숨소리가 거친 스타워즈의 대표 빌런." },
  { word: "광선검", category: "대중문화", related: ["제다이"], hint: "빛나는 날을 가진 마법 같은 칼 (라이트세이버)." },
  { word: "어벤져스", category: "대중문화", related: ["타노스"], hint: "지구를 지키기 위해 모인 마블의 슈퍼히어로 팀." },
  { word: "타노스", category: "대중문화", related: ["어벤져스"], hint: "손가락 튕기기 한 번으로 우주의 절반을 날리려던 거인." },
  { word: "아이언맨", category: "대중문화", related: ["토니 스타크"], hint: "첨단 수트를 입고 싸우는 억만장자 히어로." },
  { word: "스파이더맨", category: "대중문화", related: ["피터 파커"], hint: "거미줄을 쏘며 고층 빌딩 사이를 날아다니는 영웅." },
  { word: "캡틴 아메리카", category: "대중문화", related: ["방패"], hint: "별 무늬가 그려진 원형 방패를 던지는 영웅." },
  { word: "토르", category: "대중문화", related: ["망치"], hint: "묠니르라는 망치를 휘두르는 천둥의 신." },
  { word: "배트맨", category: "대중문화", related: ["조커"], hint: "고담시를 지키는 박쥐 가면의 히어로." },
  { word: "조커", category: "대중문화", related: ["배트맨"], hint: "광기 어린 웃음소리를 가진 배트맨의 최대 숙적." },
  { word: "슈퍼맨", category: "대중문화", related: ["크립토나이트"], hint: "외계에서 온 초인으로 S자가 그려진 파란 옷을 입음." },
  { word: "원더우먼", category: "대중문화", related: ["아마존"], hint: "황금 올가미를 사용하는 여성 영웅의 상징." },
  { word: "타이타닉", category: "대중문화", related: ["빙산"], hint: "거대한 배의 침몰과 비극적인 사랑을 그린 영화." },
  { word: "빙산", category: "대중문화", related: ["타이타닉"], hint: "타이타닉호를 침몰하게 만든 바다 위의 거대한 얼음 덩어리." },
  { word: "인셉션", category: "대중문화", related: ["꿈"], hint: "타인의 꿈속에 들어가 정보를 훔치거나 심는 내용의 영화." },
  { word: "인터스텔라", category: "대중문화", related: ["블랙홀"], hint: "우주와 시간을 다룬 크리스토퍼 놀란의 SF 대작." },
  { word: "매트릭스", category: "대중문화", related: ["네오"], hint: "가상 현실 세계와 빨간 알약, 파란 알약의 선택." },
  { word: "주라기 공원", category: "대중문화", related: ["공룡"], hint: "화석의 DNA로 공룡을 복제해 만든 테마파크 영화." },
  { word: "007 제임스 본드", category: "대중문화", related: ["스파이"], hint: "영국 첩보국 MI6 소속의 전설적인 요원." },
  { word: "미션 임파서블", category: "대중문화", related: ["톰 크루즈"], hint: "불가능한 임무를 수행하는 요원 에단 헌트의 액션물." },
  { word: "인디아나 존스", category: "대중문화", related: ["고고학자"], hint: "모자를 쓰고 채찍을 휘두르며 보물을 찾는 모험가." },
  { word: "반지의 제왕", category: "대중문화", related: ["절대반지"], hint: "중간계의 평화를 위해 반지를 파괴하러 가는 여정." },
  { word: "캐리비안의 해적", category: "대중문화", related: ["잭 스패로우"], hint: "블랙 펄 호를 이끄는 독특한 해적 선장의 이야기." },
  { word: "겨울왕국", category: "대중문화", related: ["엘사"], hint: "모든 것을 얼려버리는 마법을 가진 여왕의 이야기 (Let It Go)." },
  { word: "올라프", category: "대중문화", related: ["눈사람"], hint: "겨울왕국에 등장하는 따뜻한 포옹을 좋아하는 캐릭터." },
  { word: "라이온 킹", category: "대중문화", related: ["심바"], hint: "아버지의 죽음 이후 왕의 자리를 되찾는 사자 이야기." },
  { word: "토이 스토리", category: "대중문화", related: ["우디"], hint: "주인이 없을 때 살아 움직이는 장난감들의 우정 이야기." },
  { word: "미키 마우스", category: "대중문화", related: ["디즈니"], hint: "큰 귀가 특징인 디즈니의 역사적인 캐릭터." },
  { word: "슈렉", category: "대중문화", related: ["피오나"], hint: "성 안의 공주를 구출하러 간 늪지대의 초록 괴물." },
  { word: "쿵푸 팬더", category: "대중문화", related: ["포"], hint: "국수를 먹던 팬더가 용의 전사가 되는 과정의 애니메이션." },
  { word: "미니언즈", category: "대중문화", related: ["슈퍼배드"], hint: "노란색 몸에 멜빵바지를 입은 귀여운 악당 조수들." },
  { word: "센과 치히로", category: "대중문화", related: ["가오나시"], hint: "미야자키 하야오의 온천을 배경으로 한 판타지 애니메이션." },
  { word: "이웃집 토토로", category: "대중문화", related: ["고양이 버스"], hint: "숲의 정령과 시골 마을 아이들의 우정을 그린 작품." },
  { word: "슬램덩크", category: "대중문화", related: ["강백호"], hint: "농구에 빠진 고등학생들의 열정을 그린 전설적인 만화." },
  { word: "드래곤볼", category: "대중문화", related: ["손오공"], hint: "7개를 모으면 소원을 들어주는 구슬을 찾는 이야기." },
  { word: "나루토", category: "대중문화", related: ["닌자"], hint: "마을의 이장이 되기 위해 수련하는 소년 닌자의 성장물." },
  { word: "원피스", category: "대중문화", related: ["루피"], hint: "해적왕이 되기 위해 보물을 찾아 떠나는 대해적 시대 이야기." },
  { word: "포켓몬", category: "대중문화", related: ["피카츄"], hint: "주머니 속의 몬스터를 수집하고 배틀하는 세계적인 게임/애니." },
  { word: "귀멸의 칼날", category: "대중문화", related: ["탄지로"], hint: "가족을 위해 도깨비와 싸우는 검사들의 이야기." },
  { word: "명탐정 코난", category: "대중문화", related: ["마취총"], hint: "몸은 작아졌지만 두뇌는 그대로인 고등학생 탐정." },
  { word: "짱구는 못말려", category: "대중문화", related: ["흰둥이"], hint: "못 말리는 5살 꼬마와 그 가족의 일상 코미디." },
  { word: "도라에몽", category: "대중문화", related: ["대나무 헬리콥터"], hint: "미래에서 온 고양이 로봇과 4차원 주머니의 도구들." },
  { word: "아기공룡 둘리", category: "대중문화", related: ["고길동"], hint: "빙하 타고 내려온 아기 공룡의 이야기를 담은 한국 고전 만화." },
  { word: "뽀로로", category: "대중문화", related: ["크롱"], hint: "아이들의 대통령이라 불리는 안경 쓴 펭귄 캐릭터." },
  { word: "시트콤", category: "대중문화", related: ["순풍산부인과"], hint: "웃음소리가 삽입된 일상 코미디 장르의 드라마." },
  { word: "예능", category: "대중문화", related: ["토크쇼"], hint: "사람들에게 즐거움을 주는 텔레비전 프로그램의 한 장르." },
  { word: "아포칼립스", category: "대중문화", related: ["포스트 아포칼립스"], hint: "세계의 멸망이나 문명이 붕괴된 상태를 다루는 장르." },
  { word: "뮤지컬", category: "대중문화", related: ["오페라"], hint: "노래와 춤이 중심이 되는 연극 공연 양식." },
  // === 디지털 세상 / DIGITAL WORLD (120단어 / 60쌍) ===
  { word: "카카오톡", category: "디지털 세상", related: ["라인"], hint: "한국인 대다수가 사용하는 국민 메신저 앱 (카톡)." },
  { word: "라인", category: "디지털 세상", related: ["카카오톡"], hint: "일본과 동남아에서 인기가 많은 초록색 아이콘의 메신저 앱." },
  { word: "유튜브", category: "디지털 세상", related: ["넷플릭스"], hint: "전 세계 최대의 동영상 공유 플랫폼." },
  { word: "넷플릭스", category: "디지털 세상", related: ["유튜브"], hint: "다양한 영화와 오리지널 시리즈를 감상하는 OTT 서비스." },
  { word: "네이버", category: "디지털 세상", related: ["구글"], hint: "초록색 검색창이 상징인 한국 최대의 포털 사이트." },
  { word: "구글", category: "디지털 세상", related: ["네이버"], hint: "세계에서 가장 많이 사용되는 검색 엔진이자 IT 기업." },
  { word: "배달의민족", category: "디지털 세상", related: ["요기요"], hint: "한국에서 가장 많이 사용하는 음식 배달 앱 (배민)." },
  { word: "요기요", category: "디지털 세상", related: ["배달의민족"], hint: "배달의민족과 경쟁하는 붉은색 로고의 배달 서비스 앱." },
  { word: "당근마켓", category: "디지털 세상", related: ["중고나라"], hint: "동네 이웃과 중고 물건을 직거래하는 인기 커뮤니티 앱." },
  { word: "중고나라", category: "디지털 세상", related: ["당근마켓"], hint: "한국 최대 규모의 온라인 중고 거래 카페 및 플랫폼." },
  { word: "인스타그램", category: "디지털 세상", related: ["틱톡"], hint: "사진과 릴스를 공유하는 소셜 네트워크 서비스 (인스타)." },
  { word: "틱톡", category: "디지털 세상", related: ["인스타그램"], hint: "숏폼 형태의 짧은 영상을 공유하는 글로벌 플랫폼." },
  { word: "쿠팡", category: "디지털 세상", related: ["로켓배송"], hint: "한국의 아마존이라 불리는 대형 온라인 쇼핑몰." },
  { word: "로켓배송", category: "디지털 세상", related: ["쿠팡"], hint: "주문하면 다음 날 바로 도착하는 쿠팡의 핵심 서비스." },
  { word: "토스", category: "디지털 세상", related: ["카카오뱅크"], hint: "간편 송금으로 시작해 은행 기능까지 갖춘 핀테크 앱." },
  { word: "카카오뱅크", category: "디지털 세상", related: ["토스"], hint: "카카오톡 기반의 모바일 전문 은행." },
  { word: "인공지능", category: "디지털 세상", related: ["로봇"], hint: "인간의 지능을 컴퓨터가 흉내 내는 기술 (AI)." },
  { word: "알고리즘", category: "디지털 세상", related: ["인공지능"], hint: "문제를 해결하기 위해 정해진 논리적 절차나 규칙." },
  { word: "챗GPT", category: "디지털 세상", related: ["대화"], hint: "사람처럼 대화하고 정보를 제공하는 생성형 AI 챗봇." },
  { word: "해커", category: "디지털 세상", related: ["바이러스"], hint: "컴퓨터 시스템에 몰래 침입하여 정보를 훔치는 사람." },
  { word: "백신", category: "디지털 세상", related: ["방화벽"], hint: "컴퓨터 바이러스를 탐지하고 치료하는 소프트웨어." },
  { word: "블록체인", category: "디지털 세상", related: ["비트코인"], hint: "데이터를 분산 저장하여 해킹을 어렵게 만드는 기술." },
  { word: "비트코인", category: "디지털 세상", related: ["가상화폐"], hint: "세계 최초이자 가장 대표적인 암호화폐." },
  { word: "와이파이", category: "디지털 세상", related: ["블루투스"], hint: "무선으로 초고속 인터넷을 즐길 수 있는 연결 방식 (Wi-Fi)." },
  { word: "블루투스", category: "디지털 세상", related: ["와이파이"], hint: "가까운 거리에서 기기끼리 선 없이 연결하는 기술." },
  { word: "리그오브레전드", category: "디지털 세상", related: ["전략"], hint: "한국에서 가장 인기 있는 팀 기반 전략 게임 (롤)." },
  { word: "배틀그라운드", category: "디지털 세상", related: ["생존"], hint: "마지막까지 살아남아야 하는 한국 개발사의 배틀로얄 게임." },
  { word: "스타크래프트", category: "디지털 세상", related: ["민속놀이"], hint: "한국 PC방 문화를 만든 전설적인 전략 게임." },
  { word: "메이플스토리", category: "디지털 세상", related: ["RPG"], hint: "귀여운 2D 캐릭터를 키우는 넥슨의 대표 온라인 게임." },
  { word: "카트라이더", category: "디지털 세상", related: ["레이싱"], hint: "다양한 아이템을 쓰며 달리는 국민 자동차 경주 게임." },
  { word: "서든어택", category: "디지털 세상", related: ["총싸움"], hint: "한국에서 오랫동안 사랑받는 1인칭 슈팅 게임 (FPS)." },
  { word: "디스코드", category: "디지털 세상", related: ["음성채팅"], hint: "게이머들이 대화하며 게임을 즐기는 소통 플랫폼." },
  { word: "스팀", category: "디지털 세상", related: ["게임기"], hint: "세계 최대 규모의 PC 게임 유통 및 다운로드 플랫폼." },
  { word: "윈도우", category: "디지털 세상", related: ["맥 OS"], hint: "전 세계 PC 점유율 1위의 운영 체제." },
  { word: "안드로이드", category: "디지털 세상", related: ["iOS"], hint: "구글에서 만든 모바일용 운영 체제." },
  { word: "아이폰", category: "디지털 세상", related: ["갤럭시"], hint: "애플에서 만든 스마트폰 시리즈." },
  { word: "갤럭시", category: "디지털 세상", related: ["아이폰"], hint: "삼성전자에서 만든 스마트폰 및 가전 브랜드." },
  { word: "플레이스테이션", category: "디지털 세상", related: ["엑스박스"], hint: "소니가 개발한 가정용 게임기 (플스)." },
  { word: "닌텐도 스위치", category: "디지털 세상", related: ["휴대용 게임기"], hint: "들고 다닐 수도 있고 TV에 연결할 수도 있는 일본의 게임기." },
  { word: "스마트워치", category: "디지털 세상", related: ["애플워치"], hint: "손목에 차는 컴퓨터 시계." },
  { word: "메타버스", category: "디지털 세상", related: ["아바타"], hint: "현실 세계처럼 활동하는 가상의 디지털 세계." },
  { word: "이메일", category: "디지털 세상", related: ["지메일"], hint: "인터넷을 통해 편지를 주고받는 서비스." },
  { word: "키보드", category: "디지털 세상", related: ["마우스"], hint: "글자를 입력하는 컴퓨터 장치." },
  { word: "마우스", category: "디지털 세상", related: ["키보드"], hint: "화면의 커서를 움직이고 클릭하는 도구." },
  { word: "모니터", category: "디지털 세상", related: ["본체"], hint: "컴퓨터의 작업 내용을 보여주는 화면." },
  { word: "프린터", category: "디지털 세상", related: ["스캐너"], hint: "디지털 문서를 종이로 뽑아주는 기계." },
  { word: "다운로드", category: "디지털 세상", related: ["업로드"], hint: "인터넷에서 내 컴퓨터로 파일을 내려받는 일." },
  { word: "업로드", category: "디지털 세상", related: ["다운로드"], hint: "파일을 서버나 인터넷에 올리는 일." },
  { word: "웹툰", category: "디지털 세상", related: ["만화"], hint: "인터넷이나 스마트폰으로 보는 한국식 디지털 만화." },
  { word: "브라우저", category: "디지털 세상", related: ["크롬"], hint: "인터넷 사이트를 보기 위해 사용하는 프로그램 (예: 웨일, 엣지)." },
  { word: "클라우드", category: "디지털 세상", related: ["저장공간"], hint: "인터넷상에 데이터를 저장해두는 가상 저장소." },
  { word: "이모티콘", category: "디지털 세상", related: ["스티커"], hint: "채팅에서 감정을 표현하기 위해 쓰는 그림 문자." },
  { word: "비밀번호", category: "디지털 세상", related: ["아이디"], hint: "계정에 로그인할 때 입력하는 나만의 암호." },
  { word: "데이터", category: "디지털 세상", related: ["트래픽"], hint: "디지털 정보의 최소 단위 혹은 통신 정보량." },
  { word: "셀피", category: "디지털 세상", related: ["셀카"], hint: "자신의 모습을 스스로 찍은 사진 (Selfie)." },
  { word: "해시태그", category: "디지털 세상", related: ["검색어"], hint: "# 기호를 써서 게시물을 분류하는 키워드." },
  { word: "스트리밍", category: "디지털 세상", related: ["라이브"], hint: "데이터를 내려받지 않고 실시간으로 재생하는 방식." },
  { word: "소프트웨어", category: "디지털 세상", related: ["하드웨어"], hint: "눈에 보이지 않는 컴퓨터의 프로그램들." },
  { word: "하드웨어", category: "디지털 세상", related: ["소프트웨어"], hint: "컴퓨터를 구성하는 물리적인 부품들." },
  { word: "버그", category: "디지털 세상", related: ["오류"], hint: "프로그램이 의도와 다르게 작동하는 실수나 결함." },
  // === 스포츠 / SPORTS (100단어 / 50쌍) ===
  { word: "축구", category: "스포츠", related: ["풋살"], hint: "발을 사용해 공을 상대 골대에 넣는 세계적인 인기 스포츠." },
  { word: "손흥민", category: "스포츠", related: ["국가대표"], hint: "한국 축구의 상징이자 프리미어리그에서 활약하는 월드클래스 선수." },
  { word: "야구", category: "스포츠", related: ["홈런"], hint: "방망이로 공을 치고 베이스를 도는 한국에서 가장 인기 있는 관람 스포츠." },
  { word: "홈런", category: "스포츠", related: ["야구"], hint: "타자가 친 공이 담장을 넘어가 모든 베이스를 돌아 득점하는 것." },
  { word: "태권도", category: "스포츠", related: ["검은 띠"], hint: "한국에서 유래한 세계적인 무술이자 올림픽 정식 종목." },
  { word: "도복", category: "스포츠", related: ["태권도"], hint: "무술을 수련할 때 입는 흰색의 전통적인 운동복." },
  { word: "양궁", category: "스포츠", related: ["활"], hint: "활을 쏘아 과녁을 맞히는 종목으로, 한국이 세계 최강인 스포츠." },
  { word: "화살", category: "스포츠", related: ["양궁"], hint: "활 시위에 걸어 과녁을 향해 날려 보내는 도구." },
  { word: "김연아", category: "스포츠", related: ["피겨 스케이팅"], hint: "한국 역사상 최고의 피겨 스케이팅 선수이자 '피겨 퀸'." },
  { word: "피겨 스케이팅", category: "스포츠", related: ["김연아"], hint: "얼음 위에서 음악에 맞춰 춤을 추고 점프를 하는 빙상 종목." },
  { word: "쇼트트랙", category: "스포츠", related: ["스피드 스케이팅"], hint: "좁은 트랙에서 순위를 다투는 빙상 경기로 한국의 메달 효자 종목." },
  { word: "스피드 스케이팅", category: "스포츠", related: ["쇼트트랙"], hint: "긴 트랙에서 누가 더 빨리 결승선에 도착하는지 겨루는 빙상 경기." },
  { word: "배구", category: "스포츠", related: ["네트"], hint: "손으로 공을 쳐서 네트 너머 상대 진영으로 넘기는 구기 종목." },
  { word: "김연경", category: "스포츠", related: ["배구"], hint: "한국 여자 배구의 전설적인 공격수이자 '식빵 언니'." },
  { word: "농구", category: "스포츠", related: ["골대"], hint: "높은 링에 공을 집어넣어 득점하는 박진감 넘치는 경기." },
  { word: "골대", category: "스포츠", related: ["농구"], hint: "축구나 농구에서 공을 넣어 점수를 얻는 목표물." },
  { word: "골프", category: "스포츠", related: ["홀인원"], hint: "채로 공을 쳐서 작은 구멍에 넣는 신사적인 스포츠." },
  { word: "홀인원", category: "스포츠", related: ["골프"], hint: "티샷 한 번에 공이 바로 구멍 안으로 들어가는 기적 같은 일." },
  { word: "테니스", category: "스포츠", related: ["라켓"], hint: "라켓을 이용해 노란 공을 네트 너머로 주고받는 스포츠." },
  { word: "라켓", category: "스포츠", related: ["테니스"], hint: "테니스나 배드민턴에서 공을 치기 위해 손에 잡는 도구." },
  { word: "배드민턴", category: "스포츠", related: ["셔틀콕"], hint: "깃털이 달린 가벼운 공을 라켓으로 주고받는 국민 생활 스포츠." },
  { word: "셔틀콕", category: "스포츠", related: ["배드민턴"], hint: "배드민턴 경기에서 사용하는 깃털 달린 공." },
  { word: "수영", category: "스포츠", related: ["수영장"], hint: "물속에서 팔다리를 저어 앞으로 나아가는 운동." },
  { word: "복싱", category: "스포츠", related: ["글러브"], hint: "글러브를 낀 두 선수가 주먹만으로 승부를 겨루는 격투기." },
  { word: "글러브", category: "스포츠", related: ["복싱"], hint: "주먹이나 손을 보호하기 위해 끼는 두툼한 장갑." },
  { word: "유도", category: "스포츠", related: ["한판"], hint: "상대방을 메치거나 누르며 승부를 겨루는 일본 유래의 무술." },
  { word: "씨름", category: "스포츠", related: ["삿바"], hint: "모래판 위에서 상대의 삿바를 잡고 쓰러뜨리는 한국 전통 경기." },
  { word: "삿바", category: "스포츠", related: ["씨름"], hint: "씨름 선수들이 허리와 다리에 둘러매는 긴 천 줄." },
  { word: "탁구", category: "스포츠", related: ["핑퐁"], hint: "작은 테이블 위에서 가벼운 공을 주고받는 스포츠." },
  { word: "볼링", category: "스포츠", related: ["핀"], hint: "무거운 공을 굴려 10개의 나무 기둥을 쓰러뜨리는 게임." },
  { word: "핀", category: "스포츠", related: ["볼링"], hint: "볼링 공에 맞고 쓰러져야 하는 세워진 목표물." },
  { word: "당구", category: "스포츠", related: ["큐대"], hint: "테이블 위에서 공을 막대기로 쳐서 구멍에 넣거나 맞히는 게임." },
  { word: "등산", category: "스포츠", related: ["산"], hint: "한국인들이 주말에 가장 많이 즐기는 건강을 위한 산행." },
  { word: "마라톤", category: "스포츠", related: ["42.195km"], hint: "기나긴 길을 쉬지 않고 달려 결승선에 도착하는 경기." },
  { word: "사이클", category: "스포츠", related: ["자전거"], hint: "자전거를 이용해 속도를 겨루거나 장거리를 이동하는 종목." },
  { word: "펜싱", category: "스포츠", related: ["검"], hint: "가늘고 긴 칼로 상대를 찌르거나 베어 점수를 얻는 신사적인 격투기." },
  { word: "양궁", category: "스포츠", related: ["과녁"], hint: "활시위를 당겨 화살을 쏘는 스포츠." },
  { word: "과녁", category: "스포츠", related: ["양궁"], hint: "화살이나 총알이 맞아야 하는 표적." },
  { word: "빙상", category: "스포츠", related: ["아이스링크"], hint: "얼음 위에서 펼쳐지는 모든 스포츠를 통칭하는 말." },
  { word: "심판", category: "스포츠", related: ["호루라기"], hint: "경기 규칙이 잘 지켜지는지 공정하게 판정하는 사람." },
  { word: "호루라기", category: "스포츠", related: ["심판"], hint: "심판이 경기를 멈추거나 신호를 보낼 때 부는 도구 (휘슬)." },
  { word: "응원", category: "스포츠", related: ["치어리더"], hint: "자신이 좋아하는 팀이나 선수가 힘을 내도록 소리치는 일." },
  { word: "치어리더", category: "스포츠", related: ["응원"], hint: "경기장에서 춤을 추며 관객들의 응원을 주도하는 사람." },
  { word: "국가대표", category: "스포츠", related: ["태극마크"], hint: "나라를 대표하여 국제 경기에 출전하는 최고의 선수들." },
  { word: "태극마크", category: "스포츠", related: ["국가대표"], hint: "한국 대표팀 유니폼에 새겨진 한국의 상징." },
  { word: "올림픽", category: "스포츠", related: ["오륜기"], hint: "4년마다 열리는 세계 최대의 스포츠 축제." },
  { word: "월드컵", category: "스포츠", related: ["피파"], hint: "4년마다 열리는 전 세계적인 축구 축제." },
  { word: "금메달", category: "스포츠", related: ["우승"], hint: "결승전에서 승리하여 1등을 차지한 선수에게 주는 보상." },
  { word: "동메달", category: "스포츠", related: ["3위"], hint: "3등을 차지한 선수에게 주어지는 메달." },
  { word: "은메달", category: "스포츠", related: ["2위"], hint: "결승에서 아쉽게 져서 2등을 한 선수에게 주는 메달." },
  { word: "전반전", category: "스포츠", related: ["후반전"], hint: "경기의 첫 번째 절반을 이르는 말." },
  { word: "연장전", category: "스포츠", related: ["승부차기"], hint: "정규 시간이 끝났지만 승부가 나지 않아 추가로 진행하는 경기." },
  { word: "승부차기", category: "스포츠", related: ["골키퍼"], hint: "축구에서 무승부일 때 킥으로 승패를 정하는 방식." },
  { word: "파울", category: "스포츠", related: ["반칙"], hint: "경기 규칙을 어기는 행위." },
  { word: "경고", category: "스포츠", related: ["옐로카드"], hint: "규칙을 어겼을 때 심판이 주의를 주는 것." },
  { word: "퇴장", category: "스포츠", related: ["레드카드"], hint: "심각한 반칙으로 경기장 밖으로 쫓겨나는 것." },
  { word: "에이스", category: "스포츠", related: ["주전"], hint: "팀 내에서 가장 실력이 뛰어나고 신뢰받는 선수." },
  { word: "슬램덩크", category: "스포츠", related: ["만화"], hint: "한국에서도 엄청난 인기를 끈 전설적인 농구 만화 제목." },
  { word: "클라이밍", category: "스포츠", related: ["암벽등반"], hint: "인공 구조물이나 바위를 타고 오르는 운동." },
  { word: "스노보드", category: "스포츠", related: ["겨울스포츠"], hint: "눈 덮인 산에서 보드를 타고 내려오는 스포츠." },
  { word: "서핑", category: "스포츠", related: ["파도"], hint: "바다의 파도를 타고 즐기는 해양 스포츠." },
  { word: "요가", category: "스포츠", related: ["필라테스"], hint: "명상과 호흡, 스트레칭을 결합한 심신 수련 운동." },
  { word: "필라테스", category: "스포츠", related: ["요가"], hint: "근육 강화와 자세 교정을 목적으로 하는 체계적인 운동." },
  { word: "준비운동", category: "스포츠", related: ["부상방지"], hint: "본격적인 운동 전에 몸을 푸는 과정." },
  { word: "운동화", category: "스포츠", related: ["러닝화"], hint: "운동할 때 발을 보호하기 위해 신는 신발." },
  { word: "체육관", category: "스포츠", related: ["강당"], hint: "실내에서 운동 경기를 할 수 있도록 만든 건물." },
  { word: "스타디움", category: "스포츠", related: ["경기장"], hint: "수만 명의 관중이 모일 수 있는 커다란 야외 경기 시설." },
  { word: "라커룸", category: "스포츠", related: ["대기실"], hint: "선수들이 옷을 갈아입고 작전 회의를 하는 방." },
  { word: "전광판", category: "스포츠", related: ["점수"], hint: "경기의 현재 상황과 점수를 보여주는 커다란 화면." },
  { word: "하프타임", category: "스포츠", related: ["휴식"], hint: "경기 중간에 주어지는 선수들의 휴식 시간." },
  { word: "역전", category: "스포츠", related: ["재역전"], hint: "지고 있던 팀이 점수를 더 내서 상황을 뒤집는 것." },
  { word: "아시안 게임", category: "스포츠", related: ["아시아"], hint: "아시아 국가들이 모여 4년마다 개최하는 스포츠 대회." },
  { word: "병역혜택", category: "스포츠", related: ["금메달"], hint: "한국 남자 선수들이 국제 대회 우승 시 받는 아주 중요한 혜택." },
  { word: "치맥", category: "스포츠", related: ["야구장"], hint: "한국에서 야구나 축구를 보며 즐기는 치킨과 맥주 조합." },
  { word: "시구", category: "스포츠", related: ["야구"], hint: "야구 경기 시작 전 유명인이 공을 던지는 이벤트." },
  // === 과학과 자연 / SCIENCE & NATURE (130단어 / 65쌍) ===
  { word: "은하계", category: "과학과 자연", related: ["별"], hint: "수많은 별과 가스, 먼지가 모여 있는 거대한 우주 체계." },
  { word: "별", category: "과학과 자연", related: ["은하계"], hint: "스스로 빛과 열을 내는 천체 (항성)." },
  { word: "행성", category: "과학과 자연", related: ["위성"], hint: "태양 같은 항성 주위를 도는 커다란 천체 (예: 지구, 화성)." },
  { word: "위성", category: "과학과 자연", related: ["행성"], hint: "행성 주위를 도는 천체 (예: 달, 인공위성)." },
  { word: "태양", category: "과학과 자연", related: ["달"], hint: "우리 태양계의 중심이자 에너지의 근원인 별." },
  { word: "달", category: "과학과 자연", related: ["태양"], hint: "지구 주위를 도는 유일한 자연 위성." },
  { word: "블랙홀", category: "과학과 자연", related: ["중력"], hint: "중력이 너무 강해 빛조차 빠져나갈 수 없는 우주 공간." },
  { word: "중력", category: "과학과 자연", related: ["블랙홀"], hint: "물체를 지구 중심 방향으로 끌어당기는 힘." },
  { word: "혜성", category: "과학과 자연", related: ["소행성"], hint: "태양 근처를 지날 때 꼬리가 생기는 얼음과 먼지 덩어리." },
  { word: "소행성", category: "과학과 자연", related: ["혜성"], hint: "태양 주변을 공전하는 행성보다 작은 바위 덩어리." },
  { word: "망원경", category: "과학과 자연", related: ["렌즈"], hint: "먼 곳에 있는 물체를 크고 뚜렷하게 보기 위한 도구." },
  { word: "누리호", category: "과학과 자연", related: ["로켓"], hint: "한국이 독자적으로 개발한 한국형 발사체(로켓)." },
  { word: "로켓", category: "과학과 자연", related: ["누리호"], hint: "가스를 뿜어내는 힘으로 우주로 나아가는 비행체." },
  { word: "우주인", category: "과학과 자연", related: ["우주정거장"], hint: "우주선을 타고 우주로 나가 탐사 업무를 수행하는 사람." },
  { word: "DNA", category: "과학과 자연", related: ["유전자"], hint: "생물의 설계도라 불리는 유전 정보를 담은 물질." },
  { word: "세포", category: "과학과 자연", related: ["DNA"], hint: "생명체를 구성하는 가장 기본적인 단위." },
  { word: "박테리아", category: "과학과 자연", related: ["바이러스"], hint: "눈에 보이지 않는 아주 작은 단세포 생물 (세균)." },
  { word: "바이러스", category: "과학과 자연", related: ["박테리아"], hint: "세균보다 작으며 생물체에 감염되어 증식하는 존재." },
  { word: "뇌", category: "과학과 자연", related: ["신경"], hint: "우리 몸의 행동과 생각을 조절하는 중심 기관." },
  { word: "심장", category: "과학과 자연", related: ["혈액"], hint: "온몸에 피를 공급하기 위해 끊임없이 뛰는 펌프 기관." },
  { word: "혈액", category: "과학과 자연", related: ["심장"], hint: "몸속 혈관을 따라 돌며 산소와 영양분을 전달하는 붉은 액체." },
  { word: "허파", category: "과학과 자연", related: ["호흡"], hint: "숨을 쉴 때 산소를 받아들이고 이산화탄소를 내뱉는 기관 (폐)." },
  { word: "뼈", category: "과학과 자연", related: ["근육"], hint: "우리 몸의 형태를 유지하고 장기를 보호하는 딱딱한 조직." },
  { word: "근육", category: "과학과 자연", related: ["뼈"], hint: "수축과 이완을 통해 우리 몸을 움직이게 하는 조직." },
  { word: "진화론", category: "과학과 자연", related: ["다윈"], hint: "생물이 환경에 적응하며 오랜 시간 변해왔다는 이론." },
  { word: "광합성", category: "과학과 자연", related: ["엽록소"], hint: "식물이 햇빛을 이용해 스스로 영양분을 만드는 과정." },
  { word: "엽록소", category: "과학과 자연", related: ["광합성"], hint: "식물이 초록색을 띠게 하며 빛을 흡수하는 색소." },
  { word: "뿌리", category: "과학과 자연", related: ["줄기"], hint: "땅속에서 물과 영양분을 흡수하고 식물을 지탱하는 부분." },
  { word: "줄기", category: "과학과 자연", related: ["뿌리"], hint: "뿌리와 잎 사이에서 영양분이 이동하는 통로 역할을 하는 부분." },
  { word: "꽃", category: "과학과 자연", related: ["꽃가루"], hint: "식물이 번식하기 위해 피우는 화려하고 향기로운 부분." },
  { word: "열매", category: "과학과 자연", related: ["씨앗"], hint: "꽃이 진 뒤 맺히며 속에 씨앗을 품고 있는 부분." },
  { word: "화산", category: "과학과 자연", related: ["용암"], hint: "지하 깊은 곳의 마그마가 지표면으로 분출되는 산." },
  { word: "용암", category: "과학과 자연", related: ["화산"], hint: "화산이 폭발할 때 흘러나오는 뜨거운 액체 상태의 암석." },
  { word: "지진", category: "과학과 자연", related: ["쓰나미"], hint: "지각의 변동으로 땅이 갑자기 흔들리는 현상." },
  { word: "쓰나미", category: "과학과 자연", related: ["지진"], hint: "지진이나 화산 폭발로 인해 발생하는 거대한 파도 (해일)." },
  { word: "태풍", category: "과학과 자연", related: ["토네이도"], hint: "강한 바람과 비를 동반하여 북상하는 열대성 저기압." },
  { word: "토네이도", category: "과학과 자연", related: ["태풍"], hint: "깔때기 모양의 구름과 함께 발생하는 강력한 회오리바람." },
  { word: "번개", category: "과학과 자연", related: ["천둥"], hint: "구름 사이나 구름과 지면 사이에 발생하는 강력한 불꽃 방전." },
  { word: "천둥", category: "과학과 자연", related: ["번개"], hint: "번개가 칠 때 발생하는 공기의 진동 소리." },
  { word: "눈", category: "과학과 자연", related: ["얼음"], hint: "대기 중의 수증기가 얼어 결정체가 되어 떨어지는 것." },
  { word: "얼음", category: "과학과 자연", related: ["눈"], hint: "물이 얼어서 고체가 된 상태." },
  { word: "사막", category: "과학과 자연", related: ["오아시스"], hint: "비가 거의 오지 않아 모래나 바위만 있는 메마른 땅." },
  { word: "오아시스", category: "과학과 자연", related: ["사막"], hint: "사막 한가운데에 물이 있고 나무가 자라는 곳." },
  { word: "원자", category: "과학과 자연", related: ["분자"], hint: "물질을 구성하는 가장 기본적인 작은 입자." },
  { word: "분자", category: "과학과 자연", related: ["원자"], hint: "두 개 이상의 원자가 결합하여 물질의 성질을 가진 가장 작은 입자." },
  { word: "전기", category: "과학과 자연", related: ["자기장"], hint: "전하의 흐름으로 발생하는 에너지 형태." },
  { word: "자석", category: "과학과 자연", related: ["전기"], hint: "철을 끌어당기는 성질을 가진 물체." },
  { word: "무지개", category: "과학과 자연", related: ["프리즘"], hint: "비가 온 뒤 햇빛이 물방울에 굴절되어 나타나는 7색의 띠." },
  { word: "소리", category: "과학과 자연", related: ["진동"], hint: "물체의 떨림이 공기를 타고 귀에 전달되는 현상." },
  { word: "진동", category: "과학과 자연", related: ["소리"], hint: "물체가 빠르게 왔다 갔다 하며 떨리는 움직임." },
  { word: "산성", category: "과학과 자연", related: ["염기성"], hint: "신맛이 나며 리트머스 종이를 붉게 변화시키는 성질 (pH 7 미만)." },
  { word: "염기성", category: "과학과 자연", related: ["산성"], hint: "쓴맛이 나고 미끌거리는 성질 (pH 7 초과)." },
  { word: "수증기", category: "과학과 자연", related: ["액체"], hint: "물이 열을 받아 기체 상태가 된 것." },
  { word: "봄", category: "과학과 자연", related: ["가을"], hint: "추운 겨울이 지나고 꽃이 피는 따뜻한 계절." },
  { word: "여름", category: "과학과 자연", related: ["겨울"], hint: "햇볕이 뜨겁고 장마가 있는 무더운 계절." },
  { word: "가을", category: "과학과 자연", related: ["봄"], hint: "낙엽이 지고 곡식을 거두는 선선한 계절." },
  { word: "겨울", category: "과학과 자연", related: ["여름"], hint: "눈이 내리고 기온이 영하로 떨어지는 추운 계절." },
  { word: "밀물", category: "과학과 자연", related: ["썰물"], hint: "바닷물이 육지 쪽으로 들어와 수위가 높아지는 현상." },
  { word: "생태계", category: "과학과 자연", related: ["서식지"], hint: "생물과 그들을 둘러싼 환경이 조화를 이루며 살아가는 체계." },
  { word: "화석", category: "과학과 자연", related: ["공룡"], hint: "아주 오래전 생물의 유해나 흔적이 땅속에 굳어 남은 것." },
  { word: "세종과학기지", category: "과학과 자연", related: ["남극"], hint: "한국이 남극 탐사를 위해 세운 첫 번째 과학 기지." },
  { word: "대기", category: "과학과 자연", related: ["진공"], hint: "지구를 둘러싸고 있는 공기 층." },
  { word: "마찰력", category: "과학과 자연", related: ["열"], hint: "두 물체가 닿아 움직일 때 방해하는 힘." },
  { word: "속도", category: "과학과 자연", related: ["가속도"], hint: "물체가 움직이는 빠르기와 방향." },
  { word: "온도계", category: "과학과 자연", related: ["온도"], hint: "물질의 뜨겁고 차가운 정도를 숫자로 나타내는 도구." },
  // === 다양한 명사 / VARIED NOUNS (첫 번째 블록 - 100단어 / 50쌍) ===
  { word: "출연진", category: "다양한 명사", related: ["오케스트라"], hint: "영화나 연극에서 역할을 맡아 연기하는 사람들의 무리 (엘리트)." },
  { word: "오케스트라", category: "다양한 명사", related: ["출연진"], hint: "지휘자의 지휘 아래 여러 악기를 연주하는 음악가들의 집단." },
  { word: "콘클라베", category: "다양한 명사", related: ["공의회"], hint: "새로운 교황을 선출하기 위해 열리는 추기경들의 비밀 회의." },
  { word: "공의회", category: "다양한 명사", related: ["콘클라베"], hint: "종교적인 교리나 규칙을 결정하기 위해 모이는 권위 있는 회의." },
  { word: "법전", category: "다양한 명사", related: ["헌법"], hint: "특정 분야의 법률이나 규칙을 체계적으로 정리해 놓은 책." },
  { word: "헌법", category: "다양한 명사", related: ["법전"], hint: "국가의 통치 조직과 국민의 기본권을 규정한 최상위 법." },
  { word: "민주주의", category: "다양한 명사", related: ["공화국"], hint: "국민이 권력을 가지고 스스로 다스리는 정치 체제." },
  { word: "공화국", category: "다양한 명사", related: ["민주주의"], hint: "주권이 국민에게 있고 선출된 대표가 통치하는 국가 형태." },
  { word: "군주제", category: "다양한 명사", related: ["제국"], hint: "국왕이나 황제가 국가의 통치권을 갖는 정치 체제." },
  { word: "정의", category: "다양한 명사", related: ["자유"], hint: "사회를 올바르게 유지하기 위한 공정하고 바른 도리." },
  { word: "자유", category: "다양한 명사", related: ["정의"], hint: "남에게 구속받지 않고 자기 의지대로 행동할 수 있는 상태." },
  { word: "눈치", category: "다양한 명사", related: ["센스"], hint: "타인의 기분이나 상황을 빠르게 파악하는 한국 특유의 감각." },
  { word: "정", category: "다양한 명사", related: ["사랑"], hint: "오랜 시간 함께하며 쌓인 따뜻하고 끈끈한 한국인의 마음." },
  { word: "효도", category: "다양한 명사", related: ["불효"], hint: "부모님을 정성껏 잘 모시는 자식의 도리." },
  { word: "군집", category: "다양한 명사", related: ["무리"], hint: "사람이나 생물이 한곳에 떼를 지어 모여 있는 상태." },
  { word: "제도", category: "다양한 명사", related: ["시스템"], hint: "관습이나 법률 등에 의하여 정해진 사회적 규범." },
  { word: "성공", category: "다양한 명사", related: ["실패"], hint: "목적한 바를 이룸." },
  { word: "실패", category: "다양한 명사", related: ["성공"], hint: "일이 목적대로 되지 않거나 수포로 돌아감." },
  { word: "명예", category: "다양한 명사", related: ["존엄"], hint: "세상으로부터 인정받는 좋은 이름이나 자랑스러운 존엄성." },
  { word: "존엄", category: "다양한 명사", related: ["명예"], hint: "범접할 수 없는 높고 엄숙한 가치." },
  { word: "죄책감", category: "다양한 명사", related: ["후회"], hint: "자신이 저지른 잘못에 대해 스스로 느끼는 가책." },
  { word: "후회", category: "다양한 명사", related: ["죄책감"], hint: "이전에 한 일이 잘못되었다고 생각하여 아쉬워함." },
  { word: "질투", category: "다양한 명사", related: ["부러움"], hint: "다른 사람이 잘되는 것을 시기하고 미워하는 마음." },
  { word: "욕심", category: "다양한 명사", related: ["질투"], hint: "분수에 넘치게 무엇을 탐내거나 누리고자 하는 마음." },
  { word: "자비", category: "다양한 명사", related: ["동정"], hint: "남을 깊이 사랑하고 가엾게 여겨서 베푸는 마음." },
  { word: "동정", category: "다양한 명사", related: ["자비"], hint: "남의 어려운 처지를 보고 안타깝게 여기는 마음." },
  { word: "동맹", category: "다양한 명사", related: ["조약"], hint: "개인이나 국가가 서로 돕기로 약속하여 맺는 관계." },
  { word: "조약", category: "다양한 명사", related: ["동맹"], hint: "국가 간의 합의를 서면으로 기록한 법적 약속." },
  { word: "딜레마", category: "다양한 명사", related: ["선택"], hint: "두 가지 선택지 사이에서 어느 쪽도 고르기 어려운 상황." },
  { word: "선택", category: "다양한 명사", related: ["딜레마"], hint: "여러 개 중에서 하나를 골라잡음." },
  { word: "미스터리", category: "다양한 명사", related: ["비밀"], hint: "설명하거나 이해하기 어려운 신비하고 불가사의한 일." },
  { word: "비밀", category: "다양한 명사", related: ["미스터리"], hint: "남에게 알리지 않고 숨기는 정보." },
  { word: "운명", category: "다양한 명사", related: ["우연"], hint: "인간의 힘을 초월하여 정해져 있는 필연적인 전개." },
  { word: "우연", category: "다양한 명사", related: ["운명"], hint: "아무런 인과관계 없이 뜻하지 않게 일어난 일." },
  { word: "카오스", category: "다양한 명사", related: ["질서"], hint: "천지창조 이전의 혼돈 상태 또는 무질서함." },
  { word: "질서", category: "다양한 명사", related: ["카오스"], hint: "혼란 없이 조화롭게 유지되는 상태나 순서." },
  { word: "이론", category: "다양한 명사", related: ["실제"], hint: "사물의 이치나 지식을 논리적으로 정리한 것." },
  { word: "실제", category: "다양한 명사", related: ["이론"], hint: "생각이나 논리가 아닌 현실의 상태." },
  { word: "전설", category: "다양한 명사", related: ["신화"], hint: "과거부터 입으로 전해 내려오는 인물이나 장소에 관한 이야기." },
  { word: "신화", category: "다양한 명사", related: ["전설"], hint: "우주의 기원이나 신들의 활동을 다룬 신비로운 이야기." },
  { word: "진실", category: "다양한 명사", related: ["거짓"], hint: "거짓이 없는 사실 그대로의 모습." },
  { word: "거짓", category: "다양한 명사", related: ["진실"], hint: "사실과 다르게 꾸며 낸 것." },
  { word: "꿈", category: "다양한 명사", related: ["악몽"], hint: "잠자는 동안 겪는 정신 현상 또는 미래의 희망." },
  { word: "악몽", category: "다양한 명사", related: ["꿈"], hint: "무섭고 괴로운 내용의 꿈." },
  { word: "자만심", category: "다양한 명사", related: ["자부심"], hint: "자신을 지나치게 높게 평가하여 뽐내는 마음." },
  { word: "자부심", category: "다양한 명사", related: ["자만심"], hint: "자기 자신이나 소속된 집단에 대해 가지는 긍지." },
  { word: "슬픔", category: "다양한 명사", related: ["기쁨"], hint: "마음이 아프고 괴로운 감정." },
  { word: "기쁨", category: "다양한 명사", related: ["슬픔"], hint: "만족스럽고 즐거운 감정." },
  { word: "평화", category: "다양한 명사", related: ["전쟁"], hint: "분쟁이나 전쟁 없이 평온한 상태." },
  { word: "전쟁", category: "다양한 명사", related: ["평화"], hint: "국가나 집단 간에 무력을 사용하여 싸우는 상태." },
    { word: "지혜", category: "다양한 명사", related: ["지식"], hint: "사물의 이치를 빨리 깨닫고 사물을 정확하게 처리하는 정신적 능력." },
  { word: "경험", category: "다양한 명사", related: ["지혜"], hint: "자신이 실제로 해 보거나 겪어 봄. 또는 거기서 얻은 지식." },
  { word: "신뢰", category: "다양한 명사", related: ["의심"], hint: "굳게 믿고 의지함." },
  { word: "의심", category: "다양한 명사", related: ["신뢰"], hint: "확실히 믿지 못하고 의아하게 여김." },
  { word: "논리", category: "다양한 명사", related: ["이성"], hint: "말이나 글의 조리. 또는 생각하는 과정의 법칙." },
  { word: "이성", category: "다양한 명사", related: ["논리"], hint: "본능이나 감정에 치우치지 않고 판단하는 능력." },
  { word: "기억", category: "다양한 명사", related: ["망각"], hint: "과거의 사실을 잊지 않고 머릿속에 간직함." },
  { word: "망각", category: "다양한 명사", related: ["기억"], hint: "어떤 사실이나 내용을 잊어버림." },
  { word: "예의", category: "다양한 명사", related: ["도덕"], hint: "존중의 마음을 담아 지켜야 할 말투나 행동의 규범." },
  { word: "도덕", category: "다양한 명사", related: ["예의"], hint: "사회의 구성원으로서 지켜야 할 도리나 바람직한 행동 기준." },
  { word: "한", category: "다양한 명사", related: ["슬픔"], hint: "억울하고 원통한 마음이 쌓여 맺힌 한국 특유의 슬픈 정서." },
  { word: "흥", category: "다양한 명사", related: ["즐거움"], hint: "기분이 좋아 어깨춤이 절로 나는 한국 특유의 즐거운 에너지." },
  { word: "용기", category: "다양한 명사", related: ["두려움"], hint: "씩씩하고 굳센 기운. 겁내지 않는 마음." },
  { word: "인기", category: "다양한 명사", related: ["명성"], hint: "대중의 지지를 얻거나 사회적으로 좋아하는 기운." },
  { word: "명성", category: "다양한 명사", related: ["인기"], hint: "이름이 널리 알려져 얻게 된 높은 평판." },
  { word: "재능", category: "다양한 명사", related: ["노력"], hint: "어떤 일을 잘할 수 있는 타고난 능력." },
  { word: "노력", category: "다양한 명사", related: ["재능"], hint: "목적을 이루기 위해 몸과 마음을 다해 애씀." },
  { word: "직관", category: "다양한 명사", related: ["예감"], hint: "판단이나 추론 없이 대상을 직접 파악하는 능력." },
  { word: "예감", category: "다양한 명사", related: ["직관"], hint: "앞으로 일어날 일에 대해 미리 느껴지는 기분." },
  { word: "지루함", category: "다양한 명사", related: ["따분함"], hint: "상태가 오래 계속되어 재미가 없고 싫증이 나는 마음." },
  { word: "외로움", category: "다양한 명사", related: ["고독"], hint: "혼자 떨어져 있거나 의지할 곳이 없어 쓸쓸한 마음." },
  { word: "용서", category: "다양한 명사", related: ["자비"], hint: "잘못한 일에 대해 꾸짖거나 벌주지 않고 너그럽게 보아줌." },
  { word: "비난", category: "다양한 명사", related: ["칭찬"], hint: "남의 결점을 캐내어 나쁘게 말함." },
  { word: "칭찬", category: "다양한 명사", related: ["비난"], hint: "좋은 점이나 착하고 훌륭한 일을 높이 평가함." },
  { word: "영원", category: "다양한 명사", related: ["순간"], hint: "끝없이 이어지는 시간의 상태." },
  { word: "순간", category: "다양한 명사", related: ["영원"], hint: "아주 짧은 시간." },
  { word: "공허", category: "다양한 명사", related: ["허무"], hint: "아무것도 없이 텅 비어 있는 상태." },
  { word: "풍요", category: "다양한 명사", related: ["부유"], hint: "물건이나 자원이 매우 넉넉함." },
  { word: "가난", category: "다양한 명사", related: ["빈곤"], hint: "살림살이가 넉넉하지 못하고 궁핍함." },
  { word: "사치", category: "다양한 명사", related: ["낭비"], hint: "필요 이상의 돈이나 물건을 쓰며 분수에 지나친 생활을 함." },
  { word: "절약", category: "다양한 명사", related: ["아낌"], hint: "함부로 쓰지 않고 아껴 씀." },
  { word: "리듬", category: "다양한 명사", related: ["멜로디"], hint: "음의 길고 짧음이 반복되는 규칙적인 흐름." },
  { word: "멜로디", category: "다양한 명사", related: ["리듬"], hint: "높낮이가 있는 음의 연속적인 흐름 (선율)." },
  { word: "침묵", category: "다양한 명사", related: ["소음"], hint: "아무 말도 하지 않고 조용히 있음." },
  { word: "소음", category: "다양한 명사", related: ["침묵"], hint: "불쾌하고 시끄러운 소리." },
  { word: "운", category: "다양한 명사", related: ["실력"], hint: "이미 정해져 있거나 뜻하지 않게 찾아오는 좋은 기회." },
  { word: "실력", category: "다양한 명사", related: ["운"], hint: "실제로 갖추고 있는 능력." },
  { word: "전통", category: "다양한 명사", related: ["관습"], hint: "지난 세대부터 전해 내려오는 계통." },
  { word: "관습", category: "다양한 명사", related: ["전통"], hint: "사회에서 오랫동안 되풀이되어 굳어진 행동 양식." },
  { word: "국경", category: "다양한 명사", related: ["경계"], hint: "나라와 나라 사이의 경계선." },
  { word: "한계", category: "다양한 명사", related: ["끝"], hint: "더 이상 넘기 어려운 범위나 지점." },
  { word: "영감", category: "다양한 명사", related: ["아이디어"], hint: "창조적인 일을 할 때 갑자기 떠오르는 기발한 생각." },
  { word: "법률", category: "다양한 명사", related: ["질서"], hint: "국가에서 강제로 지키게 정한 사회 규범." },
  { word: "평등", category: "다양한 명사", related: ["차별"], hint: "권리나 의무, 대우 등이 차별 없이 고름." },
  { word: "차별", category: "다양한 명사", related: ["평등"], hint: "등급이나 수준에 따라 차등을 두어 대우함." },
  { word: "인권", category: "다양한 명사", related: ["권리"], hint: "사람으로서 당연히 누려야 할 기본적 권리." },
  { word: "우정", category: "다양한 명사", related: ["의리"], hint: "친구 사이의 두터운 정." },
  { word: "의리", category: "다양한 명사", related: ["우정"], hint: "사람으로서 마땅히 지켜야 할 도리나 관계에서의 신의." },
  { word: "수수께끼", category: "다양한 명사", related: ["퀴즈"], hint: "어떤 사물에 대해 에둘러 말하여 알아맞히는 놀이." },
  { word: "비유", category: "다양한 명사", related: ["상징"], hint: "어떤 현상이나 사물을 비슷한 것에 빗대어 표현함." },
]